akka/alpakka

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/file.md
- file/src/main/java/akka/stream/alpakka/file/DirectoryChange.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/DirectoryChangesSource.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/FileTailSource.java
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/DirectoryChangesSource.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/FileTailSource.scala
- file/src/test/java/akka/stream/alpakka/file/javadsl/DirectoryChangesSourceTest.java
- file/src/test/java/akka/stream/alpakka/file/javadsl/FileTailSourceTest.java
- file/src/test/scala/akka/stream/alpakka/file/scaladsl/DirectoryChangesSourceSpec.scala
- file/src/test/scala/akka/stream/alpakka/file/scaladsl/FileTailSourceSpec.scala
- project/Dependencies.scala
> New files module ported from streams-contrib

- .travis.yml
- CONTRIBUTING.md
- build.sbt
- project/Common.scala
- project/Dependencies.scala
- project/Publish.scala
- project/build.properties
- project/plugins.sbt
This is my attempt at the automated release process. I literally got stuck while uploading docs from Travis. Rsync freezes promptly after starting up with:
```
sending incremental file list
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]
```
That is blocking automating pushing docs to the server.
Also I had to created private/public keypair and encrypt the private part to `.travis_rsa_id.enc` which is then decrypted and used to upload docs to server during the CI build. I was not able to reuse the keypair managed by Travis for ssh, therefore this key/pair.
With this merged building and publishing JARs after creating GitHub release will work. However docs will have to be pushed …
> Auto release process

- docs/src/main/paradox/external-connectors.md
> Eventuate and FS2 connectors

- docs/src/main/paradox/external-connectors.md
> Add link to reactive mongo

- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/file.md
- docs/src/main/paradox/mqtt.md
> Fixed incorrect groupIds in the docs of amqp, file and mqtt

- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
> Fix Amqp pub-sub tests to not depend on broker timings

- README.md
Resolves #100 by applying an *Old Klangian Proverb*
> explain maintenance philosophy

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/model.scala
Add SSL protocol version override to the AmqpConnectionDetails case class. This is for issue https://github.com/akka/alpakka/issues/95
> Add AMQP Config for SSL protocol

- README.md
Just a small PR to upgrade the API and reference link in the readme to the last version (0.3)
> Update API and reference link to version 0.3

- docs/src/main/paradox/external-connectors.md
Camel DSL for Akka Streams
- closes #74
> Camel DSL for Akka Streams

- s3/src/test/scala/akka/stream/alpakka/s3/impl/DiskBufferSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MemoryBufferSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/SplitAfterSizeSpec.scala
> =s3 Add patiene config for S3 tests

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpGraphStageLogic.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
> FTP: Improve type safety wrt settings (closes #116)

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
This is to resolve issue https://github.com/akka/alpakka/issues/124
> Fix for issue #124

- .travis.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/mqtt.md
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttProducerStage.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttSourceStage.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/MqttSink.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSink.scala
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttSourceTest.java
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSinkSpec.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
- mqtt/src/test/travis/acl
- mqtt/src/test/travis/auth.conf
- mqtt/src/test/travis/password
- project/Dependencies.scala
Also run mqtt broker in docker
> Add Mqtt Sink

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpGraphStageLogic.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/CommonFtpSourceTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpBaseSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpSupport.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpSourceSpec.scala
Some cleaning and testing improvements have also been made.
closes #133
> FTP: Improve thread-safety not sharing FTP clients (closes #133)

- docs/src/main/paradox/dynamodb.md
- docs/src/main/paradox/sqs.md
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
Will create a separate PR that runs paradox in travis
> Fix references to example code

- .travis.yml
> Build docs on PR validation

- docs/src/main/paradox/dynamodb.md
As noted by in #150 by @joost-de-vries
> Fixed incorrect groupid in docs for dynamodb connector

- build.sbt
- docs/src/main/paradox/sse.md
- project/Dependencies.scala
- sse/src/main/scala/akka/stream/alpakka/sse/javadsl/EventSource.scala
- sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
- sse/src/test/scala/akka/stream/alpakka/sse/scaladsl/EventSourceSpec.scala
Java API and docs missing and depending on a milestone of akka-sse. But the Scala API and tests are ready for review.
> Add SSE connector

- awslambda/src/main/scala/akka/stream/alpakka/awslambda/AwsLambdaFlowStage.scala
- awslambda/src/main/scala/akka/stream/alpakka/awslambda/javadsl/AwsLambdaFlow.scala
- awslambda/src/main/scala/akka/stream/alpakka/awslambda/scaladsl/AwsLambdaFlow.scala
- awslambda/src/test/java/akka/stream/alpakka/awslambda/javadsl/AwsLambdaFlowTest.java
- awslambda/src/test/java/akka/stream/alpakka/awslambda/javadsl/Examples.java
- awslambda/src/test/scala/akka/stream/alpakka/awslambda/scaladsl/AwsLambdaFlowSpec.scala
- awslambda/src/test/scala/akka/stream/alpakka/awslambda/scaladsl/Examples.scala
- build.sbt
- docs/src/main/paradox/awslambda.md
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
Rebase of PR https://github.com/akka/alpakka/pull/169
> Added aws lambda flow implementation

- scripts/authors.scala
> include authors script for release stats

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala
with this we can connect with ssl to mqtt broker, see #219
> Allow to pass a `SSLSocketFactory` to `MqttConnectionSettings`

- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSourceTest.java
- Reduce amount of sent messages to 1 (multiple batch streaming is tested in the SqsSourceSpec)
- Increase timeout
- Solves #245
> Fix SqsSourceTest

- README.md
And make docs links less scary to click on :)
> README: add scaladex, travis badges

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttSourceStage.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
And increase the timeout. Might help with #189, or otherwise help generate a
better error message when it does happen again.
> Fail MqttSourceStage mat. value on connection loss

- ftp/src/test/java/akka/stream/alpakka/ftp/PlainFtpSupportImpl.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
I couldn't reproduce the problem but these settings might help to improve the situation. #267
> FTP: Attempt to fix flaky test on Travis

- sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
Unfortunately there's no easy way for an automated test, because testing requires killing an SSE server forcibly. docker-it might be a solution, but this plugin hasn't been used for Alpakka so far.
Anyway, the existing (not exhaustive) tests are still green, hence I consider it a valid refactoring. And of course it really fixes the bug ;-)
> Fix broken recovery of EventSource (sse)

- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/awslambda.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/csv.md
- docs/src/main/paradox/dynamodb.md
- docs/src/main/paradox/file.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-cloud-pub-sub.md
- docs/src/main/paradox/ironmq.md
- docs/src/main/paradox/jms.md
- docs/src/main/paradox/mqtt.md
- docs/src/main/paradox/recordio.md
- docs/src/main/paradox/s3.md
- docs/src/main/paradox/sns.md
- docs/src/main/paradox/sqs.md
- docs/src/main/paradox/sse.md
@2m Sorry for leaving it like this in the first place.
(see #278)
> Replace scala.binaryVersion with scalaBinaryVersion 

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/model.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Hi,
I added additional configuration options as described in #191. 
Please let me know what you think.
Matthias
> AMQP: add more options to configuration of the ConnectionFactory, #191

- csv/src/main/scala/akka/stream/alpakka/csv/CsvParser.scala
- csv/src/test/resources/correctness.csv
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- csv/src/test/scala/akka/stream/alpakka/csv/scaladsl/CsvParsingSpec.scala
> CSV: Fixes ignored second double quote

- project/Dependencies.scala
> Use elasticmq as test dependency

- build.sbt
- project/Dependencies.scala
that mentions a couple of frequently used sbt tasks.
> Add Alpakka banner

- xml/src/test/scala/akka/stream/alpakka/xml/scaladsl/XmlCoalesceTest.scala
- xml/src/test/scala/akka/stream/alpakka/xml/scaladsl/XmlProcessingTest.scala
- xml/src/test/scala/akka/stream/alpakka/xml/scaladsl/XmlSubsliceTest.scala
Hey guys, first PR, just cleaning some stuff up.
I signed the CLA, not sure how to prove it though.
https://github.com/akka/alpakka/issues/321
> XML: make code in tests more consistent

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
> S3: Fix bug with invalid continuation token

- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ClientSpec.scala
> S3: fix application.conf being loaded for the second time (fixes #348)

- ftp/src/test/java/akka/stream/alpakka/ftp/KeyFileSftpSourceTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpStageTest.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
To reduce test flakiness until we fix #365
> Ignore sftp test

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisSourceErrors.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisSourceStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardSettings.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/javadsl/KinesisSource.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSource.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/ExampleSpec.java
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/Examples.java
- kinesis/src/test/resources/application.conf
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/DefaultTestContext.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSourceSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/ShardSettingsSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/scaladsl/Examples.scala
- project/Dependencies.scala
Adds an Amazon Kinesis source per #170 that consumes a single shard, with support for consuming multiple shards via merging.
> Add AWS Kinesis Support

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
> S3: Usage test and documentation for list bucket method

- project/plugins.sbt
... as it now has credentials from environment variables support which is used by Travis.
> Back to the official sbt-bintray plugin

- docs/src/main/paradox/external-connectors.md
External connectors, the others were already OK
Refs #66
> Sort connectors alphabetically (fixes #66)

- .travis.yml
> Show mqtt logs after travis failure

- build.sbt
> Widen scalatest timeout for simple-codes

- docker-compose.yml
- docs/src/main/paradox/geode.md
- project/Dependencies.scala
> Bump geode version to 1.2.0

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
Just a quick improvement for logging of s3 upload errors.
> fix #391 adding message for FailedUploadException

- .travis.yml
> Only run whitesource if secrets are available

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
> Propsed fix for issue with ranged downloads

- docs/src/main/paradox/dynamodb.md
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/AwsClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/package.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoImplicits.scala
- dynamodb/src/test/java/akka/stream/alpakka/dynamodb/ExampleTest.java
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ExampleSpec.scala
> Dynamodb flow api improvement

- project/Dependencies.scala
Who knows maybe it'll make MqttSourceSpec (#290) more stable
> Update to paho mqtt client 1.2.0

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Allow setting a routing Key per message and resolves #364
> Add possibility of passing routing key per message

- build.sbt
Refs #491
Because it got hit on travis
> Widen scalatest future timeout

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/spring-web.md
- project/Dependencies.scala
- spring-web/src/main/java/akka/stream/alpakka/spring/web/AkkaStreamsRegistrar.java
- spring-web/src/test/java/akka/stream/alpakka/spring/web/DemoApplication.java
- spring-web/src/test/java/akka/stream/alpakka/spring/web/MyAppConfiguration.java
- spring-web/src/test/java/akka/stream/alpakka/spring/web/SampleController.java
Resolves #516
Made sure the naming makes sense.
Please sanity check things.
I did not figure out the "magically add config", which is the auto configuration things.
But if people want that they can help out I guess :)
> Add support for akka streams in spring mvc #516

- README.md
Fix the badge to scaladex, remove unnecessary text.
> Clean up badges

- .travis.yml
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSource.scala
- docker-compose.yml
- project/Dependencies.scala
To get the driver logging to see why we're getting NoHostAvailable
exceptions during the tests.
> Add logback to cassandra tests

- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSourceSpec.scala
Reverts #536 since this code is added to the docs as a snippet.
> Revert the try to fix cassandra timeout

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSourceStage.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
Hi,
Referying to https://github.com/akka/alpakka/issues/104 and e.g. https://github.com/akka/alpakka/commit/d478a6168262e070588c0c83a9111ef6f6e3f04b I'd like to propose to allow for JMS acknowledge mode configuration.
> JMS - make acknowledge mode configurable

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
> Specify request JSON encoding explicitly in Elasticsearch connector

- docs/src/main/paradox/file.md
- file/src/main/scala/akka/stream/alpakka/file/javadsl/LogRotatorSink.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- file/src/test/java/akka/stream/alpakka/file/javadsl/LogRotatorSinkTest.java
- file/src/test/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSinkSpec.scala
It's a basic logrotation type file sink. I'm still a newbie so feel free to comment/discuss my code.
> logrotation file sink

- project/build.properties
Changelog: https://developer.lightbend.com/blog/2017-10-27-sbt-1-0-3-hotfix/
> Update sbt to 1.0.3.

- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
> LogRotatorSink future handling logic reimplemented

- s3/src/main/scala/akka/stream/alpakka/s3/auth/Signer.scala
> Make Signer#sessionHeader match exhaustive

- docs/src/main/paradox/data-transformations/xml.md
- xml/src/main/scala/akka/stream/alpakka/xml/Xml.scala
- xml/src/main/scala/akka/stream/alpakka/xml/javadsl/XmlWriting.scala
- xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlWriting.scala
- xml/src/test/java/akka/stream/alpakka/xml/javadsl/XmlWritingTest.java
- xml/src/test/scala/akka/stream/alpakka/xml/scaladsl/XmlWritingTest.scala
Implementation of the serialization of the ParseEvent from xml-parser
> XML Writer #498

- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
> SQS: Add missing AttributeName

- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
It would still be good to fix this properly, let's keep tracking that in #290
> Ignore flakey test

- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/data-transformations/xml.md
- docs/src/main/paradox/dynamodb.md
- docs/src/main/paradox/elasticsearch.md
- docs/src/main/paradox/file.md
- docs/src/main/paradox/jms.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/slick.md
- docs/src/main/paradox/spring-web.md
Just noticed we got a lot of new snippets since @raboof did his find-and-replace.
> Use absolute paths for new samples

- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSink.scala
Also some quick cleaning to remove warnings.
> SNS: SQS: Bump dependencies

- docs/src/main/paradox/file.md
- file/src/main/scala/akka/stream/alpakka/file/javadsl/LogRotatorSink.scala
- file/src/test/java/akka/stream/alpakka/file/javadsl/LogRotatorSinkTest.java
- file/src/test/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSinkSpec.scala
Fixes #584 
In the end my changes were quite small, but I tried to make the Java and Scala examples very similar.
I didn't add the path generators to the API.
@tg44 Can you have a look?
> Reviewed the file rotator sink examples

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvToMap.java
> csv.javadsl.CsvToMap must be public

- build.sbt
- docker-compose.yml
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/ObservableToPublisher.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoSource.scala
- mongodb/src/test/scala/akka/stream/alpakka/mongodb/MongoSourceSpec.scala
- added mongodb module to sbt aggregate
- added Mongo to Docker compose
- reformated sources
Fixes #593
> Add MongoDb to aggregate build

- project/Dependencies.scala
- project/build.properties
Minor version upgrades to prepare for an Alpakka release.
> Current Akka, sbt, ScalaTest versions

- csv/src/main/scala/akka/stream/alpakka/csv/CsvParser.scala
- csv/src/test/java/akka/stream/alpakka/csv/javadsl/CsvParsingTest.java
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
> Make CSV exception non-private

- docs/src/main/paradox/index.md
> Add link to Alpakka's Scaladoc in index.md

- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/mongodb.md
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/DocumentUpdate.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoFlow.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoSink.scala
- mongodb/src/test/scala/akka/stream/alpakka/mongodb/MongoSinkSpec.scala
- mongodb/src/test/scala/akka/stream/alpakka/mongodb/MongoSourceSpec.scala
Based off #115 #148  from @iozozturk, which it should merge well with.
No Java DSL as this is based off of the mongo-scala-driver. A java connecter should possibly be from the mongo-java-driver.
Pending Documentation
> Add mongodb sink

- .travis.yml
- docs/src/main/paradox/index.md
- docs/src/main/paradox/patterns.md
- project/Dependencies.scala
and revise links to Akka documentation.
Fixes #624.
> Drop Akka 2.4 from Alpakka build

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoSettings.scala
- project/Dependencies.scala
More info: https://twitter.com/akkateam/status/939063569953341440
> Update Akka and Akka Streams. Will fix potential memory leak. 

- docs/src/main/paradox/mqtt.md
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/MqttCommittableMessage.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/MqttFlow.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/MqttSource.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/javadsl/package.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttCommittableMessage.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttFlow.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSink.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSource.scala
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttFlowTest.java
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttSourceTest.java
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/package.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttFlowSpec.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSinkSpec.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
- mqtt/src/test/travis/acl
Add possibility to manually ack messages downstream
Resolves #378
> MQTT manual acks

- README.md
which got lost after https://github.com/akka/alpakka/pull/648
> Bring back the gitter badge icon

- docs/src/main/paradox/slick.md
Thanks to https://github.com/lightbend/paradox/issues/166#issuecomment-351898341
> Fix link to slick fromConfig docs

- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
> Fix will message test

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
fix #139 unify s3 error handling
> fix #139 unify s3 error handling

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApiSpec.scala
Related to: https://github.com/akka/alpakka/issues/523
> Do not use auth when publishing in emulation

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Reverts akka/alpakka#638
Seems to consistently fail when it was merged onto master.
> Revert "AMQP keep connection open if there are pending acks"

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
I haven't been able to reproduce the error happening in prod but I've noticed a small difference between the Java and the Scala test and correct it. I suspect that to be the issue.
> Amqp keep connection if pending acks

- docs/src/main/paradox/index.md
Link to release notes and availablity for Scala 2.11
> More info on main page

- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttFlowTest.java
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttSourceTest.java
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
Introduce unique names for different tests / specs.
> MQTT: Make actor system names unique per spec

- docs/src/main/paradox/ftp.md
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/CommonFtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpBaseSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/KeyFileSftpSourceTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/RawKeySftpSourceTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/StrictHostCheckingSftpSourceTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpMovingExample.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpProcessAndMoveExample.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpRemovingExample.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/scalaExamples.scala
Fixes https://github.com/akka/alpakka/issues/155 and https://github.com/akka/alpakka/issues/156
> FTP: move and remove functionality as a Sink

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSink.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSinkSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSourceSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSink.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSinkSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSourceSettings.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
I tried to make the ElasticSearch connector documentation more comprehensive.
> Elasticsearch: revised documentation

- doc-examples/src/main/scala/jms/JmsSampleBase.scala
Master failed as the JMS API had changed from another PR.
> Adopt to changed JMS API

- doc-examples/src/main/scala/jms/JmsToFile.scala
- doc-examples/src/main/scala/jms/JmsToHttpGet.scala
- doc-examples/src/main/scala/jms/JmsToOneFilePerMessage.scala
- doc-examples/src/main/scala/jms/JmsToWebSocket.scala
Event Sources have a materialized value now.
> Adopt to JMS source API changes

- doc-examples/src/main/scala/ftpsamples/FtpToFile.scala
- doc-examples/src/main/scala/jms/JmsToWebSocket.scala
- doc-examples/src/main/scala/playground/FtpServerEmbedded.scala
- doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/SplitterExamples.java
A continuation of my quest against compilation warnings 🙂
> Clean up compilation warnings

- docs/src/main/paradox/index.md
- docs/src/main/paradox/other-docs.md
Blogs & presentations regarding Alpakka
> Add page with links to other documentation

- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/awslambda.md
- docs/src/main/paradox/azure-storage-queue.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/data-transformations/csv.md
- docs/src/main/paradox/data-transformations/recordio.md
- docs/src/main/paradox/data-transformations/xml.md
- docs/src/main/paradox/dynamodb.md
- docs/src/main/paradox/elasticsearch.md
- docs/src/main/paradox/file.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/geode.md
- docs/src/main/paradox/google-cloud-pub-sub.md
- docs/src/main/paradox/hbase.md
- docs/src/main/paradox/ironmq.md
- docs/src/main/paradox/jms.md
- docs/src/main/paradox/kinesis.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/mqtt.md
- docs/src/main/paradox/s3.md
- docs/src/main/paradox/slick.md
- docs/src/main/paradox/sns.md
- docs/src/main/paradox/spring-web.md
- docs/src/main/paradox/sqs.md
- docs/src/main/paradox/sse.md
- docs/src/main/paradox/unix-domain-socket.md
Fixes #609
I made sure these labels exist at Github, as well.
> Add direct links in the docs to find issues

- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisFlowSettings.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardSettings.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/Examples.java
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/scaladsl/Examples.scala
Fixes #678 
When looking to improve the Kinesis docs in regard to #678 I felt the urge to improve the Java API while at it.
> Revised Kinesis docs and improved Java API

- docs/src/main/paradox/jms.md
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsBufferedAckConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsBufferedAckConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsTxConnectorsSpec.scala
There was a lot of copy-and-paste going on to create the JMS tests...
Fixes #721
> JMS: Removed unused (and duplicate) snippet tags

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSink.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSinkTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
> Add support for send message request to sqs

- docs/src/main/paradox/dynamodb.md
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/Paginator.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/package.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoImplicits.scala
- dynamodb/src/test/java/akka/stream/alpakka/dynamodb/ExampleTest.java
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ExampleSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ItemSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TestOps.scala
Implements #443
* Paginated operations marked as AwsPagedOp
* Paginated operations return `Source`
> Paging for DynamoDB scan and query operations

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Resolves #746 and add some tests so it doesn't happen again.
What a really silly bug....
> Fix broken AQMP credential

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
Due to conflicts in https://github.com/akka/alpakka/pull/703 with https://github.com/akka/alpakka/pull/670 a new PR was made for re-usable connections in https://github.com/akka/alpakka/pull/706. This resulted in loss of some functionality in the underlying connection factory PR (https://github.com/akka/alpakka/pull/703)
This PR restores that functionality. The idea is that when a native ConnectionFactory is used, it may contain a host/port. This is ignored in the current implementation of `AmqpConnectionFactoryConnectionProvider`. As a result, setting the host/port in the underlying ConnectionFactory and using this constructor with an empty `hostAndPortList` leads to unexpected behavior (i.e. you set the host and port, but the RabbitMQ client throws an IO Exception saying "failed to …
> AMQP: use host & port from underlying connection factory

- jms/src/main/scala/akka/stream/alpakka/jms/JmsSinkStage.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/CachedConnectionFactory.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
fix jms connection leak issue since 0.16
> JMS: fix connection leak issue

- s3/src/main/scala/akka/stream/alpakka/s3/S3Exception.scala
> adding toString override to S3Exception #731

- CONTRIBUTING.md
- contributor-advice.md
- slick/src/test/resources/logback-test.xml
> Contributor advice

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/Model.scala
- google-cloud-pub-sub/src/test/java/akka/stream/alpakka/googlecloud/pubsub/ExampleUsageJava.java
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApiSpec.scala
> Added PubSubMessage attributes support for Google Cloud PubSub.

- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvToMap.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/package.scala
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/scaladsl/IronMqProducer.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoFlow.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoSink.scala
- s3/src/main/scala/akka/stream/alpakka/s3/S3Settings.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- sns/src/main/scala/akka/stream/alpakka/sns/javadsl/SnsPublisher.scala
- sns/src/main/scala/akka/stream/alpakka/sns/scaladsl/SnsPublisher.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSource.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocket.scala
Class references in brackets in Scaladoc do not use the imports, therefore a lot of those couldn't be resolved.
I came through a bit, but revising the text content could be more important...
> Fix scaladoc warnings

- s3/src/main/scala/akka/stream/alpakka/s3/impl/DiskBuffer.scala
The current DiskBuffer implementation leaks a file handle, because it
doesn't unmap the file channel (and the JVM doesn't seem to unmap it
on GC, even though it promises to do so).
This commit rewrites the DiskBuffer using ordinary streams.
Fixes #780.
> S3: Rewrite DiskBuffer using plain streams to not leak handles

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Improvements:
*  It is now possible to search without specifying typeName - Fixes #775
* you can now search in all indexes by specifying empy indexName - Fixes #774
> elasticsearch - improvements

- csv/src/main/scala/akka/stream/alpakka/csv/CsvParser.scala
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
> CSV: Require read of byte following CR before issueing line

- jms/src/test/scala/akka/stream/alpakka/jms/JmsSpec.scala
- project/build.properties
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
This PR contains format changes by scalaformat and the sbt hotfix version 1.1.1
> Sbt 1.1.1 and scalaformat changes

- doc-examples/src/main/resources/application.conf
- doc-examples/src/main/scala/elastic/FetchUsingSlickAndStreamIntoElastic.scala
- doc-examples/src/main/scala/playground/ElasticSearchEmbedded.scala
- doc-examples/src/main/scala/playground/elastic/ElasticsearchMock.scala
- docs/src/main/paradox/examples/elasticsearch-samples.md
- docs/src/main/paradox/examples/index.md
- project/Dependencies.scala
@ennru Updated with the latest from upstream.
> Add Self-contained example for Elasticsearch #788

- project/Dependencies.scala
> Bump Jackson in Elasticsearch connector to 2.9.4

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
Fixes #805 
Also, I think I've learnt that the `automaticReconnect` setting doesn't appear to re-connect, and that I must use `RestartFlow.withBackoff` and friends to reconnect - would this be correct?
> Handles failure on disconnect for MQTT

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
This PR fixes auto-reconnection and counteracts the need for #812 by avoiding the failing of the stage when we know that an automatic reconnect is planned.
The changes here are difficult to test without stopping/starting the docker container. However, I've tested locally by observing that I can stop the MQTT server and then start it again, both with and without messages pending upstream. All appears well.
All existing tests are working of course and I've engineered my changes to be quite benign without the automatic reconnection feature being enabled.
> Automatic reconnect was not working for MQTT

- docs/src/main/paradox/slick.md
- slick/src/main/scala/akka/stream/alpakka/slick/javadsl/package.scala
- slick/src/test/scala/akka/stream/alpakka/slick/scaladsl/SlickSpec.scala
> Slick: create SlickSession from DatabaseConfig instance (#833)

- doc-examples/src/main/java/elastic/FetchUsingSlickAndStreamIntoElasticInJava.java
- doc-examples/src/main/scala/elastic/FetchUsingSlickAndStreamIntoElastic.scala
- docs/src/main/paradox/examples/elasticsearch-samples.md
This adds a Java implementation of @arunma 's self-contained example.
> Examples: Add Java taste of ElasticSearch example

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/BatchException.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/package.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckSink.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsAckSinkTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
Implements https://github.com/akka/alpakka/issues/795
Tests & documentation pending
> AWS SQS: Implement batch Ack

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Fixes the second issue reported in #842
> Ensure that exceptions are always materialized in AMQP

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSinkSpec.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
Similar to what #848 does for AMQP
Might close some of the issues raised in #635
> Ensure that an exception is materialized on MQTT connection error

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceStage.scala
> Avoid to use var parameter in Elasticsearch connector

- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
Fixes compilation error after merge of #729
> AWS S3: settings changed with merge

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
This fixes a couple small bugs with the unix domain socket connector, both of which would cause its thread to crash depending upon timing.
1) `channel.read` can throw an `IOException` if the socket has subsequently been closed since the `SelectionKey` was selected.
```
Exception in thread "unix-domain-socket-io" java.io.IOException: Bad file descriptor
at jnr.enxio.channels.Common.read(Common.java:67)
at jnr.enxio.channels.AbstractNativeSocketChannel.read(AbstractNativeSocketChannel.java:62)
at jnr.unixsocket.UnixSocketChannel.read(UnixSocketChannel.java:250)
at akka.stream.alpakka.unixdomainsocket.scaladsl.UnixDomainSocket$.akka$stream$alpakka$unixdomainsocket$scaladsl$UnixDomainSocket$$nioEventLoop(UnixDomainSocket.scala:142)
at …
```
> Unix Domain Socket: fix some bugs due to races

- docs/src/main/paradox/external-connectors.md
- Added kcl-akka-stream to external connectors page
> Added kcl-akka-stream to External Connectors Page

- .travis.yml
- project/AutomaticModuleName.scala
- project/Common.scala
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
So the format check can be done by the plugin
> Use the default scalafmt plugin

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- contributor-advice.md
Reviewed the current readme and tried to integrate Alpakka Kafka connector into it.
Also showing Lightbend's commitment to taking on Alpakka.
> Readme proposal

- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
#635 reported that MQTT automatic reconnect doesn't work.
It does work, but is not documented. The trick is that it needs `cleanSession` set to true.
This PR add a test proving it.
Whenever I have some time I'd also update the documentation.
> Add MQTT automatic reconnect test

- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchFlowSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSinkSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsAckSinkTest.java
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSinkTest.java
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSinkSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
* Reviewed documentation and test cases
* Implemented Java API for settings classes
* Share Actor system between Elasticmq and Alpakka code in Java tests
Did not find the cause for test failures yet, though.
> AWS SQS: try to improve test stability

- build.sbt
- docs/src/main/paradox/index.md
- docs/src/main/paradox/other-docs/index.md
- docs/src/main/paradox/other-docs/snapshots.md
- docs/src/main/paradox/other-docs/webinars-presentations-articles.md
> Mention snapshots in the docs (#888)

- project/Whitesource.scala
- project/plugins.sbt
Using "--all" makes it possible to determine if the current commit is the tip of the master branch even in Travis which checkouts a particular sha of a commit.
@raboof I think this might work in Travis environment and does not depend on sbt-git. WDYT? :)
> Run git to describe the current git commit

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
I noticed some stuff that was wrong with the channel shutdown listeners
> Improve AQMP channels shutdown listeners

- .travis.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/kudu.md
- kudu/src/main/scala/akka/stream/alpakka/kudu/KuduTableSettings.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/internal/KuduCapabilities.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/internal/KuduFlowStage.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/javadsl/KuduTableStage.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/scaladsl/KuduTableStage.scala
- kudu/src/test/java/akka/stream/alpakka/kudu/javadsl/KuduStageTest.java
- kudu/src/test/resources/application.conf
- kudu/src/test/resources/logback-test.xml
- kudu/src/test/scala/akka/stream/alpakka/kudu/scaladsl/KuduStageSpec.scala
- project/Dependencies.scala
Apache Kudu Connector Flow and Sink. I have added few examples in docs and I have signed the Lightbend CLA.
> Apache Kudu Connector Flow and Sink

- docs/src/main/paradox/amqp.md
Documents the issue mentioned in #933
> Document AQMP versions support

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
> Use message routing key in AMQP flow if present

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSource.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApiSpec.scala
- it should not try to fetch the token from the session when running in emulated mode
- fixes [981](https://github.com/akka/alpakka/issues/981)
> [Google Cloud PubSub] Fix getting token when running in emulated mode

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
Unix Domain Socket - If writing fails, we need to fail the `sent` promise with the exception so that it can bubble up appropriately. This PR does that.
Additionally, the use of `BroadcastHub` was preventing the sink cancelling the attached `Source`, so now using `Sink.fromGraph(Flow[ByteString]...)`.
> Unix Domain Socket - fix bug causing write side closure of socket to be swallowed

- doc-examples/src/main/java/ftpsamples/FtpToFileExample.java
- doc-examples/src/main/scala/ftpsamples/FtpToFile.scala
- doc-examples/src/main/scala/playground/FtpServerEmbedded.scala
- docs/src/main/paradox/examples/ftp-samples.md
This uses not yet released paradox features: https://github.com/lightbend/paradox/pull/202
> Add Java ftp to file example

- docs/src/main/paradox/hbase.md
For newbie like me can be useful to quickly understand what library to use. Or maybe we can provide a common Alpakka page that list all the latest version of the libraries?
> Added information for dependencies to use for HBase connector

- project/Dependencies.scala
* Update mongo-scala-driver to latest version (2.3.0)
> Mongo: Update driver to 2.3.0

- ironmq/src/main/scala/akka/stream/alpakka/ironmq/IronMqClient.scala
- project/Dependencies.scala
This should resolve the `IllegalStateException: IO Listener actor terminated unexpectedly for remote endpoint`
error which was fixed in the `10.1.x` `akka-http` series
See: https://github.com/akka/akka-http/issues/1837
Re: #913 #915
> Bump `akka-http` version to `10.1.1` and `akka-http-circe` to `1.20.1` to resolve http unbind failure

- doc-examples/src/main/java/mqtt/javasamples/MqttGroupedWithin.java
- docs/src/main/paradox/examples/index.md
- docs/src/main/paradox/examples/mqtt-samples.md
- mqtt/src/test/travis/acl
- project/Dependencies.scala
A larger example exercising quite some Akka Streams features.
Missing
> WIP: MQTT samples

- docs/src/main/paradox/sns.md
- sns/src/main/scala/akka/stream/alpakka/sns/SnsPublishFlowStage.scala
- sns/src/main/scala/akka/stream/alpakka/sns/javadsl/SnsPublisher.scala
- sns/src/main/scala/akka/stream/alpakka/sns/scaladsl/SnsPublisher.scala
- sns/src/test/java/akka/stream/alpakka/sns/javadsl/Examples.java
- sns/src/test/scala/akka/stream/alpakka/sns/SnsPublishFlowSpec.scala
- sns/src/test/scala/akka/stream/alpakka/sns/scaladsl/Examples.scala
> Add support for using PublishRequest to publish messages to SNS

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
This pull request updates Elasticsearch document according to #1104.
Also this pull request contains a bugfix for Java API. I found the bug when I wrote a test for Java API to post an example in the document.
> Update Elasticsearch docs to describe incoming message types

- contributor-advice.md
- docs/src/main/paradox/reference.md
- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceFlow.scala
- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceSource.scala
- reference/src/main/scala/akka/stream/alpakka/reference/model.scala
- reference/src/main/scala/akka/stream/alpakka/reference/settings.scala
- reference/src/test/java/docs/javadsl/ReferenceTest.java
From https://github.com/akka/alpakka/pull/1039
Ignore the Java test code reformat. It seems that the new java formatter has not yet been introduced to all of the sources.
> Address reference connector feedback

- docs/src/main/paradox/hdfs.md
> HDFS: Fix wrong URL path

- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
> Make sure the stream is there for all message acks (#974)

- reference/src/main/scala/akka/stream/alpakka/reference/settings.scala
Noticed while working on other connectors.
> Add missing Java getters to reference connector

- awslambda/src/main/scala/akka/stream/alpakka/awslambda/impl/AwsLambdaFlowStage.scala
- awslambda/src/main/scala/akka/stream/alpakka/awslambda/javadsl/AwsLambdaFlow.scala
- awslambda/src/main/scala/akka/stream/alpakka/awslambda/scaladsl/AwsLambdaFlow.scala
- awslambda/src/test/java/docs/javadsl/AwsLambdaFlowTest.java
- awslambda/src/test/java/docs/javadsl/Examples.java
- awslambda/src/test/scala/docs/scaladsl/AwsLambdaFlowSpec.scala
- awslambda/src/test/scala/docs/scaladsl/Examples.scala
- docs/src/main/paradox/awslambda.md
> Move classes to the default packages for AWS Lambda connector 1.0

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvToMap.java
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvFormatter.scala
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParsingStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvToMapJavaStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvToMapStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/model.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvFormatting.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvParsing.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvToMap.scala
- csv/src/test/java/docs/javadsl/CsvFormattingTest.java
- csv/src/test/java/docs/javadsl/CsvParsingTest.java
- csv/src/test/java/docs/javadsl/CsvToMapTest.java
- csv/src/test/scala/akka/stream/alpakka/csv/CsvFormatterSpec.scala
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvFormattingSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvToMapSpec.scala
- docs/src/main/paradox/data-transformations/csv.md
> Packages for csv connector 1.0

- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/AzureQueueSourceStage.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/impl/AzureQueueSinkFunctions.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/impl/AzureQueueSourceStage.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/javadsl/AzureQueueSink.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/javadsl/AzureQueueSource.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/model.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/scaladsl/AzureQueueSink.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/scaladsl/AzureQueueSource.scala
- azure-storage-queue/src/main/scala/akka/stream/alpakka/azure/storagequeue/settings.scala
- azure-storage-queue/src/test/java/docs/javadsl/JavaDslTest.java
- azure-storage-queue/src/test/scala/docs/scaladsl/AzureQueueSpec.scala
> Packages and un-case-classes for Azure Storage Queue connector 1.0

- docs/src/main/paradox/index.md
- docs/src/main/paradox/other-docs/index.md
> Reference: add connector so navigation works

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectorSettings.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpConnectorLogic.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpReplyToSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/model.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpRpcFlow.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpSink.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/java/docs/javadsl/AmqpDocsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpGraphStageLogicConnectionShutdownSpec.scala
- amqp/src/test/scala/docs/scaladsl/AmqpDocsSpec.scala
> Refactor AMQP case classes to private classes 

- docs/src/main/paradox/unix-domain-socket.md
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
- unix-domain-socket/src/test/java/docs/javadsl/UnixDomainSocketTest.java
- unix-domain-socket/src/test/resources/logback-test.xml
- unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
* Move internal code to impl; API tests to docs
As part of #1093
> Unix Domain Socket: Become 1.0 ready

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSink.scala
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
- orientdb/src/test/scala/akka/stream/alpakka/orientdb/OrientDBSpec.scala
- slick/src/test/scala/akka/stream/alpakka/slick/scaladsl/SlickSpec.scala
- solr/src/test/scala/akka/stream/alpakka/solr/SolrSpec.scala
In this PR, I have made some changes to the Scaladoc in the ElasticSearchSink.scala and also made some name changes in the method names for the test files.
> Minor update to scaladoc and Method name changes in test files

- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
> Jms: put producers back to the pool on stream resume/restart

- docs/src/main/paradox/data-transformations/json.md
- json-streaming/src/main/scala/akka/stream/alpakka/json/impl/JsonStreamReader.scala
- json-streaming/src/main/scala/akka/stream/alpakka/json/javadsl/JsonReader.scala
- json-streaming/src/main/scala/akka/stream/alpakka/json/scaladsl/JsonReader.scala
- json-streaming/src/test/java/docs/javadsl/JsonReaderUsageTest.java
- json-streaming/src/test/scala/docs/scaladsl/JsonReaderTest.scala
> Json streaming: towards 1.0

- docs/src/main/paradox/file.md
- file/src/main/java/akka/stream/alpakka/file/impl/DirectoryChangesSource.java
- file/src/main/java/akka/stream/alpakka/file/impl/FileTailSource.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/Directory.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/DirectoryChangesSource.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/FileTailSource.java
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/DirectoryChangesSource.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/FileTailSource.scala
- file/src/test/java/docs/javadsl/DirectoryChangesSourceTest.java
- file/src/test/java/docs/javadsl/DirectoryTest.java
- file/src/test/java/docs/javadsl/FileTailSourceTest.java
- file/src/test/java/docs/javadsl/LogRotatorSinkTest.java
- file/src/test/scala/docs/scaladsl/DirectoryChangesSourceSpec.scala
- file/src/test/scala/docs/scaladsl/DirectorySpec.scala
- file/src/test/scala/docs/scaladsl/FileTailSourceSpec.scala
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
These changes are backwards-compatible.
> File: towards 1.0

- docs/src/main/paradox/slick.md
- slick/src/test/java/docs/javadsl/DocSnippetFlow.java
- slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
- slick/src/test/java/docs/javadsl/DocSnippetSink.java
- slick/src/test/java/docs/javadsl/DocSnippetSource.java
- slick/src/test/java/docs/javadsl/SlickTest.java
- slick/src/test/java/docs/javadsl/User.java
- slick/src/test/scala/docs/scaladsl/DocSnippets.scala
- slick/src/test/scala/docs/scaladsl/SlickSpec.scala
> Slick/JDBC: towards 1.0

- docs/src/main/paradox/data-transformations/recordio.md
- simple-codecs/src/main/scala/akka/stream/alpakka/recordio/impl/RecordIOFramingStage.scala
- simple-codecs/src/main/scala/akka/stream/alpakka/recordio/javadsl/RecordIOFraming.scala
- simple-codecs/src/main/scala/akka/stream/alpakka/recordio/scaladsl/RecordIOFraming.scala
- simple-codecs/src/test/java/docs/javadsl/RecordIOFramingTest.java
- simple-codecs/src/test/scala/docs/scaladsl/RecordIOFramingSpec.scala
Added Java samples as a test.
Fixes #1087
> Simple Codecs: towards 1.0

- docs/src/main/paradox/orientdb.md
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/impl/OrientDBFlowStage.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/impl/OrientDBSourceStage.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDBFlow.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDBSource.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/model.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDBFlow.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDBSource.scala
- orientdb/src/test/java/docs/javadsl/OrientDBTest.java
- orientdb/src/test/resources/application.conf
- orientdb/src/test/resources/logback-test.xml
- orientdb/src/test/scala/docs/scaladsl/OrientDBSpec.scala
This PR just moves the code to the designated packages and simplifies the code a tiny bit. There are many more things to clean up. (eg. #772)
Fixes parts of #1085
> OrientDb: towards 1.0

- docs/src/main/paradox/data-transformations/xml.md
- xml/src/main/java/akka/stream/alpakka/ParseEventMarker.java
- xml/src/main/scala/akka/stream/alpakka/xml/model.scala
- xml/src/test/java/docs/javadsl/XmlParsingTest.java
- xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
* by adding getters and an enum
* more advanced parsing example
> XML: Improve Java API

- docs/src/main/paradox/spring-web.md
- spring-web/src/test/java/docs/javadsl/DemoApplication.java
- spring-web/src/test/java/docs/javadsl/SampleController.java
> Spring-web: Move code for snippets

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApiSpec.scala
- instead of misleading `spray.json.DeserializationException: Object is missing required member 'messageIds'` return RuntimeException with the meaningful error message
> Google Cloud Pub/Sub: handle unsuccessful publish response codes

- sns/src/main/scala/akka/stream/alpakka/sns/impl/SnsPublishFlowStage.scala
- sns/src/main/scala/akka/stream/alpakka/sns/javadsl/SnsPublisher.scala
- sns/src/main/scala/akka/stream/alpakka/sns/scaladsl/SnsPublisher.scala
- sns/src/test/java/docs/javadsl/SnsPublisherTest.java
- sns/src/test/scala/akka/stream/alpakka/sns/SnsPublishMockingSpec.scala
- sns/src/test/scala/docs/scaladsl/SnsPublisherSpec.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSink.scala
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
> AWS SQS/SNS: Support for per message destinations

- sns/src/test/java/docs/javadsl/SnsPublisherTest.java
- sns/src/test/scala/akka/stream/alpakka/sns/SnsPublishMockingSpec.scala
- sns/src/test/scala/docs/scaladsl/SnsPublisherSpec.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSink.scala
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
I didn't notice that #1267 had scalafmt errors when I merged it.
> Scalafmt as it slipped through from a PR

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
> Disable AMQP automatic recovery by default

- project/Dependencies.scala
This fixes a problem with jms submodule when using coursier.
> Put jboss before maven central as central does not have the jar

- .travis.yml
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
We did not add Mqtt Streaming connector to `.travis.yml` in the original PR.
> Run mqtt-streaming tests in Travis CI

- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
This PR improves the resilience of one of the MQTT flow specs where now, only the publish event is emitted (which is the only thing we’re interested in observing).
Fixes #1295
> Improves the flow spec resilience

- dynamodb/src/test/java/docs/javadsl/ExampleTest.java
- dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
> DynamoDB: Make timeouts uniform accross tests

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Here a first try for a PR to introduce retries in case of S3 internal errors. See https://discuss.lightbend.com/t/alpakka-s3-retrying-internal-errors/2554/3
This is my first PR, so I would welcome suggestions for improvement :-)
> Add retries for S3 internal errors

- xml/src/main/java/akka/stream/alpakka/xml/ParseEventMarker.java
- xml/src/main/scala/akka/stream/alpakka/xml/model.scala
> Moving ParseEventMarker to akka.stream.alpakka.xml package

- project/Common.scala
Another mystery scaladoc appearance.
> Ignore mongodb classes from scaladoc

- project/plugins.sbt
> Depend on patched version of sbt-dependency-graph

- .travis.yml
* Use Jabba for selecting adopt OpenJDK 8
* run compile-all on Scala 2.11
> Use adopt OpenJDK 8

- ftp/src/test/java/akka/stream/alpakka/ftp/SftpSupportImpl.java
- project/Dependencies.scala
Minor API change in the Apache SSHD server used for testing.
> FTP: Upgrade dependencies

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvParsing.java
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
> CSV: Accept CR, CR, LF line-endings

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
Before this change, if downstream failed, upstream actions to invoke the
kill switch and deliver ConnectionLost would not occur.
With this change, they occur.
/cc @huntc (please confirm logic)
> mqtt-streaming: Use onComplete, not foreach

- .travis.yml
- project/PublishRsync.scala
Will merge without CI, as this is tested only on master CI builds.
> Disable strict host checking

- .travis.yml
- docker-compose.yml
- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
> AWS SQS: use ElasticMQ in Docker container instead of embedded

- docs/src/main/paradox/sse.md
- sse/src/test/java/docs/javadsl/EventSourceTest.java
- sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
* Moved snippets to `docs` packages
* Improved code layout in snippets
> SSE: towards 1.0

- build.sbt
Was publishing snapshot docs at the wrong level.
> Fix snapshot docs publish path

- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmSenderSpec.scala
- project/Dependencies.scala
Also fix tests that depended on JSON attribute ordering which changed with the new Akka Http version.
Supersedes #1406
> Upgrade Akka Http to 10.1.7

- solr/src/main/scala/akka/stream/alpakka/solr/SolrFlowStage.scala
https://doc.akka.io/docs/akka/2.5.3/scala/stream/stream-error.html
> Solr: Use akka supervision strategies on error-handling

- project/Dependencies.scala
- spring-web/src/main/java/akka/stream/alpakka/spring/web/SpringWebAkkaStreamsConfiguration.java
#1246 Removed unnecessary class injection from spring web module. 
Updated core module dependencies and removed direct dependencies from spring-webmvc and spring-webflux.
> Spring-web: support for Spring Boot 2.0 #1439

- project/Dependencies.scala
- spring-web/src/main/java/akka/stream/alpakka/spring/web/SpringWebAkkaStreamsConfiguration.java
- spring-web/src/main/java/akka/stream/alpakka/spring/web/SpringWebAkkaStreamsProperties.java
- spring-web/src/main/resources/META-INF/spring-configuration-metadata.json
- spring-web/src/test/java/docs/javadsl/SampleController.java
- spring-web/src/test/resources/application.properties
This pull request is intended to allow the ActorSystem name to be configurable.
The discussion related to this PR can be found at https://discuss.lightbend.com/t/alpakka-spring-web-support-for-setting-the-actorsystem-name/3273
> Spring Web: support for setting the ActorSystem name

- couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseFlowSpec.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSessionExamplesSpec.scala
As Travis continues to fail tests with timeouts.
> Couchbase: more test patience

- build.sbt
- docs/src/main/paradox/hdfs.md
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/HdfsFlowStage.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/strategy/DefaultRotationStrategy.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/strategy/DefaultSyncStrategy.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/strategy/Strategy.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/CompressedDataWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/DataWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/HdfsWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/SequenceWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/model.scala
- hdfs/src/test/java/docs/javadsl/HdfsReaderTest.java
- hdfs/src/test/java/docs/javadsl/HdfsWriterTest.java
- hdfs/src/test/scala/docs/scaladsl/HdfsReaderSpec.scala
- hdfs/src/test/scala/docs/scaladsl/HdfsWriterSpec.scala
* un-case classed `HdfsWritingSettings`
* moved snippet code
* Internal API marking
* pull Hadoop version to docs
> Hdfs: towards 1.0

- docs/src/main/paradox/other-docs/snapshots.md
> Docs: Technically correct snapshot info

- build.sbt
- docs/src/main/paradox/geode.md
- geode/src/main/java/akka/stream/alpakka/geode/javadsl/Geode.java
- geode/src/main/java/akka/stream/alpakka/geode/javadsl/GeodeWithPoolSubscription.java
- geode/src/main/scala-2.11/akka/stream/alpakka/geode/GeodeSettings.scala
- geode/src/main/scala-2.12/akka/stream/alpakka/geode/GeodeSettings.scala
- geode/src/main/scala/akka/stream/alpakka/geode/AkkaPdxSerializer.scala
- geode/src/main/scala/akka/stream/alpakka/geode/scaladsl/Geode.scala
- geode/src/test/java/docs/javadsl/GeodeBaseTestCase.java
- geode/src/test/java/docs/javadsl/GeodeContinuousSourceTestCase.java
- geode/src/test/java/docs/javadsl/GeodeFiniteSourceTestCase.java
- geode/src/test/java/docs/javadsl/GeodeFlowTestCase.java
- geode/src/test/java/docs/javadsl/GeodeSinkTestCase.java
- geode/src/test/scala/docs/scaladsl/GeodeContinuousSourceSpec.scala
- geode/src/test/scala/docs/scaladsl/GeodeFiniteSourceSpec.scala
- geode/src/test/scala/docs/scaladsl/GeodeFlowSpec.scala
- geode/src/test/scala/docs/scaladsl/GeodeSinkSpec.scala
- project/Dependencies.scala
* Change `ReactiveGeode` to `Geode`
* Make settings `copy` private
* Reworded documentation and made the snippets a bit more comprehensive
Fixes #1073 
cc @cheleb
> Geode: Renames and doc improvements

- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
n/a
improve JMS log messages
It is useful to include the JMS Destination name 
n/a
> JmsConnector: add JMS Destination name to log messages

- project/Dependencies.scala
Upgrade to latest Slick release.
> Slick: version 3.3.0

- project/Dependencies.scala
jms-testkit 0.2.1 is cross compiled for 2.11, 2.12, and 2.13.x
jms-testkit 0.2.1 is cross compiled for 2.11, 2.12, and 2.13.x
https://github.com/sullis/jms-testkit/issues/4
> jms-testkit 0.2.1

- project/Dependencies.scala
> Test dependencies: Play JSON 2.7.1, Specs2 4.4.1

- .travis.yml
The `~` tells jabba, to install the specified or later, if available, version.
> Always use latest JDK

- project/Dependencies.scala
Updates to the fresh of the press Alpakka Kafka 1.0-RC2.
> Update to the latest Alpakka Kafka

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvParsing.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
- project/Dependencies.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
- sse/src/main/scala/akka/stream/alpakka/sse/javadsl/EventSource.scala
Use the latest Akka release.
Type inference changes in a few places.
> Akka 2.5.21 and type inference changes

- project/Dependencies.scala
latest version of AWS SDK v2
latest version of AWS SDK v2
latest version of AWS SDK v2
n/a
> AWS SDK 2.4.14

- azure-storage-queue/src/test/java/docs/javadsl/JavaDslTest.java
- doc-examples/src/main/scala/playground/SftpServerEmbedded.scala
- file/src/test/java/docs/javadsl/DirectoryTest.java
- project/Dependencies.scala
Towards https://github.com/akka/alpakka/issues/828
Updates to the scalatest version which has support for Scala 2.13.0-M5
> Update to the latest scalatest

- project/Dependencies.scala
Fixes #xxxx
Why did you take this approach?
> scalatest 3.0.6

- project/Dependencies.scala
Fixes #xxxx
Why did you take this approach?
> AWS SDK 2.5.0

- build.sbt
- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvFormatting.java
- csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
> CSV: Adapt to Scala 2.13

- .travis.yml
- docs/src/main/paradox/release-notes/1.0-M3.md
And also mention where to track Scala 2.13 build progress.
> Split publish job across Scala versions

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Adding deleteByPrefix method which deletes all keys starting with a given prefix (similar to delete folder)
> S3: add deleteByPrefix method

- docs/release-train-issue-template.md
* sonatype repo now redirects to maven central
* added links to the API and reference docs
> Update availability section

- .scalafmt.conf
- build.sbt
- project/plugins.sbt
Latest sbt-scalafmt has improved caching which decreases formatting times substantially.
> Upgrade to the latest sbt-scalafmt

- docs/src/main/paradox/.htaccess
Refs https://github.com/akka/akka.github.com/issues/554
> Add example .htaccess file

- doc-examples/src/main/resources/logback.xml
- project/Dependencies.scala
Latest Alpakka Kafka version
Version mismatch stopped the doc-examples from running.
https://github.com/akka/alpakka-kafka/issues/736
https://gitter.im/akka/alpakka-kafka?at=5c86060fbf7990126e83a7ff
> Alpakka Kafka 1.0.1, Embedded Kafka 2.1.1

- CONTRIBUTING.md
- README.md
- docs/release-train-issue-template.md
Alpakka project has been migrated to travis-ci.com
> Change links after Travis migration

- docs/src/main/paradox/_template/projectSpecificFooter.st
Allow the docs being XML and HTML compliant.
> Hack to allow CDATA in footer

- slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
- slick/src/test/java/docs/javadsl/DocSnippetSink.java
- slick/src/test/scala/docs/scaladsl/DocSnippets.scala
Fixes a typo in word `parallelism` made in several places.
> Fix typo: parallism -> parallelism

- .travis.yml
- build.sbt
Fixes #1525 
Enable Migration Manager during CI builds so that binary-compatibility issues are discovered.
> Run MiMa on Travis

- sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala
> SQS: add MessageFactory

- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
Fixes #1588
Fixes back-pressure and memory leak issue from the SqsSource
> Fix SqsSource back-pressure and memory leak

- mqtt-streaming/src/main/mima-filters/1.0-RC1.backwards.excludes
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
> MQTT Streaming: Fix keepalive

- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/couchbase.md
- docs/src/main/paradox/ironmq.md
- docs/src/main/paradox/jms/producer.md
- docs/src/main/paradox/kinesis.md
- docs/src/main/paradox/orientdb.md
- docs/src/main/paradox/reference.md
Fix dead links on some documentation pages.
> Docs: fix more dead links

- project/Common.scala
> Add organization homepage setting

- docs/src/main/paradox/ftp.md
> Link to SshClient API

- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
Extend the timeout allowed for actor system termination to 10 seconds (via `futureValue`).
Several builds were aborted as the actor system in SQS tests didn't terminate within the given 5 seconds. 
https://travis-ci.com/akka/alpakka/jobs/189430084#L833
> SQS: allow more time for actor system termination

- project/Dependencies.scala
Fixes #xxxx
Why did you take this approach?
> AWS SDK 2.5.20

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
Mark the Alpakka SQS API as "may change" so that we can release Alpakka 1.0.0, but still find good ways to improve the API.
#1604 
https://github.com/akka/alpakka/labels/p%3Aaws-sqs
> SQS: API may change

- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
Some formatting was wrong after the latest PR merge.
> SQS: fix formatting

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/Mqtt.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
These version numbers assumed we'd do an RC2 (but were wrong even for that).
> Fix version in deprecations

- docs/src/main/paradox/mongodb.md
> Link to Akka docs lacked suffix

- project/Dependencies.scala
Fixes #xxxx
Why did you take this approach?
> akka 2.5.22

- project/Dependencies.scala
> mockito 2.27.0

- docs/src/main/paradox/hbase.md
- hbase/src/main/scala/akka/stream/alpakka/hbase/impl/HBaseSourceStage.scala
- hbase/src/main/scala/akka/stream/alpakka/hbase/javadsl/HTableStage.scala
- hbase/src/main/scala/akka/stream/alpakka/hbase/scaladsl/HTableStage.scala
- hbase/src/test/java/docs/javadsl/HBaseStageTest.java
- hbase/src/test/scala/docs/scaladsl/HBaseStageSpec.scala
This PR provides Sources to read elements from HBase database.
> HBase: add source

- project/plugins.sbt
Use Akka gRPC 0.6.1
https://github.com/akka/akka-grpc/releases/tag/v0.6.1
> Google cloud pub/sub gRPC: use Akka gRPC 0.6.1

- project/Dependencies.scala
Upgrade Alpakka Kafka to 1.0.2
> Alpakka Kafka 1.0.2

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
Changing requirements link in docs since it was for cloudtrail not for S3.
Also i've deleted a dead line in java docs.
References #1608
> S3: Broken bucket naming rules link

- project/Dependencies.scala
Upgrade doc-examples to the latest.
> Alpakka Kafka 1.0.3

- mongodb/src/test/scala/docs/scaladsl/MongoSourceSpec.scala
Add import to the documentation
People are trying to follow the docs and were not able to compile it completely. 
Example : https://stackoverflow.com/questions/56066043/not-found-value-fromregistries/56066648#56066648
> Mongo DB: Add missing imports to docs.

- doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/PassThroughExamples.java
- docs/src/main/paradox/patterns.md
Added the PassThroughFlow examples in Java
Providing support for Java developers by adding the example of PassThroughFlow in Java.
I had to implement the PassThroughFlow in java for my own project. I have successfully created it and making it open to all to use.
> PassThroughFlow examples in Java

- project/Dependencies.scala
> AWS SDK 2.5.20 -> 2.5.41

- project/Dependencies.scala
> AWS SDK 2.5.44

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/Mqtt.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
These deprecations were introduced in 1.0.1.
> MQTT streaming: correct deprecated since version

- docs/src/main/paradox/external/couchbase.md
Found this with https://github.com/lightbend/paradox/pull/317
Thanks @raboof!
> Remove external couchbase page

- project/plugins.sbt
Updates to the latest akka-grpc.
https://github.com/akka/akka-grpc/releases/tag/v0.6.2
> Google Cloud Pub/Sub gRPC: Update to the latest akka-grpc

- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionImpl.scala
> Couchbase: Propagate replicateTo setting when using CouchbaseSession.insert #1744

- project/Dependencies.scala
> AWS SDK 2.5.65

- project/Dependencies.scala
> Mockito 2.28.2

- build.sbt
Reuses settings instead of duplicating the same logic.
> Use projectInfoVersion for paths of generated docs

- project/plugins.sbt
Use sbt-dynver plugin 4.0.0 which fixes a few annoyances we've had.
> sbt dynver 4.0.0

- .github/autolabeler.yml
Fix the Google Cloud Storage directory in the autolabler configuration.
> Fix Google Cloud Storage directory

- docs/src/main/paradox/influxdb.md
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/InfluxDbReadSettings.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/InfluxDbWriteMessage.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/AlpakkaResultMapperHelper.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbFlowStage.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbSourceStage.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbFlow.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbSink.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/javadsl/InfluxDbSource.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbFlow.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbSink.scala
- influxdb/src/main/scala/akka/stream/alpakka/influxdb/scaladsl/InfluxDbSource.scala
- influxdb/src/test/java/docs/javadsl/InfluxDbCpu.java
- influxdb/src/test/java/docs/javadsl/InfluxDbTest.java
- influxdb/src/test/java/docs/javadsl/TestUtils.java
- influxdb/src/test/scala/docs/scaladsl/FlowSpec.scala
- influxdb/src/test/scala/docs/scaladsl/InfluxDbSpec.scala
- project/project-info.conf
Add a note to the docs about the early state of Alpakka InfluxDB.
* Note in the docs
* Remove compile warnings
* Dates in project-info
> InfluxDB: API may change note

- .github/autolabeler.yml
Correct the autolabeler config for the hbase label.
> Fix HBase directory for auto labeling

- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-cloud-storage.md
* improve run locally instruction in FTP
* fix link
> Minor doc fixes

- .travis.yml
Switches to JDK 11 when running nightly.
> Use JDK 11 when running nightly

- project/Dependencies.scala
> mockito 3.0.0

- project/Dependencies.scala
Updates to the just released Alpakka Kafka 1.0.5.
https://github.com/akka/alpakka-kafka/issues/853
> Update to Alpakka Kafka

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
When we get a `ConsumeFailed` exception in the `Consumer` then this is a problem that we cannot recover from.  To recap, `ConsumeFailed` is when we've received a `Publish` from a remote and we need to acknowledge it, but our calling code hasn't yet done so. The problem should cause the client to shutdown in the same way that subscription, or unsubscription does when they fail. Same for the server.
This fix should address a long-standing issue we've had on a super slow machine where `ConsumeFailed` occurs from time to time, and the stream effectively hangs because the caller wasn't made aware of the problem and couldn't restart the connection. Local testing confirms the fix should work.
The fix also replaces the use of `watchWith` with just `watch` as the former provides no means of …
> Treat ConsumeFailed as a problem

- build.sbt
Exclude the `impl` packages of all modules from Mima's checks.
It is annoying to require adding Mima exclusion files for `impl` in new versions.
> Mima: generally allow changes to the impl-package

- .github/autolabeler.yml
> Autolabeler config

- project/Dependencies.scala
> AWS SDK 2.7.18

- project/Dependencies.scala
> Solr: Upgrade to 7_7_2

- docker-compose.yml
- project/Dependencies.scala
> :arrow_up: Geode 1.9.0

- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
> File: remove unused import

- project/Dependencies.scala
Updates to the latest Akka milestone for nightly Alpakka builds.
https://discuss.lightbend.com/t/akka-2-6-0-m6-released/4857
> Update to the latest Akka milestone

- CODE_OF_CONDUCT.md
- docs/src/main/paradox/overview.md
https://www.lightbend.com/conduct
> Update to Lightbend Community Code of Conduct

- jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
> JMS: Java API for JmsMessages withProperties

- google-cloud-pub-sub/src/main/mima-filters/1.1.x.backwards.excludes
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala
- google-cloud-pub-sub/src/test/java/docs/javadsl/ExampleUsageJava.java
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/ModelSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-cloud-pub-sub/src/test/scala/docs/scaladsl/ExampleUsage.scala
Changed optionality of fields for PubSubMessage, which is now only for receiving.
Changed case classes to regular classes for not breaking compatibility
in the future.
Unit tests for model classes as now they are not generated by compiler.
References #1797
> Google Cloud Pub/Sub: PublishMessage for publishing

- project/Dependencies.scala
> Cassandra driver 3.7.1 (was 3.5.1)

- docker-compose.yml
- project/Dependencies.scala
> Geode upgrade to 1.9.1 (was 1.9.0)

- project/Dependencies.scala
Updates aalto-xml to version 1.2.2
References #1944 
aalto-xml version 1.2.2 has a thread-safety fix that is especially important when used in akka streams
> XML: update aalto-xml to version 1.2.2

- docs/src/main/paradox/other-docs/webinars-presentations-articles.md
> Docs: add some blogs and presentations

- CODE_OF_CONDUCT.md
- docs/src/main/paradox/overview.md
Backport of https://github.com/akka/alpakka/pull/1910
> [Backport] Update to Lightbend Community Code of Conduct

- jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
> [Backport] JMS: Java API for JmsMessages withProperties

- project/Dependencies.scala
Use Jackson Databind 2.9.10 (instead of 2.9.9.3)
Avoid vulnerabilities that are fixed in this patch version.
> Jackson Databind 2.9.10

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
> S3 allow max chunk size to be as large as the chunk buffer size

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoDb.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/BalancingMapAsync.scala
* Akka 2.6.0-RC1
* Akka 2.5.26
* Adapt some method names
* Copy in old Buffer factory to SQS
> Akka 2.6/2.5 cross-compilation

- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- dynamodb/src/test/java/docs/javadsl/RetryTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpWithProxyStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsWithProxyStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpWithProxyStageTest.java
- project/Dependencies.scala
Directly depend on Akka Discovery so it always uses the correct Akka version.
#1988
https://travis-ci.com/akka/alpakka/jobs/247554088#L528
* Add Akka Discovery dependency
* Recommend direct Akka Discovery dependency in the docs
* Commit formatting updates for Java files
> Google Cloud Pub/Sub gRPC: Akka Discovery

- CONTRIBUTING.md
- contributor-advice.md
Explain the use of MiMa a bit more (copied in from https://github.com/akka/akka/blob/master/CONTRIBUTING.md#binary-compatibility) now that we intend to use the directory-style.
> Docs: more MiMa docs

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/test/java/docs/javadsl/GCStorageTest.java
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
- google-cloud-storage/src/test/scala/docs/scaladsl/GCStorageSourceSpec.scala
Brings the GCS implementation in line with the documented
expected behavior for dealing with HTTP 500 responses.
This PR resolves #1931 
Ticket #1931 pointed to akka/akka#27461 as another potential resolution, but that ticket appears to have been discarded in the meantime.
* Exponential backoff is now used for waits of up to 32 seconds on 500 responses returned from GCS, as specified in the GCS SLA.
> Google Cloud Storage: Add exponential backoff on server errors

- docker-compose.yml
- project/Dependencies.scala
> :arrow_up: geode 1.11.0

- project/Dependencies.scala
> AWS SDK 2.10.47

- project/Dependencies.scala
> Make sure the correct javax.jms dependency is always fetched

- unix-domain-socket/src/test/java/docs/javadsl/UnixDomainSocketTest.java
- unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
> UnixDomainSocketTest: await domain socket binding before connecting

- project/Dependencies.scala
> AWS SDK 2.10.60

- build.sbt
- docs/src/main/paradox/mqtt-streaming.md
- docs/src/main/paradox/overview.md
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/akka/stream/alpakka/mqtt/streaming/impl/MqttFrameStageSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
- project/Dependencies.scala
Still failing one test: "MqttSessionSpec: MQTT client connector should receive a QoS 1 publication from a subscribed topic and ack it and then ack it again"
References #2097
> MQTT streaming: target Akka 2.6

- project/plugins.sbt
* Latest versions of sbt plugins
* Restructure `project/plugins.sbt` by grouping
References #2145
> Sbt plugin updates

- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
Fixed a tiny typo in `SqsSourceSettings#toString` 
I signed the CLA. :-)
> SQS:spelling of visibilityTimeout in SqsSourceSettings#toString

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
Refs #2126
More meaningfor IOResult, check whether the file is available from the
source before removing/moving
> FTP: Harden move/remove tests

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
> S3: Ensure S3Settings is resolved once per actor system

- google-cloud-storage/src/main/mima-filters/2.0.0-M3.backwards.excludes
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/Owner.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/Formats.scala
Another field that should be optional
Somehow we ended up with main.scala.akka.stream... packages
References #2163
> GCS - Owner entityId should be optional

- docs/src/main/paradox/external/mapr.md
- docs/src/main/paradox/index.md
Links to the repository for a MapR Database connector in Alpakka-style.
> Docs: Add MapR Database

- docs/src/main/paradox/mqtt-streaming.md
Add MQTT 3.1.1 version statement to the docs.
See #2137
> MQTT Streaming: protocol version

- .travis.yml
- docker-compose.yml
> Temporarily disable hbase build

- .travis.yml
- scripts/build.sh
- scripts/test-if-changed.sh
- scripts/travis.sh
> Build cleanup

- project/Dependencies.scala
> Cassandra: exclude gremlin-core from transitive deps

- unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
Assert in more detail to shed light into #1649
> Unix Domain Socket: improve test assertions

- mqtt/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
Simplify the test a bit to see if it helps with #1801 
The test used a regular Scala var to expect concurrent modification.
> MQTT: improve MqttFlowSpec

- cassandra/src/test/resources/application.conf
- docs/src/main/paradox/cassandra.md
> Cassandra: show reconnect-on-init

- docs/src/main/paradox/release-notes/2.0.x.md
I forgot to add the contributors list to the release notes.
> 2.0.0-RC1 contributors

- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSchedulerSourceSpec.scala
- testkit/src/main/scala/akka.stream.alpakka.testkit/scaladsl/Repeated.scala
Fixes (or tries to) https://github.com/akka/alpakka/issues/2219
I cannot reproduce the error locally, can you try it @seglo ?
> Fix flicker test in Kinesis KCL

- hdfs/src/test/java/docs/javadsl/HdfsWriterTest.java
- project/Dependencies.scala
Bonus: No more Apache Commons Lang!
> HDFS: use Hadoop 3.2.1

- project/Dependencies.scala
See Release notes https://docs.couchbase.com/java-sdk/2.7/sdk-release-notes.html
> Couchbase: use client 2.7.13

- hbase/src/test/scala/docs/scaladsl/HBaseStageSpec.scala
Very small PR for correcting a HBase test name
> HBase: Removed duplicated word in spec

- project/Dependencies.scala
To avoid Whitesource from seeing them twice
https://travis-ci.com/github/akka/alpakka/jobs/308315352#L358
> HDFS: remove test dependency classifier

- docker-compose.yml
- geode/src/main/scala-2.11/akka/stream/alpakka/geode/GeodeSettings.scala
- project/Dependencies.scala
> Geode 1.12.0

- project/Dependencies.scala
- project/plugins.sbt
> Google Cloud Pub/Sub gRPC: Update to Akka gRPC 0.8.3

- docs/src/main/paradox/influxdb.md
- docs/src/main/paradox/release-notes/2.0.x/kinesis.md
- docs/src/main/paradox/release-notes/2.0.x/s3.md
> Docs: official InfluxDB client

- build.sbt
> Pravega: enable MiMa

- csv/src/test/java/docs/javadsl/CsvFormattingTest.java
- scripts/travis.sh
This broke in #2192
Stage name "Test" vs "test"...
> Build: fix running tests

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/Chunker.scala
> Google Cloud Storage: emit more chunks when input is closed

- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpFlowSpec.scala
Isolates the mock for the test added in #2263 which destroys the state of the mock for other tests.
We did not notice this as #2192 broke Travis' testing, which was fixed in #2278.
References #2263
> AMQP: isolate mock

- docs/src/main/paradox/release-notes/2.0.x.md
- docs/src/main/paradox/release-notes/2.0.x/amqp.md
- docs/src/main/paradox/release-notes/2.0.x/avroparquet.md
- docs/src/main/paradox/release-notes/2.0.x/elasticsearch.md
- docs/src/main/paradox/release-notes/2.0.x/file.md
- docs/src/main/paradox/release-notes/2.0.x/google-cloud-pub-sub-grpc.md
- docs/src/main/paradox/release-notes/2.0.x/google-cloud-storage.md
- docs/src/main/paradox/release-notes/2.0.x/mqtt.md
- docs/src/main/paradox/release-notes/2.0.x/s3.md
- docs/src/main/paradox/release-notes/2.0.x/sse.md
> 2.0.0 Release notes

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/CommittableRecord.scala
> Fix typo in comment

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/ShardProcessor.scala
> Kinesis: Give the callback a more meaningful name

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSchedulerSource.scala
The broadcast aims to carry along commitable records, while at the same time, try to checkpoint based on the last record per batch. Since the checkpointing runs synchronously (told from the return type) there isn't a need to have the broadcast-then-zip pattern. Instead, simply run the try-checkpoint side effect in a map stage suffice.
> [kinesis] Get rid of unnecessary broadcast-zip

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/ShardProcessor.scala
> Kinesis: Small cleanup

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSchedulerSourceStage.scala
I would prefer avoiding `Any` if possible, but not sure if Any has any benefit that I might haven't noticed in this specific use case. To me, this is internal and should be safe to change for better type safety
> Kinesis: Avoid Any in KinesisSchedulerSourceStage

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/ShardProcessor.scala
Group override def together for better readability
> Kinesis: code layout

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
References #2305
Adds createBulk factory methods to ElasticsearchFlow
> [Elasticsearch] Add createBulk factory methods

- project/Dependencies.scala
This updates “com.github.matsluni“ % “aws-spi-akka-http“ to 0.0.9.
> Update AwsSpiAkkaHttpVersion to 0.0.9

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
Resolves #2313 
Adds logging for indexing failures
> Elasticsearch: Log indexing errors

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
References #2271 
(Already signed the Lightbend CLA)
> Elasticsearch: Support the routing parameter

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequestSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
References #2329  
That's my attempt to update the pattern of S3 URI.
> S3: URI pattern to support all regions

- .github/autolabeler.yml
- .github/release-drafter.yml
- docs/src/main/paradox/aws-event-bridge.md
- project/project-info.conf
The AWS API docs are in Javadoc.
> Docs: AWS Eventbridge link

- project/Dependencies.scala
Aligning with the version in Akka 2.6.6
> Jackson 2.10.4 (was 2.10.3)

- docker-compose.yml
- project/Dependencies.scala
> Pravega 0.7.1 (was 0.7.0)

- project/Dependencies.scala
https://github.com/akka/akka-http/issues/3290
> Akka HTTP 10.2.0-RC1 in the scheduled build

- project/plugins.sbt
- Akka Paradox (for apidoc)
- Dynver
- sbt scalafmt
> build: plugin updates

- .github/autolabeler.yml
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/impl/pagetoken/AddPageToken.scala
> BigQuery: fix compilation

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Fixes https://github.com/akka/alpakka/issues/2363
> AWS S3: Avoid uploading a empty chunk after splitting

- project/Dependencies.scala
https://doc.akka.io/docs/akka-http/10.2/release-notes/10.2.x.html
> Akka HTTP 10.2 RC2 in the scheduled build

- docs/src/main/paradox/patterns.md
https://twitter.com/ktosopl/status/1293108858571784192
> docs: Spelling

- docs/src/main/paradox/elasticsearch.md
References https://github.com/akka/alpakka/issues/2385
> Fix Elasticsearch WriteMessage.createIndexMessage documentation

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSchedulerSourceStage.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/DefaultTestContext.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSchedulerSourceSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/Valve.scala
> Kinesis KCL source backpressure

- doc-examples/src/test/scala/akka/stream/alpakka/eip/scaladsl/PassThroughExamples.scala
- project/Dependencies.scala
Tiny change for https://doc.akka.io/docs/alpakka/2.0.1/patterns.html#passthrough
> doc: Alpakka Kafka 2.0.5 in the patterns section

- build.sbt
> AWS Event Bridge: enable Mima

- project/Dependencies.scala
> Cassandra: overwrite Netty to 4.1.52

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
Use `Http().SingleRequest` for pull and acknowledge and read response as it comes back to avoid timeout on reponse entity.
References #2296
> Google Cloud Pub/Sub: use SingleRequest

- ftp/src/test/resources/application.conf
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
> FTP test: use all stages stopped timeout

- project/Dependencies.scala
Refs https://github.com/akka/akka-grpc/issues/1125
> Inherit io.grpc version from Akka gRPC

- docker-compose.yml
- pravega/src/main/scala/akka/stream/alpakka/pravega/PravegaSettings.scala
- pravega/src/main/scala/akka/stream/alpakka/pravega/impl/PravegaSource.scala
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaBaseSpec.scala
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaGraphSpec.scala
- project/Dependencies.scala
> Pravega 0.8

- .travis.yml
> Test file type of problematic hdfs dependency

- unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
> Add some diagnostics for #2437

- docs/src/main/paradox/avroparquet.md
- docs/src/main/paradox/elasticsearch.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/s3.md
- docs/src/main/paradox/slick.md
- docs/src/main/paradox/sqs.md
- docs/src/main/paradox/udp.md
Mostly grammatical fixes, but a few stylistic changes to documentation wording.
> Documentation fixes

- ftp/src/test/java/akka/stream/alpakka/ftp/FtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpWithProxyStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsWithProxyStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpWithProxyStageTest.java
>  FTP: Ignore flakey remove/move tests

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
> MQTT streaming: log the stash at clientConnect

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
> MQTT Streaming: Ignore a flaky test

- .travis.yml
- build.sbt
- project/Common.scala
- project/Dependencies.scala
> Drop support for scala 2.11

- .travis.yml
References https://github.com/akka/akka-platform-guide/pull/313, https://github.com/akka/akka-platform-guide/pull/325, https://github.com/akka/akka-platform-guide/pull/348
> CI: clean Travis caches explicitly

- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpRpcFlow.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpSource.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/AmqpSpec.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpGraphStageLogicConnectionShutdownSpec.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionImpl.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionJavaAdapter.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSession.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoDb.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GooglePubSub.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/scaladsl/IronMqConsumer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/test/scala/akka/stream/alpakka/jms/impl/SoftReferenceCacheSpec.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSourceStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSchedulerSource.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/scaladsl/KinesisFirehoseFlow.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/DiskBuffer.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/BalancingMapAsync.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocket.scala
> Akka 2.6: sameThreadExecutionContext -> parasitic

- build.sbt
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSession.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSessionRegistry.scala
- cassandra/src/test/java/docs/javadsl/CassandraFlowTest.java
- cassandra/src/test/java/docs/javadsl/CassandraSourceTest.java
- cassandra/src/test/java/docs/javadsl/CassandraTestHelper.java
We should merge #2507 first.
Refs #2466﻿
> Cassandra: use Akka 2.6

- avroparquet/src/test/java/docs/javadsl/AvroParquetSinkTest.java
- avroparquet/src/test/java/docs/javadsl/Examples.java
- build.sbt
> Akka 2.6: avroparquet

- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpFlowTest.java
- amqp/src/test/java/docs/javadsl/AmqpDocsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/AmqpSpec.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpGraphStageLogicConnectionShutdownSpec.scala
- build.sbt
> Akka 2.6: amqp

- aws-event-bridge/src/test/java/docs/javadsl/EventBridgePublisherTest.java
- aws-event-bridge/src/test/scala/akka/stream/alpakka/aws/eventbridge/DefaultTestContext.scala
- aws-event-bridge/src/test/scala/akka/stream/alpakka/aws/eventbridge/IntegrationTestContext.scala
- build.sbt
- docs/src/main/paradox/aws-event-bridge.md
> Akka 2.6: aws-event-bridge

- reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/Reference.scala
- reference/src/test/java/docs/javadsl/ReferenceTest.java
- reference/src/test/scala/docs/scaladsl/ReferenceSpec.scala
Fixes #2493 (No fatal warnings yet)﻿
> Reference: adapt to Akka 2.6

- build.sbt
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarReaderStage.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- file/src/test/java/docs/javadsl/ArchiveTest.java
- file/src/test/java/docs/javadsl/DirectoryChangesSourceTest.java
- file/src/test/java/docs/javadsl/DirectoryTest.java
- file/src/test/java/docs/javadsl/FileTailSourceTest.java
- file/src/test/java/docs/javadsl/LogRotatorSinkTest.java
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlowTest.scala
- file/src/test/scala/docs/scaladsl/ArchiveSpec.scala
- file/src/test/scala/docs/scaladsl/DirectoryChangesSourceSpec.scala
- file/src/test/scala/docs/scaladsl/DirectorySpec.scala
- file/src/test/scala/docs/scaladsl/FileTailSourceExtrasSpec.scala
- file/src/test/scala/docs/scaladsl/FileTailSourceSpec.scala
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
- file/src/test/scala/docs/scaladsl/TarArchiveSpec.scala
> File: akka 2.6.

- build.sbt
- jms/src/main/scala/akka/stream/alpakka/jms/Envelopes.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsProducerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/SourceStageLogic.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsBufferedAckConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsIbmmqConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsTxConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsProducerRetrySpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsTxConnectorsSpec.scala
> JMS: Akka 2.6 features

- build.sbt
- slick/src/test/java/docs/javadsl/DocSnippetFlow.java
- slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
- slick/src/test/java/docs/javadsl/DocSnippetSink.java
- slick/src/test/java/docs/javadsl/DocSnippetSource.java
- slick/src/test/java/docs/javadsl/SlickTest.java
- slick/src/test/resources/application.conf
- slick/src/test/scala/docs/scaladsl/DocSnippets.scala
- slick/src/test/scala/docs/scaladsl/SlickSpec.scala
> Slick: Akka 2.6 features.

- azure-storage-queue/src/test/java/docs/javadsl/JavaDslTest.java
- azure-storage-queue/src/test/scala/docs/scaladsl/AzureQueueSpec.scala
- build.sbt
> azure-storage-queue: Akka 2.6 features (#2465).

- awslambda/src/test/java/docs/javadsl/AwsLambdaFlowTest.java
- awslambda/src/test/java/docs/javadsl/Examples.java
- awslambda/src/test/scala/docs/scaladsl/AwsLambdaFlowSpec.scala
- awslambda/src/test/scala/docs/scaladsl/Examples.scala
- build.sbt
- docs/src/main/paradox/awslambda.md
> awslambda: Akka 2.6 features (#2464).

- build.sbt
- spring-web/src/main/java/akka/stream/alpakka/spring/web/AkkaStreamsRegistrar.java
- spring-web/src/main/java/akka/stream/alpakka/spring/web/SpringWebAkkaStreamsConfiguration.java
- spring-web/src/main/mima-filters/2.x.backwards.excludes/PR2526.backwards.excludes
> spring-web: Akka 2.6 features

- simple-codecs/src/test/java/docs/javadsl/RecordIOFramingTest.java
- simple-codecs/src/test/scala/docs/scaladsl/RecordIOFramingSpec.scala
> Simple Codecs: remove materializer

- json-streaming/src/test/java/docs/javadsl/JsonReaderUsageTest.java
- json-streaming/src/test/scala/docs/scaladsl/JsonReaderTest.scala
> JSON streaming: no materializer

- project/Dependencies.scala
To be on the latest version for reporting/re-creating:
https://github.com/akka/akka-persistence-cassandra/issues/816
> Upgrade cassandra driver to 4.9

- .github/workflows/link-validator.yml
- .github/workflows/release-drafter.yml
- build.sbt
- docs/src/main/paradox/elasticsearch.md
- docs/src/main/paradox/external/fs2.md
- docs/src/main/paradox/google-cloud-storage.md
- docs/src/main/paradox/hbase.md
- docs/src/main/paradox/influxdb.md
- docs/src/main/paradox/ironmq.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/orientdb.md
- docs/src/main/paradox/other-docs/webinars-presentations-articles.md
- docs/src/main/paradox/pravega.md
- docs/src/main/paradox/release-notes/1.0.x.md
- docs/src/main/paradox/release-notes/2.0.x.md
- docs/src/main/paradox/slick.md
- scripts/link-validator.conf
...and fix links that were reported to require an updated.
References https://github.com/akka/alpakka-kafka/pull/1267
> Run link validator and release drafter (as GitHub workflows)

- build.sbt
- sse/src/main/mima-filters/2.0.x.backwards.excludes/akka-2-6.excludes
- sse/src/main/scala/akka/stream/alpakka/sse/javadsl/EventSource.scala
- sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
- sse/src/test/java/docs/javadsl/EventSourceTest.java
- sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
> SSE: Akka 2.6

- build.sbt
- dynamodb/src/main/mima-filters/2.0.x.backwards.excludes/akka-2.6.excludes
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoDb.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoDb.scala
- dynamodb/src/test/java/docs/javadsl/ExampleTest.java
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ItemSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TableSpec.scala
- dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
> DynamoDb: Akka 2.6

- build.sbt
- hbase/src/test/java/docs/javadsl/HBaseStageTest.java
- hbase/src/test/scala/docs/scaladsl/HBaseStageSpec.scala
- Update HBase according to the checklist in #2481
References #2481
> Update HBase to Akka 2.6

- build.sbt
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/HdfsFlowStage.scala
- hdfs/src/test/java/docs/javadsl/HdfsReaderTest.java
- hdfs/src/test/java/docs/javadsl/HdfsWriterTest.java
- hdfs/src/test/scala/docs/scaladsl/HdfsReaderSpec.scala
- hdfs/src/test/scala/docs/scaladsl/HdfsWriterSpec.scala
- Update HDFS according to the checklist in #2482
References #2482
> Update HDFS to Akka 2.6

- build.sbt
- udp/src/test/java/docs/javadsl/UdpTest.java
- udp/src/test/scala/docs/scaladsl/UdpSpec.scala
- Update UDP according to the checklist in #2504
References #2504
> Update udp to Akka 2.6

- build.sbt
- kudu/src/main/scala/akka/stream/alpakka/kudu/scaladsl/KuduTable.scala
- kudu/src/test/java/docs/javadsl/KuduTableTest.java
- kudu/src/test/scala/docs/scaladsl/KuduTableSpec.scala
- Update Kudu according to the checklist in #2488
References #2488
> Update kudu to Akka 2.6

- build.sbt
- pravega/src/main/java/akka/stream/alpakka/pravega/javadsl/Pravega.java
- pravega/src/test/java/docs/javadsl/PravegaSettingsTestCase.java
- pravega/src/test/scala/docs/scaladsl/PravegaReadWriteDocs.scala
- project/Dependencies.scala
- Update Pravega according to the checklist in #2492 
- Update Pravega dependencies to their latest version
References #2492
> Update Pravega to Akka 2.6

- build.sbt
- mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/MqttPerf.scala
- mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttPerf.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/impl/MqttFlowStage.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/scaladsl/MqttMessageWithAck.scala
- mqtt/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt/src/test/java/docs/javadsl/MqttSourceTest.java
- mqtt/src/test/scala/docs/scaladsl/MqttSourceSpec.scala
- mqtt/src/test/scala/docs/scaladsl/MqttSpecBase.scala
- Update MQTT according to the checklist in #2490 
References #2490
> Update MQTT and MQTT streaming to Akka 2.6

- build.sbt
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/impl/IronMqPullStage.scala
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/impl/IronMqPushStage.scala
- ironmq/src/test/java/akka/stream/alpakka/ironmq/UnitTest.java
- ironmq/src/test/java/docs/javadsl/IronMqDocsTest.java
- ironmq/src/test/scala/akka/stream/alpakka/ironmq/IronMqSpec.scala
- ironmq/src/test/scala/akka/stream/alpakka/ironmq/impl/IronMqClientForTests.scala
- Update IronMQ according to the checklist in #2484
References #2484
> Update IronMQ to Akka 2.6

- build.sbt
- docs/src/main/paradox/mongodb.md
- mongodb/src/test/java/docs/javadsl/MongoSinkTest.java
- mongodb/src/test/java/docs/javadsl/MongoSourceTest.java
- mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala
- mongodb/src/test/scala/docs/scaladsl/MongoSourceSpec.scala
- Update MongoDB according to the checklist in #2490
References #2489
> Update mongodb to akka 2.6

- .github/workflows/link-validator.yml
> Remove git fetch depth limit in link validator github action

- build.sbt
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub-grpc/src/test/java/docs/javadsl/IntegrationTest.java
- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/ExampleApp.scala
- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
> Update Google Cloud Pub Sub GRPC to Akka 2.6

- build.sbt
- geode/src/test/java/docs/javadsl/GeodeBaseTestCase.java
- geode/src/test/java/docs/javadsl/GeodeContinuousSourceTestCase.java
- geode/src/test/java/docs/javadsl/GeodeFiniteSourceTestCase.java
- geode/src/test/java/docs/javadsl/GeodeFlowTestCase.java
- geode/src/test/java/docs/javadsl/GeodeSinkTestCase.java
- geode/src/test/scala/docs/scaladsl/GeodeBaseSpec.scala
> Update Geode to Akka 2.6

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
Previously it would always assume a single specific keyfile format (`OpenSSHKeyFile` a.k.a. the "old" OpenSSH keyfile format) which obviously doesn't always work. But it only did the wrong thing when no password was provided for probably historic reasons. (Downstream I'm currently working around this issue by providing a wrong password.) Now we just use [`authPublickey()`](https://github.com/akka/alpakka/blob/10c268dd3add3f4a0956877df04a7cabd7c2a98c/ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala#L213) from the other branch which does the same but correctly and in addition we can remove some duplicate code.
> FTP: Fix SFTP keyfile authentication when no password is provided

- project/Dependencies.scala
> Drop alpakka-kafka reference in docs

- docker-compose.yml
> Update pravega docker image to match client version

- docs/src/main/paradox/amqp.md
> [AMQP] Adds a note about recovery issue

- build.sbt
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSource.scala
- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
- couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
- couchbase/src/test/scala/docs/scaladsl/DiscoverySpec.scala
> Couchbase Akka 2.6

- .travis.yml
- project/Dependencies.scala
> Upgrade Akka 2.6.13 for 3.0.0-M1

- xml/src/main/scala/akka/stream/alpakka/xml/impl/StreamingXmlParser.scala
- xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlParsing.scala
- xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
Added unit test to prove issue exists and afterwords fixed it
> Fixed empty source XML parsing #2655

- .scala-steward.conf
- project/Dependencies.scala
> Upgrade jackson libs to same version as Akka

- build.sbt
- google-common/src/main/mima-filters/3.0.0-M1.backwards.excludes/2661-oauth-token-stream
> Enable MiMa for google-common

- scripts/authors.scala
I didn't have Scala 2.11 on my path and encountered several errors.
> Update authors.scala script for 2.13+

- docs/src/main/paradox/release-notes/3.0.x.md
- docs/src/main/paradox/release-notes/3.0.x/google-cloud-bigquery.md
- docs/src/main/paradox/release-notes/3.0.x/google-cloud-pub-sub.md
- docs/src/main/paradox/release-notes/3.0.x/jms.md
> 3.0.1 release notes

- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/FcmNotificationModels.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmFlows.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmJsonSupport.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/scaladsl/GoogleFcm.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/impl/FcmFlows.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/impl/FcmJsonSupport.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/impl/FcmSender.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/javadsl/GoogleFcm.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/AndroidConfig.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/ApnsConfig.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/BasicNotification.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/FcmNotification.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/FcmOption.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/FcmResponse.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/NotificationTarget.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/models/WebPushConfig.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/v1/scaladsl/GoogleFcm.scala
- google-fcm/src/test/java/docs/javadsl/FcmExamples.java
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/v1/ConditionBuilderSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/v1/FcmNotificationSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/v1/impl/FcmSenderSpec.scala
- google-fcm/src/test/scala/docs/scaladsl/FcmExamples.scala
There was added all properties for sending messages to FCM according to https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages (#2659)
> Google FCM: Add additional properties

- docker-compose.yml
- project/Dependencies.scala
> Geode 1.13.3 (was 1.13.2)

- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsMessageProducer.scala
- jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
> JMS producer should support null values for property #2690

- s3/src/main/mima-filters/3.0.4.backwards.excludes/pr-2767-add-s3-setting.excludes
- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/Signer.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/SigningKey.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SignerSpec.scala
> S3: Allow to skip signing anonymous requests

- .github/workflows/link-validator.yml
- scripts/link-validator.conf
https://github.com/ennru/site-link-validator/releases﻿
> Use Link Validator 0.2.2

- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
This trivial PR just fixes some incorrect documentation from before
> S3: Fix documentation for resumeMultipartUpload

- build.sbt
> chore: enable Mima for new connectors

- project/build.properties
To mitigate any impact of sbt's use of log4j2
> Update to sbt 1.5.6

- .github/workflows/release-drafter.yml
- project/build.properties
Use
- sbt 1.5.7
- release-drafter/release-drafter@v5﻿
> build: security updates

- google-common/src/main/scala/akka/stream/alpakka/google/auth/GoogleOAuth2.scala
The `generateJwt` method (or rather, the underlying library) might throw an exception which is unhandled and makes the streams that require authentication fail without anything logged and any way to recover.
This can be reproduced by simply changing the private key to something invalid, like adding a few extra characters, in this case a `java.security.InvalidKeyException` is thrown.
This PR aims to catch the exception and return it in the `Future` so that the downstream can properly handle it.
> google-common: Catch and return JWT errors

- project/Dependencies.scala
- project/TestChanged.scala
- scripts/link-validator.conf
Bumping some dependencies to bring security fixes in.﻿
> security bump: Akka HTTP 10.1.15; Log4j2 2.17.1 (in tests)

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
Fixes https://github.com/akka/alpakka/issues/1901
> amqp: Add default constructor for AmqpSSLConfiguration

- docker-compose.yml
- project/Dependencies.scala
> bump: Geode 1.14.1

- project/Dependencies.scala
https://github.com/akka/alpakka/issues/2799
> amqp: Use amqp-client 5.14.0 to avoid vulnerabilities

- slick/src/test/resources/application.conf
Show the DB2 solution from #2294 in the docs.﻿
> slick: DB2 hint

- project/Dependencies.scala
https://github.com/akka/alpakka-kafka/releases/tag/v3.0.0
﻿
> docs: bump Alpakka Kafka 3.0.0

- .github/workflows/publish.yml
- .travis.yml
Further strangles the need for Travis CI.
Secrets are configured in the environment and new gpg keys are created.
> Releasing from GitHub workflow

- .github/workflows/check-build-test.yml
- csv/src/test/resources/application.conf
- scripts/gh-detect-changes.sh
Avoid steps altogether if no changes are detected.
> build: check if build needed earlier

- pravega/src/main/scala/akka/stream/alpakka/pravega/PravegaSettings.scala
- pravega/src/test/java/akka/stream/alpakka/pravega/PravegaKVTableTestCase.java
- pravega/src/test/java/docs/javadsl/PravegaReadWriteDocs.java
- pravega/src/test/java/docs/javadsl/PravegaSettingsTestCase.java
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaKVTableSpec.scala
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaStreamAndTableSpec.scala
- pravega/src/test/scala/docs/scaladsl/PravegaReadWriteDocs.scala
- pravega/src/test/scala/docs/scaladsl/PravegaSettingsSpec.scala
> Pravega: Renaming builder method

- project/Dependencies.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Random updates to (mainly) testing libraries across the board.
> More recent versions of test and support libraries

- s3/src/main/mima-filters/4.0.0-M1.backwards.excludes/pr-2856-alpakka-3-deprecations.backwards.excludes
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
Removes S3 depreciation's in ready for 4.0.0 M1 milestone.
References: https://github.com/akka/alpakka/issues/2854
> Remove S3 depreciations

- docker-compose.yml
- project/Dependencies.scala
> Pravega 0.10.2 (was 0.10.1)

- file/src/main/scala/akka/stream/alpakka/file/impl/archive/ZipReaderSource.scala
- file/src/main/scala/akka/stream/alpakka/file/javadsl/Archive.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/Archive.scala
> File: Add charset parameter for archives

- docker-compose.yml
- project/Dependencies.scala
> :arrow_up: Geode 1.15.0 (was 1.14.3)

- CONTRIBUTING.md
- LICENSE
- build.sbt
https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
> Change license

- project/Dependencies.scala
* CVE-2022-22970
* CVE-2022-22950
* CVE-2022-22971
* CVE-2022-22968
> Update Spring dependency

- LICENSE
- build.sbt
* given the big dependency updates that are included
> Next relese will be 5.0.0

- .github/workflows/fossa.yml
> Fix mistake in fossa.yml

- project/Dependencies.scala
> Update Hadoop dependency to 3.3.3

- project/Dependencies.scala
Already updated to this in the Cassandra plugin https://github.com/akka/akka-persistence-cassandra/pull/984
> Update Cassandra driver to 4.14.1

- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpGraphStageLogicConnectionShutdownSpec.scala
- build.sbt
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-cloud-bigquery.md
- docs/src/main/paradox/jms/producer.md
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- influxdb/src/test/scala/docs/scaladsl/InfluxDbSourceSpec.scala
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/scaladsl/IronMqProducer.scala
- jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/KinesisTest.java
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
- pravega/src/main/scala/akka/stream/alpakka/pravega/scaladsl/Pravega.scala
- pravega/src/main/scala/akka/stream/alpakka/pravega/scaladsl/PravegaTable.scala
- project/Common.scala
- project/Dependencies.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSize.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSizeWithContext.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ExtSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- scripts/link-validator.conf
...and remove some link checking left-overs.
> bump: Scala 2.13.10 and 2.12.17; Javadoc links

- project/Dependencies.scala
- project/plugins.sbt
* Akka 2.7.0-M5
* Akka HTTP 10.4.0-M2
* Akka gRPC 2.2.0-M
> Update Akka dependencies

- docs/src/main/paradox/release-notes/5.0.x.md
- docs/src/main/paradox/release-notes/index.md
- project/Dependencies.scala
- project/plugins.sbt
* and Akka gRPC 2.2.0
* and Jackson databind 2.13.4.2
> Update to Akka 2.7.0, Akka HTTP 10.4.0

- project/plugins.sbt
References https://github.com/akka/akka-grpc/releases/tag/v2.2.1
> bump: Akka gRPC 2.2.1 (was 2.2.0) and project infra

- project/Dependencies.scala
- scripts/link-validator.conf
> chore: ignore broken API links

- project/Dependencies.scala
References https://github.com/akka/alpakka-kafka/releases/tag/v4.0.2
> bump: Alpakka Kafka 4.0.2

- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSessionPerformanceSpec.scala
- cassandra/src/test/scala/docs/javadsl/CassandraSessionSpec.scala
Popped up [here](https://github.com/akka/akka-management/pull/1134#discussion_r1172488640).
> fix: logger with proper class ref

- project/plugins.sbt
sbt-jmh 0.4.4
mima 1.1.2
Paradox Akka theme 0.47
> chore: build plugin upgrades

- project/build.properties
References https://github.com/sbt/sbt/releases/tag/v1.9.4
> bump: sbt 1.9.4 (was 1.9.1)

- project/Dependencies.scala
AMQP: Update java client to 5.18.0
References https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.18.0
> AMQP: Update java client to 5.18.0

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpDirectoryOperationsGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpGraphStageLogic.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/ComputeEngineCredentials.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/NoCredentials.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/OAuth2Credentials.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/UserAccessCredentials.scala
- google-common/src/test/scala/akka/stream/alpakka/google/auth/OAuth2CredentialsSpec.scala
- project/Dependencies.scala
- scripts/link-validator.conf
References
- https://scala-lang.org/download/2.13.12.html
> bump: Scala 2.13.12 (was 2.13.10)

- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/impl/DeprecatedCredentials.scala
- project/Dependencies.scala
- project/plugins.sbt
* Akka 2.9.0
* Akka HTTP 10.6.0
* Akka gRPC 2.4.0
> bump: Akka 2.9.0

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
> Kinesis: fix maxBytesPerSecond throttling

- project/plugins.sbt
@johanandren should be good to merge.
> Upgrade dependencies to avoid repo.scala-sbt.org

- LICENSE
> chore: License change date for 7.0.2

- .scala-steward.conf
- project/Dependencies.scala
Running once a month should be enough for Alpakka.
> Make Scala Steward less eager

- .github/workflows/check-build-test.yml
- build.sbt
- cassandra/src/test/java/docs/javadsl/CassandraTestHelper.java
- docker-compose.yml
- docs/src/main/paradox/google-cloud-bigquery-storage.md
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- project/Dependencies.scala
Not intended for merge, just want to give the tests a spin on JDK 21
> build: Verify compilation JDK 21

- README.md
- docs/src/main/paradox/other-docs/webinars-presentations-articles.md
As Alpakka doesn't publish to Maven Central anymore, the badges show old versions.
> Remove wrong version badges

- LICENSE
References https://github.com/akka/alpakka/issues/3202
> chore: License change date for 8.0.0

- .github/release.yml
Not sure, but looking at the examples they seem to have the labels in a list even when it is just a single one, so let's try that.
> build: Fix release notes config yaml

- .github/workflows/link-validator.yml
- docs/src/main/paradox/jakarta-jms/consumer.md
- docs/src/main/paradox/jakarta-jms/producer.md
- docs/src/main/paradox/jms/consumer.md
- docs/src/main/paradox/jms/producer.md
- scripts/link-validator.conf
Bump the link validator
Ignore Cassandra links (they exist but don't respond HTTP OK)
Fix some anchors
> chore: blocked Cassandra links

- .github/workflows/check-build-test.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/aws-event-bridge.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- docs/src/main/paradox/mqtt.md
- scripts/ftp-servers.sh
- scripts/link-validator.conf
Adapt `docker compose` command.
> Docker compose (without hyphen)

- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
> AWS SQS: copy delay seconds on batch request

- .github/workflows/check-build-test.yml
- docker-compose.yml
Asked here: https://github.com/iron-io/docs/issues/687
> build(ironmq): disable tests to avoid docker pull error

- project/plugins.sbt
This upgrade was missed before the release.
> bump: Akka gRPC 2.5.0 (was M1)

- LICENSE
Refs https://github.com/akka/alpakka/issues/3324
> chore: license for 9.0.1 release

- LICENSE
References https://github.com/akka/alpakka/issues/3393
> chore: License change date for 9.0.2

- project/Dependencies.scala
References https://github.com/akka/alpakka-kafka/issues/1864
> bump: alpakka-kafka to 7.0.4

- scripts/link-validator.conf
Annoying to have the link validator fail on all PRs.
> chore: link validator config
