akka/alpakka

- CONTRIBUTING.md
Funny thing is that the PR that adds a requirement that every PR must reference a ticket, does not reference a ticket.
> Remove section to PR branch naming and mention paradox

- docs/src/main/paradox/external-connectors.md
I'd like to add "iothub-react" to Alpakka, it's a component to stream messages from/to IoT devices using Microsoft Azure IoT Hub. 
Source code and documentation are available here https://github.com/Azure/toketi-iothubreact and the project is also linked here https://azure.github.io/projects/sdks . 
I tested the page rendering locally (thanks @johanandren for the instructions)
Please let me know if there's anything we can do to improve :-)
> Link to external Azure IoT Hub component - iothub-react

- project/Dependencies.scala
* development should be done with Scala 2.11 so that new
features (e.g. in library) are not accidentilly used
> use Scala 2.11 as default

- .travis.yml
- project/Publish.scala
So all of the subprojects can be released at once, and new subprojects do not need maintenance when being released the first time (like requesting new bintray package to be included into JCenter).
> Use common bintray package

- CONTRIBUTING.md
- build.sbt
- project/Publish.scala
So Lightbend Tech Hub can consume the scaladoc jar and server Alpakka Api docs.
> Publish unidoc

- .travis.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSource.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
Hi, this is the SqsSource implementation that depends only on the aws-java-sdk-sqs and no other dependencies (issue #44). 
The source does not automatically delete messages from a queue (not even configurable) because usually you will ensure that the message was successfully processed before removing it from the queue. Either way, it would be only one line to explicitly remove a message from a SQS queue.
The SqsSourceStage gets the `AmazonSQSAsyncClient` as an explicit argument and does not create its own for exact the same reason and if it would create an own one, the user had to create a second client to remove the message.
> Amazon SQS Source

- project/Dependencies.scala
- s3/src/main/scala/akka/stream/alpakka/s3/acl/CannedAcl.scala
- s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
And thanks for this awesome library!
/cc @johanandren @2m @patriknw
> Tune S3 (ACL, safe keys, object content type)

- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
In previous PR I forget to fix S3Client arguments for same consistency.
> [fix] Same order of arguments for s3 multipartUpload

- docs/src/main/paradox/external-connectors.md
Links to Scala and Java DSL of the latest Streamz release.
> Camel DSL for Akka Streams

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/dynamodb.md
- dynamodb/src/main/resources/reference.conf
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/AwsClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/ClientSettings.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoProtocol.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoSettings.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/package.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoImplicits.scala
- dynamodb/src/test/java/akka/stream/alpakka/dynamodb/ExampleJavaSpec.java
- dynamodb/src/test/resources/application.conf
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ExampleSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ItemSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/LocalDynamo.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TableSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TestOps.scala
- project/Dependencies.scala
Hello,
This is a connector for Amazon's DynamoDB associated with [#77](https://github.com/akka/alpakka/issues/77). The connector relies on the AWS Java SDK and Akka HTTP. It does not implement custom request signing or marshalling, and relies on the SDK for these facilities. This pull request only includes DynamoDB, and I can submit a separate pull request for Kinesis if this one is successful. 
There are two things to note:
- The tests rely on DynamoDBLocal which in turn relies on the native assembly for SQLite being available on the path. (This is mentioned in the documentation)
- My Kinesis implementation will depend on the same AwsClient, so it may need to be extracted to a shared location in the future?
> AWS DynamoDB Connector #77

- docker-compose.yml
- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSinkStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSource.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSinkTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSinkSettingsSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSinkSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSettingsSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
First PR for https://github.com/akka/alpakka/issues/118
Adds `SqsSink` for publishing messages in SQS
Also:
- use `StageLogging`
- factor out `DefaultTestContext` for source/sink tests
- add `Integration` tag for integration tests (the ones that require running fake-sqs/elasticmq)
- update ElasticMQ container
- update AWS Java SDK
- remove "docker pull" in .travis.yml
- add Mockito for testing (sqs project only)
- use `AmazonSQSAsync` interface instead of `AmazonSQSAsyncClient` class
TODO:
> Add SQS publish sink

- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/S3Settings.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/resources/application.conf
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3NoMock.scala
Fixes https://github.com/akka/alpakka/issues/137
> Provide S3 AWS credentials from application.conf

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
S3 will respond to requests with a redirect to the region specific URI if the bucket has been created recently. Using the region-specific URI prevents a failure in such case
> update s3 multipart uploads to use region-specific uri (resolves #142)

- ftp/src/test/java/akka/stream/alpakka/ftp/FtpBaseSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpSupport.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpSourceSpec.scala
This PR clarifies the use of the `binary` attribute, as opposed to `ascii` or `text` mode, on both `FTP` and `FTPs` configurations. Please, take into account that this doesn't apply to the `SFTP` configuration. As of @rafacm 's  contribution, the test suite has been improved to better show the use of `binary` mode.
> FTP: Improve testing on binary bigger files (closes #154)

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpSourceSpec.scala
* Change `fillBuffer` to ensure that `buffer`
head has a file (as opposed to file or dir).
* Clean up pattern matching on Vector.
> Fix FTP#list to recurse through sparse dirs, #165

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
Add a quick fix for the US standard zone
#175 - #171
> S3 - Add case handling for Us Standard zone

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
Current (".") and parent ("..") directories are returned as part of the list, which causes `FtpBrowserGraphStage` (https://github.com/akka/alpakka/blob/master/ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala#L67) to infinitely try to call `listFiles()` again on these directories.
`SftpOperations.scala` has this filter (https://github.com/akka/alpakka/blob/master/ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala#L47) but it's missing in `FtpOperations.scala`
> [FTP] Critical fix for infinite loop of traversing "." and ".." directories

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsSource.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSettingsSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
Fixes #135 
The solution to the issue, as proposed by @aserrallerios was to create a custom `AmazonSQSAsyncClient` with a thread pool which is limited to `maxBufferSize / maxBatchSize` threads. To make sure the maxBufferSize is not exceeded, I keep track of the number of current requests and only allow new requests if `maxBatchSize` elements would fit into the buffer for another request.
To further optimize AWS resource usage, as soon as there is a request which returns 0 messages, I assume that the queue is empty and limit the number of concurrent requests to 1. This makes sure that there will be only one request long polling for new messages.
> Limit parallelism for the SqsSource

- docs/src/main/paradox/ftp.md
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpGraphStageLogic.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/CommonFtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpBaseSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpSupportImpl.java
- ftp/src/test/java/org/apache/ftpserver/filesystem/jimfs/impl/JimfsFtpFile.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
> FTP - toPath sink #182

- docs/src/main/paradox/index.md
Now people don't notice Kafka is in here since it's "external", expanding the TOC one more level makes it more visible.
WDYT?
> Make external libs more visible (reactive kafka)

- docker-compose.yml
- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckSinkStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckSink.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/package.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckSink.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsAckSinkTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckSinkSettingsSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
Second PR for #118 
Example flows. We can acknowledge messages after processing:
```scala
SqsSource(queue)
.map { m: Message => (m, Ack()) }
.to(SqsAckSink(queue))
```
or put messages back in the queue, for later processing:
```scala
SqsSource(queue)
.map { m: Message => (m, RequeueWithDelay(5)) }
.to(SqsAckSink(queue))
```
> Add SqsAckSink

- awslambda/src/test/scala/akka/stream/alpakka/awslambda/scaladsl/AwsLambdaFlowSpec.scala
When an assertion fails after the test has already succeeded it will be
ignored, so Await the future before continuing with the check.
> Await futures before performing assertion (fixes #235)

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
> Added support for partial file download from S3 #264

- build.sbt
- docs/src/main/paradox/index.md
By passing versions to Paradox properties correct versions and links can be created in md files.
(Just as I did for [Akka Stream Kafka](http://doc.akka.io/docs/akka-stream-kafka/current/home.html).)
> Add version info and links on index page

- docs/src/main/paradox/file.md
- file/src/main/java/akka/stream/alpakka/file/javadsl/Directory.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/DirectoryChangesSource.java
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/Directory.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/DirectoryChangesSource.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/FileTailSource.scala
- file/src/test/java/akka/stream/alpakka/file/javadsl/DirectoryTest.java
- file/src/test/scala/akka/stream/alpakka/file/scaladsl/DirectorySpec.scala
- file/src/test/scala/akka/stream/alpakka/file/scaladsl/FileTailSourceSpec.scala
Refs  #272
Adds `Directory.ls` and `Directory.walk` to stream file paths from the filesystem.
> Directory sources

- project/Dependencies.scala
- sse/src/main/scala/akka/stream/alpakka/sse/javadsl/EventSource.scala
- sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
- sse/src/test/scala/akka/stream/alpakka/sse/scaladsl/EventSourceSpec.scala
This is an important fix for the SSE connector, because in Akka SSE 2 heartbeats, which are used by this connector as framing delimiter, aren't ignored during unmarshalling.
> sse: Upgrade to Akka SSE 3 and make test more robust

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/S3Settings.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ClientIntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
In my opinion an S3 client should be configured for a region via the config file.
> Remove duplicated region argument in client methods

- project/Dependencies.scala
So older version is not evicted.
Fixes #310
> #310 exclude newer Akka dependency

- build.sbt
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApiSpec.scala
Works whether the `PUBSUB_EMULATOR_HOST` variable is defined as a property or as environment variable.
Refs: #286
> PubSub: Add support for emulator host variables

- csv/src/main/scala/akka/stream/alpakka/csv/CsvParsingStage.scala
- csv/src/test/scala/akka/stream/alpakka/csv/scaladsl/CsvParsingSpec.scala
As @kciesielski described in #315 he encountered a bug which sometimes swallowed CSV
lines.
The issue occurs on stream completion when more than on CSV line is not parsed yet and the
last line has no line ending.
I haven't been able to re-create the issue in a proper test case as it is connected to
stream execution timings.
> CSV: Emit all lines on completion

- project/Dependencies.scala
https://github.com/akka/alpakka/issues/309
Looks like the projects in ´build.sbt´ are already ordered, and the dependencies are obviously in an ´Object´, so all that's left of this issue is to order the projects ´Dependencies.scala´
> Alphabetically order dependencies

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
If an error happened in preStart, the future wouldn't be completed and anyone mapping on the result would just hang on that future.
> Fix #343 by handling preStart failures explicitly

- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSinkStage.scala
Fixes  #350 
* Adds timeToLive (Duration) to JmsSinkSettings
* Sets timeToLive on the jmsProducer
> Add Setting to configure TimeToLive for the JmsProducer in JmsSink

- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
Is it ok to use `java.time.Instant` (JDK 8)?
This is a breaking change as the return type for listing changes, is that ok? If not what is the proposed solution?
Can the java and scala api's share a case class? Currently I just copied the case class and added a map to convert
> fix #347 return more info when listing bucket

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
I thought it better to just fail than to redirect and log a warning indicating a performance issue
> fix #312 don't accept s3 redirect responses as success

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
Whether you are using a proxy or not, the host header should always be the proper amazon URL. When you are using a proxy, you want the URI to include your proxy host.
> S3: Bug fix around host header when using Proxy

- .travis.yml
Seems to work, and IIRC the 'non-sudo' builds are more lightweight?
> Check if sudo is still required for travis

- s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala
- s3/src/test/scala/akka/stream/alpakka/s3/auth/CanonicalRequestSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/auth/SignerSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala
fix #374 correctly encodes non-ascii characters for signing s3 requests
> fix #374 correctly encodes non-ascii characters for signing s3 requests

- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/ExampleSpec.java
See #390 - let's see if this is the only test that triggers this deadlock.
> Ignore test that deadlocks the build

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
This pull request fixes the problem detailed in #380. There are two issues addressed:
* IOExceptions thrown by the ftp client during onPush were not being handled, the interpreter handles the exception and calls postStop on the graph stage, which by default completes the IOResult promise with a success. This is fixed by intercepting the the exception in onPush and failing the promise with the exception. 
* postStop was throwing an additional exception, in the case of a failure in onPush, as by default it closes the OutputStream which is in a failed state. This seems unnecessary, so this change fixes that by cleaning up the IOStream in the exception handling in onPush.
> fix #380 handling IOExceptions in FTP sink onPush

- build.sbt
Makes it harder to search for `***` to find test failures
> Don't use `***` in the sbt header

- build.sbt
Not sure if those projects will still interfere with each other though. We'll
see. We might have to fork... or make sure this deadlock gets fixed upstream.
Refs #390
> Disable parallel testing for projects that use mockito

- docs/src/main/paradox/sqs.md
- project/Dependencies.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckSinkSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsAckSinkTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/ChangeMessageVisibilitySpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
- Fixes https://github.com/akka/alpakka/issues/257 - change message visibility instead of requeueing
- **BREAKING** changed `Ack` to `Delete` and `RequeueWithDelay` to `ChangeMessageVisibility` - using SQS actions names
- Added `Ignore` to ignore messages and let them reappear in the queue after visibility timeoue
- updated dependencies
- updated documentation
TODO
> AWS-SQS: Use ChangeMessageVisibility instead of RequeueWithDelay

- project/plugins.sbt
To consider non-tagged builds on master 'isSnapshot'
(https://github.com/dwijnand/sbt-dynver/pull/42), which
makes the whitesource project name make more sense.
> Update dynver plugin

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsStageTest.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
This is a proposal to make the model of the FTP component more homogeneous. It remains to be decided if we want to replicate in `FTP` and` FTPs` the [fluent API](https://github.com/akka/alpakka/blob/master/ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala#L116) that has been defined in `sFTP`, especially for Java use. Feedback is appreciated.
Closes #395
> FTP Homogenize model

- s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala
- s3/src/test/scala/akka/stream/alpakka/s3/auth/CanonicalRequestSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala
fix #404 S3 correct encoding for path containing colon
> fix #404 S3 correct encoding for path containing colon

- build.sbt
- docs/src/main/paradox/ftp.md
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpBaseSupport.java
- project/Dependencies.scala
This PR improves testing stability on FTP connector. The key change has been to add a new jvm configuration parameter that enables a less strict random generator device on Travis Linux VMs. The previous one would hang the main process if the machine is not able to generate enough entropy. Aditionally, some test dependencies have been updated.
/cc @raboof 
#422
> FTP testing stability

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/AwsClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoClient.scala
`DynamoClientImpl` accepts an `ActorMaterializer` when it could use the more specific type of `Materializer` (see: https://github.com/akka/alpakka/blob/master/dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala#L20).
Other clients, such as the s3 client use a `Materializer` instead (see: https://github.com/akka/alpakka/blob/master/s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala#L48).
See: #437
> Change DynamoClient to accept Materializer instead of ActorMaterializer

- docs/src/main/paradox/ftp.md
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpRetrievingExample.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpSettingsExample.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpTraversingExample.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpWritingExample.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/scalaExamples.scala
Documentation improved by adding imports on examples.
closes #396
> FTP: include imports in examples

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/DocSnippets.java
- s3/src/test/resources/application.conf
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/DocSnippets.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala
- Added an accepted content type to the unmarshaller of the inital response to a
mutlipart upload.
- Updated the documentation with COS specific information.
- Rewrote the integration test in S3NoMock.scala
https://github.com/akka/alpakka/issues/464
> Support for ibm cloud object storage

- .travis.yml
- build.sbt
- project/TestChanged.scala
Inspired by https://github.com/akka/akka/blob/master/project/ValidatePullRequest.scala
Kept it a bit simpler for now, ignoring dependencies between projects
> Build only changed subprojects

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/slick.md
- project/Dependencies.scala
- slick/src/main/scala/akka/stream/alpakka/slick/javadsl/Slick.scala
- slick/src/main/scala/akka/stream/alpakka/slick/javadsl/package.scala
- slick/src/main/scala/akka/stream/alpakka/slick/scaladsl/Slick.scala
- slick/src/main/scala/akka/stream/alpakka/slick/scaladsl/package.scala
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/DocSnippetFlow.java
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/DocSnippetSink.java
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/DocSnippetSource.java
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/SlickTest.java
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/User.java
- slick/src/test/resources/application.conf
- slick/src/test/resources/logback.xml
- slick/src/test/scala/akka/stream/alpakka/slick/scaladsl/DocSnippets.scala
- slick/src/test/scala/akka/stream/alpakka/slick/scaladsl/SlickSpec.scala
This adds support for a new "slick" connector, which uses the Slick library to enable interaction with all major (and quite a few minor) relational databases.
Since Slick is Scala only, the Java DSL is a little less powerful and required a few thin wrappers.
This PR contains contributions by @rayroestenburg.
> Support for relational databases (JDBC) through Slick

- docs/src/main/paradox/jms.md
The examples cannot be done in snippets since the ibm mq client jar is not publicly available trough maven / ivy repo.
> Added docs for using IBM MQ.

- build.sbt
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Disables parallel test because [elasticsearch-cluster-runner](https://github.com/codelibs/elasticsearch-cluster-runner) which is used to run Elasticsearch for test doesn't support parallel execution on same JVM formally.
Fixes #479.
> Fix timing issue in Elasticsearch tests

- project/Dependencies.scala
- project/build.properties
Not needed anymore when used with coursier 1.0.0-RC12 after https://github.com/coursier/coursier/issues/636 and https://github.com/coursier/coursier/issues/200 have been fixed.
> Remove coursier workaround

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/AmqpRpcFlow.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/AmqpSource.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/CommittableIncomingMessage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/package.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/model.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpRpcFlow.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpSource.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/CommittableIncomingMessage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/package.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/AmqpSpec.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
- docs/src/main/paradox/amqp.md
Fix #97 by adding the possibility of deactivate `autoAck` and allowing to `ack` or `nack` messages downstream.
Nack allow to optionally requeue the message or not (by default it does).
I've noticed that #292 was doing the same but it seems stale and the work seems bloated to me (it introduce a lot of duplicities and unrelated changes).
This PR introduce a very minimal change.
No breaking changes at API level.
Fully tested.
Only "breaking" change is that `IncomingMessage` becomes a trait and `AckedIncomingMessage` and `UnackedIncomingMessage` are case classes extending it. (I'm any case I don't think that anyone should be using `IncomingMessage` so this shouldn't even be a real breaking change)
The advantage of having `AckedIncomingMessage` and `UnackedIncomingMessage` as case classes …
> Allow message ack downstream

- geode/src/main/scala/akka/stream/alpakka/geode/internal/stage/GeodeCQueryGraphLogic.scala
- geode/src/main/scala/akka/stream/alpakka/geode/internal/stage/GeodeContinuousSourceStage.scala
Fixes https://github.com/akka/alpakka/issues/484
If incoming queue is not empty, new elements are queue rather than flowed downstream
> BugFix order of outgoing message #484

- dynamodb/src/main/resources/reference.conf
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/AwsClient.scala
- dynamodb/src/test/resources/application.conf
Current implementation uses the DefaultAWSCredentialsProviderChain which provides support for obtaining the credentials from the instance. 
When the headers are added on the http request the  "X-Amz-Security-Token" is ommited but it is required.
Small DRY of the host address and update for the documentation for the port settings.
Tested in AWS. Any suggestion how to test it locally welcome.
See #276
> [DDB] Support for AWS Session Credentials - Using the Token  session auth

- docs/src/main/paradox/amqp.md
Just noticed that the AMQP docs are broken at https://developer.lightbend.com/docs/alpakka/current/amqp.html
My bad from my previous PR. Here is the fix (hopefully :) ).
> Fix broken amqp docs

- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Since Elasticsearch 5.x, content type auto detection has been deprecated. So current tests cause warnings like following during execution:
```
[299 Elasticsearch-5.6.0-781a835 "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "F, 29 Sep 2017 12:02:34 GMT"]
```
This pull request adds Content-Type header to some requests in test cases to prevent this warnings.
> Fix warnings occured during  Elasticsearch test execution

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
Throw error if the s3 bucket name contains non-LDH characters #511
* Added a regex to validate the bucket name when the path-style-access is false
> Throw error if the s3 bucket name contains non-LDH characters #511

- build.sbt
- project/Common.scala
The javadoc tool returned an error (and failed the build) for me because of the
-Xlint:unchecked option which is passed to javadoc but not
recognized there.
> Remove javac options that confuse javadoc

- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSourceSpec.scala
Default was [5 seconds](http://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/SocketOptions.html#DEFAULT_CONNECT_TIMEOUT_MILLIS).
> #527 Increase connection to Cassandra timeout

- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSourceSpec.scala
Cassandra does not handle the dropping/creating of a keyspcae with the
same name very well. This can lead to errors coming back and the driver
then refusing to hand out connections for that host.
> Make test cassandra keyspace name dynamic

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
AWS SDK credential provider supports token expiration, so the code needs to reflect that.
I was not sure how to go about scope of `def`: we can just make `akka.stream.alpakka.s3.auth.SigningKey#credentials` a `def` and leave `SigningKey` a `val`, but the key also depends on a current date. I'm not an expert in the field of security algorithms and to the extent of my understanding it it safer to recalculate the the key completely.
A better solution would be to try and use the signing mechanism provided by the AWS SDK, but I decided to keep the scope of changes smaller.
> S3: Make SigningKey non-constant to reflect possible token changes

- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
Timeout: from 1.5x to 2x to avoid failures due to natural async latencies.
> Fix Kinesis publisher test

- docker-compose.yml
- geode/scripts/geode.sh
- project/Dependencies.scala
Docker startup script fixed: geode data location were overlaping with geode (new) installation layout.
> Bump geode version to 1.3.0

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvParsing.java
- csv/src/main/scala/akka/stream/alpakka/csv/CsvParser.scala
- csv/src/main/scala/akka/stream/alpakka/csv/CsvParsingStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvFormatting.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvParsing.scala
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- csv/src/test/scala/akka/stream/alpakka/csv/scaladsl/CsvFormattingSpec.scala
- csv/src/test/scala/akka/stream/alpakka/csv/scaladsl/CsvParsingSpec.scala
Introduce `maximumLineLength` in CSV parsing so that the parser fails when
no line break is encountered for a reasonably long line (defaults to 10 kB).
Fixes #509
> CSV: Fail parsing for too long lines

- build.sbt
- docs/src/main/paradox/data-transformations/csv.md
- docs/src/main/paradox/data-transformations/recordio.md
- docs/src/main/paradox/data-transformations/xml.md
- docs/src/main/paradox/file.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/jms.md
More Paradox directives in the documentation: 
* `@scala`, `@java` to show text depending on the language selected
* `@github` for links to the Github repo
* `@javadoc` (with config in build.sbt) will find the best URL depending on the package name
Took CSV docs to start with. 
JMS docs had a couple of broken links.
> Doc links to GitHub & Javadoc

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApiSpec.scala
* remove 'apikey' param from HTTP request URL for GCP Pub/Sub publish request.
> fix GCP pub/sub auth issue - remore redundant apikey param

- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsAckSinkSettings.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/SqsAckSinkTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/ChangeMessageVisibilitySpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/MessageAttributeNameSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
Fix #574.
Note that this is not backward compatible. It will break Java and ~~Scala~~ sources that use the `Ack` feature of SQS.
Edit: Only the Java sources are broken with the new PR.
> SQS: More idiomatic MessageAction

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoProtocol.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoClient.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoImplicits.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TableSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TestOps.scala
Add DynamoDB support for operations:
* DescribeTimeToLive
* UpdateTimeToLive
Unfortunately cannot be tested locally as DynamoDB Local does not
support these operations.
> Add DynamoDB TTL support #603

- .gitignore
Closes #284  
Mosquette was actually removed on long time ago (https://github.com/akka/alpakka/commit/67be7aeddbdb50d4d5858d3466e39a149bb568e4)
So the files can be removed from .gitignore and the issue can be closed.
> Remove mosquette from .gitignore

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSinkStage.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
Add support for attributes timeToLive, priority and deliveryMode per message in JmsSinkStage.
Resolves #441
> JMS: Support message individual timeToLive during send (#441)

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/unix-domain-socket.md
- project/Dependencies.scala
- unix-domain-socket/src/main/resources/reference.conf
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocket.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
- unix-domain-socket/src/test/java/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocketTest.java
- unix-domain-socket/src/test/resources/application.conf
- unix-domain-socket/src/test/resources/logback-test.xml
- unix-domain-socket/src/test/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocketSpec.scala
Provides Java and Scala DSLs along with documentation for both.
The `UnixDomainSocket` class is modelled directly from its `Tcp` counterpart. Note that, for no particular reason, I've not included support for `idleTimeout` on binding and connecting. This should be trivial. I just ran out of time.
*NOTE* The PR will require squashing given that commits pertain to PR feedback.
Fixes #620
> Provides Unix Domain Socket support

- s3/src/main/resources/reference.conf
Fixes inconsistency mentioned in #580
> S3: sets default credentials provider to default

- hbase/src/test/scala/akka/stream/alpakka/hbase/scaladsl/HBaseStageSpec.scala
I think that example should look like that because it is self-explanatory. It does not suggest that `Put` has constructor that operates on `String` argument.
> HBase example refinement

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSink.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSink.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
This a replacement-PR for https://github.com/akka/alpakka/pull/586.
This PR changes the original ElasticsearchFlowStage-implementation and adds the "returns info about both success and failed messages"-functionality to it.
The original ElasticsearchFlowStage-implementation only returns info about failed messages.
This makes it impossible to pass "info" through the elastic-flow.
Example of such info might be a Kafka-offset that should be committed AFTER the message has been written to elastic.
The fix in this PR makes this possible.
> ElasticsearchFlow now returns info about both success and failed messages - with optional cargo

- project/Dependencies.scala
Just a bit of housekeeping.
Bugs have been fixed and performance improved.
Only breaking change is that auto-recovery was disabled by default and now it's enable by default. I can make it disable by default but I think that makes sense to go along with the underlying library (thoughts??)
Also, since version 4.0, allows using Java IO which should reduce the number of threads. I've tried it and all the test pass just fine (and seem faster but I can't say without proper measurements). so my question is:
a) Should it be enabled it by default?
b) Should we expose all the settings for NIO as rabbitmq client library does?
I haven't include the NIO change because it would conflict with #506 and I'd rather to get that done first and then introduce NIO.
As I side note, I think that it would be good …
> Update AMQP client version to the latest

- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/S3Settings.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/DocSnippets.java
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/AwsS3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/DocSnippets.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
Suggestion to continue with the approach used in https://github.com/akka/alpakka/pull/440 to use default AWS resolver for `region` as well.
Potentially simplifies configuration of an application when using AWS.
> S3: use default region provider

- docs/src/main/paradox/mqtt.md
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttSourceTest.java
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSinkSpec.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
Closes #337
Allow setting QoS and retained flag per message.
Deprecate the old Will message since the new message already contains the necessary data.
Bring back the will test since I can't see why it was ignored.
No breaking changes in the existing APIs.
> [MQTT] Allow setting QoS & retained per message

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
This removes the MqttConnectorLogic and put it's logic into the stage.
This PR doesn't change functionality but simplifies the MQTT connector and makes it easier to reason about it.
It also removes the need of using var for the connection in the stage and makes it inmutable.
> Move MQTT connector logic into the stage

- .travis.yml
- docker-compose.yml
- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/dynamodb.md
- docs/src/main/paradox/geode.md
- docs/src/main/paradox/ironmq.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/mqtt.md
Closes #75
* Add the same info to all docs.
* Replac the raw call to docker to a call to docker-compose, since the containers are already configured there.
* Fix the travis config to show all the docker logs instead of only some of the containers.
> Consolidate documentation about docker images required for tests

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
I found some issues with the way the unacknowledged messages are tracked in the AMQP connector.
I also move around a couple things so it's easier to compare the SourceStage and the FlowStage to ensure that both use the same logic. In the future it might make sense to merge them in one stage (as the MQTT connector).
> AMQP keep connection open if there are pending acks

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Headers.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Request.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3HeadersSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
fix #654 S3 support server side encryption - customer keys (SSE-C)
> AWS S3: Support for customer key server side encryption

- s3/src/main/scala/akka/stream/alpakka/s3/auth/Signer.scala
- s3/src/test/scala/akka/stream/alpakka/s3/auth/SignerSpec.scala
"YYYY" in `DateTimeFormatter.ofPattern("YYYYMMdd")` means
week-based-year, which formats `LocalDate.of(2017, 12, 31)` as
"20181231" and results in unexpected rejections from S3 as below:
> The difference between the request time and the current time is too large.
Replacing it with "yyyy" fixes the bug.
> S3: Format x-amz-date with year-of-era

- jms/src/main/scala/akka/stream/alpakka/jms/JmsSinkStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsSink.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsSink.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
Sometimes it's useful to know when the stream has completed. Materializing `JmsSink` to a `Future` makes this easier.
> Make JmsSink materialize to Future[Done]

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/model.scala
- project/Dependencies.scala
This PR adds a new AmqpConnectionSettings type that accepts a native `ConnectionFactory` from the underlying RabbitMQ client.
The motivation is that I needed to give an SSL truststore with an imported mutual certificate. This required me to inject a `SocketFactory` with that truststore directly into the AMQP `ConnectionFactory`. This isn't supported by the `AmqpConnectionDetails` class. I thought it might be useful in some more complex use cases (like this one) to give the underlying `ConnectionFactory` directly to the Alpakka AMQP graphstage, so you can use the more advanced features of the Java RabbitMQ client.
The new settings type (`AmqpConnectionFactory`) can be constructed with a single `ConnectionFactory`. I maintained support for multiple host/port combinations with an extra …
> AMQP: add support for native ConnectionFactory as a configuration option

- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/S3Settings.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/DocSnippets.java
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/DocSnippets.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
Rebased #619 against latest master.
> Support custom s3 api endpoints

- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectionProvidersTest.java
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
- docs/src/main/paradox/amqp.md
Fix a couple issues that I found on the amqp docs:
* List of providers not showing as a list
* Link to Amqp ConnectionFactory is broken
Also refactor a bit the example so they look as similar as possible between java and scala.
Unfortunately I can't test that since running `sbt docs/local:paradox` on master always result on:
```
[error] java.net.URISyntaxException: Illegal character in path at index 36: /.../alpakka/docs/src/main/paradox
[error] 	at java.net.URI$Parser.fail(URI.java:2848)
[error] 	at java.net.URI$Parser.checkChars(URI.java:3021)
[error] 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
[error] 	at java.net.URI$Parser.parse(URI.java:3063)
[error] 	at java.net.URI.<init>(URI.java:588)
[error] 	at com.lightbend.paradox.markdown.Path$.relativeLocalPath(Page.scala:221) …
```
> Fix amqp docs

- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSourceStage.scala
When `javax.jms.ConnectionFactory#createConnection()` throws an exception (e.g. failed to connect), we are left with a null connection and throw a NPE when closing the stage.
> jms: fix NPE when connection failed to initialize

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSinkSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSourceSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSinkSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSourceSettings.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
This PR contains multiple improvements to the elasticsearch-connector:
- Added support for **optimistic locking/concurrency control** (https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html)
- The flow now **guaranties** that message-results are returned in the **same order** as input.
- Changed the **default** value of the setting **retryPartialFailure to false**. (If retryPartialFailure is true, failed messages will retry, but succeeded messages will be emitted downstream. This breaks the order of messages. Also: I cannot see a situation where single failed documents in a bulk update  can start succeeding when retrying)
- source now supports **custom ObjectMapper**
- **Improved Jackson json code** in java source.
(Please see individual commits)
> Elasticsearch: enable optimistic locking/concurrency controll (and more)

- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
The Java test added to validate #748 used an extra server address which is not available. That's why it failed with the wrong exception type.
> Amqp: remove non-existing port from credentials test in Java

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
independent from stream materialization ( #740)
* download method in s3 client now returns a tuple with stream and metadata
* stream from download now materializes into NotUsed
> Make s3 object metadata available on downloads

- build.sbt
- docker-compose.yml
- docs/src/main/paradox/orientdb.md
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/OrientDBFlowStage.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/OrientDBSourceSettings.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/OrientDBSourceStage.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/OrientDBUpdateSettings.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDBFlow.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDBSink.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/javadsl/OrientDBSource.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDBFlow.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDBSink.scala
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/scaladsl/OrientDBSource.scala
- orientdb/src/test/java/akka/stream/alpakka/orientdb/OrientDBTest.java
- orientdb/src/test/scala/akka/stream/alpakka/orientdb/OrientDBSpec.scala
- project/Dependencies.scala
This PR is created to propose the addition of connector for [OrientDB](http://orientdb.com/orientdb/) in alpakka.
Features:
- Provides source & sink for reading & writing to OrientDB Document & Graph databases.
- Supports custom Objects api in javadsl using OrientDB OObjectDatabaseTx.
> Connector for orientdb #595

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsBrowseStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsSource.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsSource.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
Exposes the JMS queue browser API which iterates messages on the queue without consuming them.
> jms: add queue browser

- docs/src/main/paradox/sse.md
- sse/src/test/java/akka/stream/alpakka/sse/javadsl/EventSourceTest.java
The SSE connector has existing JavaDSL but it was not shown in docs, misleading users to think does not exist.
I added a docs sample, compile only spec.
> add missing Java docs for SSE Source

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
This is needed when streaming to an "index-pattern". 
Example:
posting documents to "my-index-2018-01-31" and "my-index-2018-02-01" while search in kibana for "my-index-*"
> elasticsearch: ElasticsearchFlowStage now supports custom indexName pr document

- s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala
- s3/src/test/scala/akka/stream/alpakka/s3/auth/CanonicalRequestSpec.scala
Fixes https://github.com/akka/alpakka/issues/719.
- The path encoding in `CanonicalRequest` was not encoding some reserved characters (in [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.2)), like `#`, `@`, and `&`.
- The query string encoding in `CanonicalRequest` used `java.net.URLEncoder` rather than just encoding the "non unreserved" characters (in [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.3)).
> S3: Fix request signing for path and query

- docs/src/main/paradox/external-connectors.md
Adds a reference to the external implementation of #434 to the external connectors list.
Fixes external connector links to Akka docs.
> Add Kinesis KCL lib to external connectors

- docs/src/main/paradox/slick.md
- slick/src/main/scala/akka/stream/alpakka/slick/javadsl/Slick.scala
- slick/src/main/scala/akka/stream/alpakka/slick/scaladsl/Slick.scala
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/DocSnippetFlowWithPassThrough.java
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/SlickTest.java
- slick/src/test/scala/akka/stream/alpakka/slick/scaladsl/DocSnippets.scala
- slick/src/test/scala/akka/stream/alpakka/slick/scaladsl/SlickSpec.scala
Proposal for additional 'Slick.flow' function to be flexible in the return type as suggested in [Make Slick Flow variable in return type](https://github.com/akka/alpakka/issues/726) issue.
Based on @ennru's suggestion called the new functions 'flowWithPassThrough', similar to ElasticsearchFlow.
The Scala implementation was quite forward. 
The Java implementation was a bit tricky. Added an additional 'mapper' argument to the method signature to map the DBIO result into something else.
Added test cases including an example with Kafka (also copied from Elasticsearch test case).
Updated documentation including 'with kafka' example.
Let me know what you think of this solution.
> Make Slick Flow variable in return type

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
- cassandra/src/test/java/akka/stream/alpakka/cassandra/javadsl/CassandraSourceTest.java
- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSourceSpec.scala
- docs/src/main/paradox/cassandra.md
* Added 'CassandraFlow' to Cassandra, for both Java and Scala.
* Added tests and updated documentation including examples for both Java and Scala.
> Cassandra: Support passThrough in Flow

- docs/src/main/paradox/connectors.md
Just noticed the new connector was missing in the list.
> OrientDB: add to connectors listing

- docs/src/main/paradox/mqtt.md
Noticed a funny feature in the MQTT docs which is resolved by new line-breaks.
> MQTT: doc tabs broken in Paradox

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceSpec.scala
This addresses issue #776
* Adds a flag to SqsSourceSettings that will cause the source to complete after an empty receive
* Sources will stop polling for new messages after an empty receive is encountered
* Once the last current request completes and the buffer drains, the source completes
> Provide facility to complete an SQS stream after an empty receive

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
fixes #806 
basic idea,
when uploading to s3, if the input stream is empty append a single empty ByteString to the input. this forces the library to actually send request to s3.
> Empty s3 upload fails

- doc-examples/src/main/scala/jms/JmsSampleBase.scala
- doc-examples/src/main/scala/jms/JmsToFile.scala
- doc-examples/src/main/scala/jms/JmsToHttpGet.scala
- doc-examples/src/main/scala/jms/JmsToOneFilePerMessage.scala
- doc-examples/src/main/scala/jms/JmsToWebSocket.scala
- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsBrowseStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSinkStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSourceStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsConsumer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsProducer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsSink.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsSource.scala
- jms/src/main/scala/akka/stream/alpakka/jms/package.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsConsumer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsProducer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsSink.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsSource.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsBufferedAckConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsTxConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsBufferedAckConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsTxConnectorsSpec.scala
This allows the JMS producer (`JmsSink`) to also act as a flow, similar to what's offered by the [kafka producer](https://doc.akka.io/docs/akka-stream-kafka/current/producer.html). For example, you can ensure that a message is persisted to the queue before subsequent processing.
This actually eliminates the need for #691 since we can pipe the flow to `Sink.ignore` to get a sink with materialized `Future[Done]`. As a bonus, you get the actual exception instead of a generic `AbruptStageTerminationException`.
`JmsProducer` might be a better name than `JmsSink` at this point. However I didn't want to go and rename things without getting feedback first.
> jms: add flow producer

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisFlowSettings.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisFlowStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSink.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/scaladsl/Examples.scala
Fix for #816. Changes "parititon" to "partition" and "lineal" (consisting of lines) to "linear" (a sequence of steps).
> Kinesis fix spelling errors in API #816

- build.sbt
- project/AutomaticModuleName.scala
For some Alpakka modules the Java module name is not straightforward.
* I prefixed connectors to AWS technologies with `aws`. (Which should have been added to the Alpakka module names to begin with, IMHO.)
* Others use the main package name approach.
Fixes #769
> Add Java module names

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/CassandraBatchSettings.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSink.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSink.scala
- cassandra/src/test/java/akka/stream/alpakka/cassandra/javadsl/CassandraSourceTest.java
- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSourceSpec.scala
- docs/src/main/paradox/cassandra.md
* Add flow that uses unlogged batches to improve throughput when stream elements share the same 
partition key
* Implements tests for both Scala and Java.
* Documentation updated describing the new flow.
> Cassandra: add Flow using unlogged batches

- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
Previously if a stream with a `JmsConsumer.ackSource` had messages left to acknowledge (greater than the `bufferSize`) when it was being shutdown or aborted it would hang. This is because the `MessageListener` threads would be blocking on the `take` operation on the `ackQueue` and would never return which is required by the JMS spec when a `Connection` is being closed:
> From JMS 1.1:
> 4.3.4 Pausing Delivery of Incoming Messages 
If MessageListeners are running when stop is invoked, stop must wait until all of them have returned before it may return. While these MessageListeners are completing, they must have the full services of the connection available to them. 
Now when a `shutdown` or `abort` is called on the `KillSwitch` we close the `JmsSession` before the `Connection` as a message …
> JMS: Fix shutting down and aborting of streams with a JmsConsumer.ackSource (#820)

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvToMap.java
- csv/src/main/scala/akka/stream/alpakka/csv/CsvToMapJavaStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/CsvToMapStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvToMap.scala
- csv/src/test/java/akka/stream/alpakka/csv/javadsl/CsvParsingTest.java
- csv/src/test/java/akka/stream/alpakka/csv/javadsl/CsvToMapTest.java
- csv/src/test/scala/akka/stream/alpakka/csv/scaladsl/CsvParsingSpec.scala
- csv/src/test/scala/akka/stream/alpakka/csv/scaladsl/CsvToMapSpec.scala
- docs/src/main/paradox/data-transformations/csv.md
As most users will operate on String columns instead of the raw ByteString, I added decoding of ByteString directly in the CsvToMap stages. 
This could have been implemented via an extra map operation in the Flow, but I decided to code the conversion directly into the stages to reduce the number of intermediary data structures.
> CSV: support/document conversion to String

- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsTxConnectorsSpec.scala
The JMS tests have been failing quite a lot since the recent changes.
One problem are message duplicates in the "no message loss" tests, this change ignores duplicates.
> JMS: Accept redelivery of messages

- docs/src/main/paradox/mqtt.md
Unfortunately the Paho library [doesn't support the management of initial connects failing, by design](https://github.com/eclipse/paho.mqtt.golang/issues/77). This PR warns the reader.
> Spill the beans on Paho's connection management

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectionProvidersTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectionProvidersSpec.scala
Fix AMQP connection release from throwing if the connection is already closed
Closes #842
> Fix AMQP connection release from throwing

- build.sbt
- docs/src/main/paradox/connectors.md
- docs/src/main/paradox/google-fcm.md
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/FcmFlowModels.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/FcmNotificationModels.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmJsonSupport.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmSender.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleSession.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApi.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/javadsl/GoogleFcmFlow.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/javadsl/GoogleFcmSink.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/scaladsl/GoogleFcmFlow.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/scaladsl/GoogleFcmSink.scala
- google-fcm/src/test/java/akka/stream/alpakka/google/firebase/fcm/javadsl/Examples.java
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/ConditionBuilderSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/FcmNotificationSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmSenderSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApiSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/scaladsl/Examples.scala
- project/Dependencies.scala
fixes #750 
Things I did:
- inited a new module
- wrote the necessary models + jsconverters
- wrote the communication
- can authenticate and communicate with google
- wrote test for things
- can send notifications \o/
Things missing but I will working on after get some responses:
- write some docs 
- write the missing tests (after the api freezes)
- write the java api
- solve the leftover todos in the code
Questions:
1. The google-pubsub connector do the jwt encoding by hand, I used the jwt-core. By hand coding, or use a lib?
2. The google-pubsub use alpakka.googlecloud.pubsub, I used alpakka.google.firebase.fcm. More intermed package or not?
3. I have "common" codes with the google-pubsub. If you want I can modify both projects to use the same classes, or we could merge these two modul …
> google-fcm

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
`select()` is called before registering OP_ACCEPT events and without
timeout, so we end up waiting forever. Add `wakup()` call after event
registration.
> Unix domain socket: Fix bug with accepting initial connection.

- project/Dependencies.scala
This pull request updates following libraries according to the latest version of Elasticsearch:
- elasticsearch-rest-client to 6.2.2
- elasticsearch-cluster-runner (for testing) to 6.2.2.0
> Update Elasticsearch connector dependencies to Elasticsearch 6.2.2

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSinkSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSinkSettings.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Fix for #813. I also fix a Java test case on versioning support (currently it tests the wrong thing).
> Support specifying version type for ElasticSearch Flow or Sink

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Fix for #853
To expose the `Content-Type` I had to implement a `CustomContentTypeHeader`  as akka http [by design](https://github.com/akka/akka/issues/16523) does not provide a way to construct this header. 
Further `akka.http.scaladsl.model.ContentType` is a sealed trait so its not possible to have an implementation which extends both `ContentType` and `HttpHeader`. So the logic in `ObjectMetadata` also had to be changed to explicitly match header by name. Not sure if there is a better way possible to do this
> AWS S3: Expose Content-Type as part of ObjectMetaData

- .travis.yml
- project/Dependencies.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- sse/src/main/scala/akka/stream/alpakka/sse/javadsl/EventSource.scala
Scala 2.11.12 + 2.12.5
Akka 2.5.11
Akka Http 10.0.13 (including backports to support 10.1.1 see #847)
Scalatest 3.0.5
> Latest versions: Scala, Scalatest, Akka, Akka Http

- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseErrors.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseFlowSettings.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseFlowStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/javadsl/KinesisFirehoseFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/javadsl/KinesisFirehoseSink.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/scaladsl/KinesisFirehoseFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesisfirehose/scaladsl/KinesisFirehoseSink.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesisfirehose/javadsl/Examples.java
- kinesis/src/test/scala/akka/stream/alpakka/kinesisfirehose/DefaultTestContext.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseFlowSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesisfirehose/scaladsl/Examples.scala
This direct port of the relevant Kinesis functionality to use the Kinesis Firehose types for #122. I put it in the `kinesis` project rather than creating a new one as this matches the way AWS ship their own libraries. Similarly the `kinesisfirehose` package is used to match AWS.
It's not exactly an elegant solution to have significant portions of the Kinesis code duplicated with just package and type names changed. However, I spent a good while looking at some way to generalise the code but there isn't really that much that can be shared. The graph logic could be extracted out for the flow stage, but it starts to get a little messy and would have an impact on the existing interface, such as requiring exceptions to be generic and adding more methods to `KinesisFlowSettings` with sensible …
> Kinesis Firehose support #122

- docs/src/main/paradox/s3.md
- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/S3Settings.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/DocSnippets.java
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/DocSnippets.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
This PR adds the option to `listBucket` using the legacy version 1 api or the current version 2 api. The main driver for this is to support legacy requirements (e.g. third party clients that use version 1, or testing using mock S3 implementations that do not yet support the version 2 api).
The default behaviour is unchanged, using version 2. The Scala implementation makes use of default parameter values to trigger the different versions, whereas the Java implementation adds a new `listBucketV1` method which keep the v1 usage explicit and does not break any existing code that uses the version 2 api.
Looking through the response processing code the `ListBucketResult` only uses response elements that are the same in both version 1 and 2 so I have made no changes there.
Fixes akka/alpakka#468
> Add support for s3 list buckets v1

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
The Unix Domain Socket connector was closing connections when it was done reading from them. This is slightly problematic -- the server may still wish to write data to the socket even though the client has closed its write side. This PR simply removes the key cancellation and channel closing when reads have completed.
Thus, only when the source (from server -> client) has terminated, will the connection be closed. See https://github.com/akka/alpakka/blob/master/unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala#L264-L269
I have prepared some sample programs here to help illustrate the problem: https://github.com/longshorej/garbage/tree/master/unix-domain-socket-close
The program, `rust-client`, writes some data to the socket and closes …
> Unix Domain Socket - don't close socket when finished reading (may still have writes)

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
Another round of a few small tweaks. Hopefully after this it is quite stable :)
* `channel.write()` can throw an exception if writing to a closed socket, similar to the fix for read, see #873
* Following up on #878, `sendSink` shouldn't be coupled to `receiveSource`. This allows the server to continue to write data when the client has closed its write side.
/cc @huntc
>  Unix Domain Socket - more fixes

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
Make it possible to set a name on the connection to rabbitmq. While resolving issues this is quite useful :)
> AMQP: support naming connections

- dynamodb/src/main/resources/reference.conf
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
- dynamodb/src/test/resources/application.conf
This PR fixes #876 by changing the parallelism in DynamoDB so that it is applied to the HTTP connection pool.
I upped the default parallelism to 32 as this is the nearest power of 2 below 50, which is the default that [AWS used in their own SDK before deprecating the methods](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/AmazonDynamoDBAsyncClient.html). I've run up to 128 connections in production (by setting the akka-http config properties) without any problems so 32 seems perfectly safe.
> DynamoDB: Fix parallelism #876

- docs/src/main/paradox/ftp.md
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/ConfigureCustomSSHClient.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/scalaExamples.scala
Made it possible to use a custom SSH configuration.
An alternative would be the possibility to inject an `SSHClient` instance.
This should help with #874.
Worked together with @HarrisonBaxter
> FTP: Support custom SSH configuration

- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
... and validate the TxEnvelope on commit/rollback - hopefully at no or very minimal performance impact.
Unfortunately, cannot recreate issue on unit-test broker. Can consistently recreate issue on same 'abort message loss' test with our internal broker.
> JMS: Tombstone the message handling on abort (#904) 

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala
Closes #897 
As stated in https://www.rabbitmq.com/consumer-prefetch.html, setting the basicQos global flag to false makes the limit shared by all the consumers on the channel. Since each stage has a single channel and a single consumer, that's the appropriate configuration.
> Fix AQMP prefetch configuration for cached connections

- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttSourceTest.java
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
- mqtt/src/test/travis/acl
Separate topics between tests better so they do not interfere.
As it turned out the for local tests the docker container had to be cleaned up between two runs, otherwise it would fail for old (unacknowledged) data popping up.
Made sure Java tests and Scala tests don't use the same topic names.
> MQTT: Improve test stability

- docs/src/main/paradox/mqtt.md
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala
- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
Using a dynamic port hopefully clears #929.
Added some links to the Paho client lib, as well.
> MQTT: use dynamic port for proxy in tests

- .travis.yml
- build.sbt
- docs/src/main/paradox/data-transformations/json.md
- json-streaming/src/main/scala/akka/stream/alpakka/json/JsonStreamReader.scala
- json-streaming/src/main/scala/akka/stream/alpakka/json/javadsl/JsonReader.scala
- json-streaming/src/main/scala/akka/stream/alpakka/json/scaladsl/JsonReader.scala
- json-streaming/src/test/java/akka/stream/alpakka/json/JsonReaderUsageTest.java
- json-streaming/src/test/resources/application.conf
- json-streaming/src/test/resources/logback-test.xml
- json-streaming/src/test/scala/akka/stream/alpakka/json/JsonReaderTest.scala
- project/Dependencies.scala
> Support streaming of json-values (cntd.)

- csv/src/main/scala/akka/stream/alpakka/csv/CsvParser.scala
- csv/src/test/java/akka/stream/alpakka/csv/javadsl/CsvParsingTest.java
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
Parsing two-byte things on split `ByteString`s requires specialised states.
Fixes #880
> Csv: parsing two byte codes

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Headers.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Request.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3Client.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/JavaExamplesSnippets.java
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3HeadersSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
> AWS S3: multipart copy (continued)

- .jvmopts-travis
- .travis.yml
- docs/src/main/paradox/index.md
- docs/src/main/paradox/other-docs/snapshots.md
instead of daily. Publishing daily is problematic due to artifact version clashes if there were no commits between snapshot releases.
> Publish snapshots after every merge

- s3/src/main/scala/akka/stream/alpakka/s3/auth/package.scala
- s3/src/test/scala/akka/stream/alpakka/s3/auth/authSpec.scala
I coundn't find hex encoding in current depending libraries, therefore I added own implementation to remove the future dependency to JAXB.
Closes #952.
> AWS S3: Reimplementation of hex encoding to avoid depending on JAXB

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/MqttFlowStage.scala
- mqtt/src/test/java/akka/stream/alpakka/mqtt/javadsl/MqttSourceTest.java
* fixed clientId reuse between java and scala tests
* fixed `pull` call from paho library thread context
> A couple of fixes in MQTT tests

- mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSourceSpec.scala
This should make the MQTT tests stable until we fix https://github.com/akka/alpakka/issues/972
> Workaround for tcp stream too fast deinit

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
I ran into issues connecting to a ftps server and traced it down to this.
I still have an issue with needing to call `execPROT("P")`, to transfer files over ssl too,
but I'll open an issue for discussion first.
> FTP Use FTPSClient for ftps

- docs/src/main/paradox/ftp.md
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/examples/FtpSettingsExample.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/scalaExamples.scala
I've tested it agains the server, which requires encrypted data transfer and it works.
I'm not super sure how to add this case to the specs yet.
> FTP  Added `explicitSSL` parameter to `FtpsSettings` (#976).

- docs/src/main/paradox/elasticsearch.md
Add description about `includeDocumentVersion` property of `ElasticsearchSourceSettings` to the document.
This property is defined here:
https://github.com/akka/alpakka/blob/3902367aa8a9097d6f676adecb8fb475b76505af/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSourceSettings.scala#L17
and used in `ElasticsearchSourceStage`:
https://github.com/akka/alpakka/blob/3902367aa8a9097d6f676adecb8fb475b76505af/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceStage.scala#L80-L88
> Describe includeDocumentVersion property of ElasticsearchSourceSettings

- doc-examples/src/main/java/elastic/FetchUsingSlickAndStreamIntoElasticInJava.java
The doc examples are not compiled for PRs. This change is necessary to make them compile after #1016
> Docs: Use moved ElasticsearchSettings class

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala
I noticed that when the connection fails (wrong credentials or whatever) the connection is still null so there is a NullPointerException when trying to remove listeners.
However, the exception is not caught in the tests. Probably because it's thrown in a different thread?
Any advice on how to test or improve this is more than welcome :)
> Fix exception thrown when AMQP can't connect to the server.

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/CassandraSourceStage.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/GuavaFutures.scala
Fixes #1021 
* also using `Future.foreach` instead of `map`/`flatMap` for side effect
* not using redundant scala Future implicit class conversion (we are only interested in the side effect of `AsyncCallback` anyway…)
* not replacing boxed `ResultSet` on every fetch (`ResultSet` is reusable, no need to generate garbage for gc)
* general boyscouting
> Cassandra: avoiding isExhausted calls + prefetching results when buffer is half full

- docker-compose.yml
OrientDB `latest` docker image has been updated to `3.0.2` and that started failing tests: #1046
> Pin OrientDB version to 2.2.35

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
Adjust S3 MultiPartUpload to use non-static signing key.  See issue: 
https://github.com/akka/alpakka/issues/996
> Non-static signing key for S3 MultiPartUpload (#996)

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoClient.scala
Implementing `DynamoClient` as a class, and in particular a final class, means that it's not possible to mock for testing repositories that use it.
This change converts it to an interface and returns an anonymous class implementing it from the apply method, which will be source-compatible with `DynamoClient(settings)`, although not with `new DynamoClient(settings)`.
Removing the `final` modified from the class would be another option, which would keep source compatibility in either of the above cases, but this seems like a cleaner approach to me.
> DynamoDB client interface rather than class

- docs/src/main/paradox/hbase.md
- hbase/src/main/scala/akka/stream/alpakka/hbase/HBaseSettings.scala
- hbase/src/main/scala/akka/stream/alpakka/hbase/internal/HBaseFlowStage.scala
- hbase/src/main/scala/akka/stream/alpakka/hbase/javadsl/HTableStage.scala
- hbase/src/test/java/akka/stream/alpakka/hbase/javadsl/HBaseStageTest.java
- hbase/src/test/scala/akka/stream/alpakka/hbase/scaladsl/HBaseStageSpec.scala
I need to perform different kind of mutations on HBase given an input message.
Until now  only `put` is supported. 
My idea is to return a list of `Mutation` from the `converter` function instead of a single `Put` instance.
Then I have changed:
```
table.put(settings.converter(msg))
```
with:
```
val mutations = settings.converter(msg)
for (mutation <- mutations) {
mutation match {
case x: Put => table.put(x)
case x: Delete => table.delete(x)
case x: Append => table.append(x)
case x: Increment => table.increment(x)
}
}
```
This should allow to perform different kind of mutations (delete, increment, append) and also perform no mutations (useful if you have some business logic to skip some records).
It can probably solve #328 and #326
What do you think?
> HBase: Allow multiple mutations

- project/Dependencies.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
Fixes an issue observed with unix domain socket connector where when the read side was closed, the NIO event loop would go into an infinite loop with `channel.read` returning `-1`.
We should have be deregistering interest in `READ` when completing the queue.
Related PR: https://github.com/akka/alpakka/pull/878
/cc @huntc
> Unix Domain Socket - ensure that interest in READ is removed upon EOF

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
- cassandra/src/test/java/akka/stream/alpakka/cassandra/javadsl/CassandraSourceTest.java
The pass through-functionality for Cassandra flows relies on a `map` on the future to just push in the pass through-value, by using Akkas `ExecutionContexts.sameThreadExecutionContext` this does not require an execution context to be passed in.
Fixes #1035
> Cassandra: remove need for execution context

- README.md
The previous maven link used inside `README.md`, `https://search.maven.org/search?q=akka-stream-alpakka` seems to not work anymore.
I have changed it to `https://search.maven.org/#search%7Cga%7C1%7Cakka-stream-alpakka`.
> Fix maven search url

- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Field type `string` is deprecated in the recent versions of Elasticsearch. We should use `text` or `keyword` instead.
> Fix warning in Elasticsearch test

- docs/src/main/paradox/jms.md
In the JMS documentation, the source code in the 'Create a JmsConsumer to an IBM MQ Queue' section doesn't display properly. This should fix it (by simply removing two newline characters).
> Fixed visualization glitch in IBM MQ JmsConsumer doc section

- xml/src/main/scala/akka/stream/alpakka/xml/Xml.scala
- xml/src/main/scala/akka/stream/alpakka/xml/javadsl/XmlParsing.scala
- xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlParsing.scala
- xml/src/test/scala/akka/stream/alpakka/xml/scaladsl/XmlProcessingTest.scala
When there are invalid bytes in XML, aalto-xml parser throws an exception like below:
```
[ERROR] [07/12/2018 17:57:02.332] [default-akka.actor.default-dispatcher-2] [akka://default/system/StreamSupervisor-0/flow-0-0-ignoreSink] Error in stage [akka.stream.alpakka.xml.Xml$StreamingXmlParser@110ba553]: Illegal XML character ((CTRL-CHAR, code 8))
at [row,col {unknown-source}]: [10895,11]
com.fasterxml.aalto.WFCException: Illegal XML character ((CTRL-CHAR, code 8))
at [row,col {unknown-source}]: [10895,11]
at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
at com.fasterxml.aalto.in.XmlScanner.handleInvalidXmlChar(XmlScanner.java:1526)
at com.fasterxml.aalto.async.AsyncByteArrayScanner.parseCDataContents(AsyncByteArrayScanner.java:638)
at …
```
> XML: Add ignoreInvalidChars option to XmlParsing.parser

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectorSettings.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala
- amqp/src/test/java/docs/javadsl/AmqpDocsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
- amqp/src/test/scala/docs/scaladsl/AmqpDocsSpec.scala
Fixes #1000 
The introduced field is `NamedQueueSourceSettings.ackRequired` rather than `autoAck` (being the name of the affected parameter in underlying amqp-client lib) to avoid confusion with the existing autoAck functionality (cc #97).
New integration test only tests that it isn't broken. Given the flag is merely passed to underlying library, I think we can assume that it works as intended.
> AMQP - allow setting of autoAck on underlying channel.basicConsume call

- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisErrors.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisFlowStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/javadsl/KinesisFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/Examples.java
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/scaladsl/Examples.scala
* KinesisFlowStage now receives pairs of (PutRecordsRequestEntry, T)
* KinesisFlowStage outputs pairs of (PutRecordsResultEntry, T)
* Object of type T is passed through without modifications
* Can use T as a context to correlate input and output messages
* Changes are hidden behind the existing public API
* New method KinesisFlow.withUserContext enables using the context
Rationale: In our project, we were faced with the problem of mirroring a Kafka topic to a Kinesis stream. In order to ensure at-least-once semantics, we need to be careful to commit Kafka message offsets back only when they were successfully written to Kinesis. However, due to the async nature of Kinesis put requests, the message order to Kinesis is not guaranteed. So we need to manually track which messages have already …
> AWS Kinesis: Allow passing a user context object with each message.

- doc-examples/src/main/java/elastic/FetchUsingSlickAndStreamIntoElasticInJava.java
- doc-examples/src/main/scala/elastic/FetchUsingSlickAndStreamIntoElastic.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSinkSettings.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Currently, `ElasticsearchFlow` supports only **insert** and **upsert**. We can configure a flow as either one of them.
This pull request adds support for **update** and **delete** by message types by introducing following incoming message types:
- `IncomingIndexMessage`
- `IncomingUpdateMessage`
- `IncomingUpsertMessage`
- `IncomingDeleteMessage`
This also means it makes possible to handle all request types in single flow.
I'm not sure whether I should modify existing `ElasticsearchFlow` interfaces to support this functionality. I think it doesn't need so much effort to update existing code which uses `ElasticsearchFlow` to this version, but breaking source code compatibility is a fact.
If keeping source code compatibility is critical in Alpakka connectors, I would like to add new flow …
> Elasticsearch: Support update and delete by incoming message types

- doc-examples/src/main/scala/elastic/FetchUsingSlickAndStreamIntoElastic.scala
- elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSpec.scala
Mapping types will be removed in the future version of Elasticsearch and using `_doc` as a single mapping type is recommended in Elasticsearch 6.x.
https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html
> Use _doc as type in Elasticsearch tests

- .travis.yml
- hbase/src/test/java/akka/stream/alpakka/hbase/javadsl/HBaseStageTest.java
- hbase/src/test/scala/akka/stream/alpakka/hbase/scaladsl/HBaseStageSpec.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/Examples.java
- slick/src/test/java/akka/stream/alpakka/slick/javadsl/DocSnippetFlowWithPassThrough.java
- udp/src/test/java/docs/javadsl/UdpTest.java
Before we used environment variable as a name, because that showed up in the Travis UI. However since stages went out of beta, support for job names has been added.
This also reformats some Java test code, which was left unformatted after the Java formatter change.
> Add names to Travis jobs

- build.sbt
- unix-domain-socket/src/main/java/jnr/enxio/channels/KQSelector.java
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
- unix-domain-socket/src/test/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocketSpec.scala
This PR includes a number of improvements to the `halfClose` handling of the Unix Domain Socket. `halfClose` is particularly relevant for clients (and enabled by default), as they will close their write side to signal end of input, but will still wish to read data from the server.
The main changes here are to call `shutdownOutput` and `shutdownInput` where appropriate, instead of closing the channel. Additionally, a bug in JNR is worked around which was causing some NIO events to be lost.
Fixes https://github.com/akka/alpakka/issues/1139
> Unix Domain Socket - Improve halfClose handling

- contributor-advice.md
Add a short note on how to select the `IODispatcher` when wrapping block IO operations from client libraries.
See #1173
> Add advice to select IODispatcher

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Exceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsSettingsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsMessageProducerSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsSettingsSpec.scala
- project/Dependencies.scala
- JmsProducerStage now supports multiple sessions by behaving
similarly to MapAsync
- Producers are pooled and parallelism is controlled by how producers
are returned to the pool.
- Created a separate JmsMessageProducer class to keep the stage logic
more focussed on coordinating elements within the stage.
- Grouped the logic for creating the execution context to use in the
producer stage as well as in the consumer stage.
Fixes #1144
> JMS producer multi session

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsMessageProducerSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
- This is a shameless minor update of the changes done by @liff in #862 to make it work with the changes done by @russellyou  #867. More specifically, to be able to use the `create` API from `Destination`.
> JMS: Support for durable subscriptions #966

- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvToMap.scala
In `CsvToMap.withHeadersAsStrings` the `charset` parameter was ignored
> CSV: CsvToMap default charset

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsSettingsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsBufferedAckConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsSettingsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsTxConnectorsSpec.scala
> JMS: Adding connection timeouts and retries (fixes #1192 and #1193)

- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSpec.scala
This fixes messages arriving order when pulling from a FIFO queue and adds test coverage for that particular scenario.
Feel free to make suggestions to this one. Otherwise, this is ready to be merged.
Cheers!
> AWS SQS: Keep message order

- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceFlow.scala
- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceSource.scala
- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceWithResourceFlow.scala
- reference/src/main/scala/akka/stream/alpakka/reference/javadsl/Reference.scala
- reference/src/main/scala/akka/stream/alpakka/reference/javadsl/ReferenceWithResource.scala
- reference/src/main/scala/akka/stream/alpakka/reference/model.scala
- reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/Reference.scala
- reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/ReferenceWithResource.scala
- reference/src/main/scala/akka/stream/alpakka/reference/testkit/MessageFactory.scala
- reference/src/test/java/docs/javadsl/ReferenceTest.java
- reference/src/test/java/docs/javadsl/ReferenceWithResourceTest.java
- reference/src/test/scala/docs/scaladsl/ReferenceSpec.scala
- reference/src/test/scala/docs/scaladsl/ReferenceWithResourceSpec.scala
* Exemplify WriteMessage => WriteResult
* Rename ReadMessage to ReadResult as it comes from the outside
* showcase testkit to allow constructing result instances
* use full package names for Java classes
> Reference: updates to message types

- project/Dependencies.scala
Update mongo-scala-driver to latest version (2.4.2)
> Mongo: Update driver to 2.4.2

- docs/src/main/paradox/solr.md
- solr/src/main/scala/akka/stream/alpakka/solr/SolrFlowStage.scala
- solr/src/main/scala/akka/stream/alpakka/solr/SolrUpdateSettings.scala
- solr/src/main/scala/akka/stream/alpakka/solr/javadsl/SolrFlow.scala
- solr/src/main/scala/akka/stream/alpakka/solr/javadsl/SolrSink.scala
- solr/src/main/scala/akka/stream/alpakka/solr/scaladsl/SolrFlow.scala
- solr/src/main/scala/akka/stream/alpakka/solr/scaladsl/SolrSink.scala
- solr/src/test/java/akka/stream/alpakka/solr/SolrTest.java
- solr/src/test/resources/conf/schema.xml
- solr/src/test/scala/akka/stream/alpakka/solr/SolrSpec.scala
At this moment, there's a little problem of performance with SolR component because there's no asynchronous part in the code. So the batch size is always 1. 
I propose an alternative by keeping the inspiration from the Elastic Search component.
The solr update is now encapsulated in a future, and the async callbacks are used to make everything coherent (in failure and in success).
Still using the elastic search code, I will provide a notion of operation, to allow the removal of documents.
Please, have a look.
> Solr: support update/delete/atomic update operations and batch those

- .jvmopts-travis
Last release from Travis failed because of `java.lang.OutOfMemoryError: Java heap space`
https://travis-ci.org/akka/alpakka/jobs/434147431
> Increase java heap spave on Travis

- docs/src/main/paradox/jms.md
- jms/src/main/scala/akka/stream/alpakka/jms/Jms.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsBrowseStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsConsumer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/javadsl/JmsProducer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsConsumer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/scaladsl/JmsProducer.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsSettingsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsMessageProducerSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsProducerRetrySpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsSettingsSpec.scala
This is my proposal on how to achieve producer retries with reconnects.
I also simplified some code along the line (which I hope is okay for everyone).
Also, I added a missing async callback on disconnect that incidentally also changes the amount of retries performed in the reconnect test (I will point out in annotations where).
Documentation is lacking for now, I will add some examples once we are fine with the design and the way it works.
Fixes #1226
> Jms producer retries

- xml/src/main/scala/akka/stream/alpakka/xml/impl/Subtree.scala
- xml/src/test/scala/docs/scaladsl/XmlSubtreeSpec.scala
Pull request to fix issue #1276 
Call of the function `Document.createElementNS` in `Subtree` had the arguments in inverted order (see documentation [here](https://docs.oracle.com/javase/8/docs/api/org/w3c/dom/Document.html#createElementNS))
> XML: fix subtree with namespace parsing

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSource.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
Fixes #1254.
Adds a returnImmediately flag to the creation of a PubSub Source,
with the default still set to true for backwards compatibility.
> Google Pub/Sub: backoff after no messages fetched

- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsSourceStage.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Hi, first time contributing here, so hopefully I didn't miss anything from the instructions.
In addition, I signed the CLA
**Feature**: 
Allow setting the visibility timeout parameter in the SQS `Receive` request.
this means that in each `Receive` request it will override the default visibility timeout from SQS queue configuration. if one will not set it, the default will be taken.
The requirement:
if one knows the maximum time it takes to process a message and want to set it in the application (and not in the SQS queue console) this change will reduce the number of calls. So, instead of 2 calls - `Receive` and `ChangeVisibilityTimeout`, we will just run the `Receive`
We, At the company I'm working for, started a code migration from our old SQS client to Alpakka.
during the migration we …
> AWS SQS: Source - Allow configuring visibility timeout

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestStateSpec.scala
The ask pattern is overkill for situations where there is a strong coupling between one actor and another, as is the case between an MQTT session and its many command and event flows. For instance, if an MQTT session actor is lost for any reason, then its associated flows will also be failed. In this scenario, where a flow notifies the session of, say, an event having been received, it is effectively “calling” the session actor as per a function call, but using a message. The request is effectively synchronous in nature (although there is no blocking of course). The session actor must promise to yield a result, no matter what. Not yielding a result is a bug.
As such, we can use promises instead of the ask pattern for tightly coupled callers calling on actors. This then yields the …
> MQTT streaming: Retire ask in favour of promise

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
A situation can occur where a CONNECT is received by the MQTT server while in a state of already being connected. In this case, we need to process the new CONNECT i.e. CONNACK it etc.
Thanks to @longshorej for discovering the issue and providing the remedy.
> MQTT streaming: Handle connect while connected

- avroparquet/src/test/java/docs/javadsl/AvroParquetSinkTest.java
File was zero size because ParquetWriter was not closed. 
It was happened due to the one of two options:
-  Either  `Source.from(records).runWith(sink, materializer)` took more then 1 sec.
-  There was an uncaught exception in Sink.    
Anyway, I removed `Thread,sleep` method. At least we will get more clear exception next time.
> Avro Parquet -  AvroParquetSinkTest.createNewParquetFile #1316

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
Fixes #1300 
note: I am considering adding a test for this case, however it proved to be not as straightforward as the fix itself 😄 
Opening PR in case it is acceptable to get the merge without it, will continue looking into creating a test in any case - as part of this PR or a separate one.
> Elasticsearch: failStage should happen when shouldRetry returns false

- docs/src/main/paradox/mqtt-streaming.md
- mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/MqttPerf.scala
- mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttPerf.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/MqttSession.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Client publications wouldn’t previously withstand a connection being lost, whereas server publications would. I’ve now aligned the client publication handling with the server publication handling.
In addition, session objects are now told to perform a publish command directly. The rationale is that the session object is the only thing that can guarantee the QoS requirements of a PUBLISH. I use the "tell" syntax of actors as I feel that it has the same meaning i.e. "communicate directly". For example:
```scala
clientSession ! Command(Publish(topic, ByteString("ohi")))
```
Prior to this work, PUBLISH commands were communicated with a command flow, which is often associated with a network connection. The problem with the approach was that PUBLISH commands could be lost if a network …
> MQTT streaming: Resilient client publications

- CONTRIBUTING.md
The links to O'Reilly were redirecting to their home page. Pointed them at what I'm assuming is the new home for each resource.
> Fixed 2 dead links in the contributing guidelines

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestStateSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Numerous hardening activities around MQTT streaming. Please visit each commit for a full description. However, in summary:
* Corrected misinterpretation of behaviour setup
* Avoid a race condition when creating child actors
* Handle a duplicate publish while consuming
* Connection packet id distinction which now allows more than one client to send the same packet id as another
> Further MQTT streaming hardening

- docs/src/main/paradox/solr.md
- solr/src/main/scala/akka/stream/alpakka/solr/SolrFlowStage.scala
- solr/src/test/java/akka/stream/alpakka/solr/SolrTest.java
- solr/src/test/resources/conf/schema.xml
- solr/src/test/scala/akka/stream/alpakka/solr/SolrSpec.scala
On atomic update, the routing value is required when there is a routing field configured on the server (implicit routing). With the compositeId routing, this routing value is not needed.
https://lucene.apache.org/solr/guide/7_5/shards-and-indexing-data-in-solrcloud.html#document-routing
> Solr: Routing value for atomic update becomes optional

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
Prior to this change, an MQTT client could only send one SUBSCRIBE for a given topic at a time without receiving an `IllegalStateException`. It is quite plausible that multiple SUBSCRIBE requests for the same topic are made in succession given connection failures. This change now stashes requests while a SUBSCRIBE is occurring on the client, in the same way that the server does.
Also, I was sending out a SUBSCRIBE request for each topic filter, whereas it should go out as just one request. This would have caused errors had the feature been leveraged by someone (we aren’t leveraging this feature presently). (same for UNSUBSCRIBE - doh!)
> MQTT streaming: Modal subscriptions

- avroparquet/src/test/java/docs/javadsl/AvroParquetSinkTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsProducerRetrySpec.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- project/Dependencies.scala
Affects Akka Typed usage in mqtt-streaming given some API changes.
Also found a bug in matt-streaming along the way in that it was incorrect in handling client connection failures. We should handle a client connection actor terminating only when it terminates gracefully or with an exception that we expect. If we get an unexpected exception then we should not try to handle it. We should also notify observers of the client connection being terminated no matter whether it stops gracefully or not.
> Akka 2.5.19 upgrade

- solr/src/main/scala/akka/stream/alpakka/solr/SolrFlowStage.scala
Solr: partition changes the order. Use instead span
> Solr: partition changes the order.

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsBatchException.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsAckFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchChangeMessageVisibilityFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchDeleteFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsBatchStageLogic.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsFlowStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsSourceStage.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala
- sqs/src/test/java/docs/javadsl/SqsAckTest.java
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/java/docs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/SqsModelSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
> AWS SQS: Improve SqsAckResult and SqsPublishResult consistency

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
Sometimes, depending on the Elasticsearch cluster configuration, we need to change the scroll value (1m, 5m, 15m, 60m, etc.).
=> ES: Moving the scroll value to ElasticsearchSourceSettings in order to be able to change it if necessary.
> ES: Making the scroll value configurable

- project/Common.scala
that sneaked in while experimenting in https://github.com/akka/alpakka/pull/1369/commits/92816967512166ada8e26615b554deeb6aae1027
> Fix scaladoc source url

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
When connections are lost the client and server flows now shutdown appropriately. This was not always the case previously.
In addition, the stashing was artificially limited which could cause problems. Overflowing memory is now entirely a caller concern.
> MQTT streaming: Connection hardening

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
We've been testing the MQTT connector in a production environment, hence discovering a few bugs. The production environment consists of a very low powered CPU and so the scenarios being fixed are largely as a result of a completely different timing behaviour to that of much faster machines.
The collection of commits here largely address an oversight on my part where I had misunderstood `flatMapMerge` to complete on a `Source` completing. It doesn't, and it shouldn't, and I don't know what I was thinking. :-)
I've now introduced a kill switch so that when a disconnection occurs within a client or server session then their associated command flows are terminated. I've enhanced a test to prove this out.
I've made some inline comments of other little things that I've fixed.
Finally, I've done …
> MQTT streaming: More connection failure hardening

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/java/akka/stream/alpakka/s3/javadsl/S3ClientTest.java
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SourceSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
AWS S3 - allow to get object metadata without size limit
fixes #1348
1. [getObjectMetadata](https://github.com/akka/alpakka/blob/daba7df05114420c7470962310e0ed8d0557150c/s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala#L138) calls HEAD on a file in S3.
2. s3-server returns the response with `Content-Length` set but [without the real data](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html).
3. if the value in `Content-Length` is greater than `http.client.parsing.max-content-length` (8 mb by default), HEAD operation (and hence getObjectMetadata) fails, e.g.:
```
Failure(EntityStreamSizeException: actual entity size (Some(10380000)) exceeded content length limit (8388608 bytes)!
You can configure this by setting …
```
> AWS S3 - allow to get object metadata without size limit

- project/Dependencies.scala
Whitesource started reporting `jaxb-impl-2.2.3U1.jar (rejected by policy '*GPL* - Reject')` when that version got picked.
> Licensing: Explicitly depend on jaxb-impl 2.2.3-1 in Hbase

- build.sbt
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
- project/Dependencies.scala
* exclude docs from Whitesource reporting
* Spray upgrade has reordered fields in expected JSON
> Use to Jackson 2.9.8, Spray Json 1.3.5

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
The kill switch introduced in the last PR remained in effect across multiple flows - I hadn’t noticed this. The flows now each have their own kill switch which solves the regression that was introduced with the last PR.
Thanks to @longshorej for educating me on `lazyInitAsync` - very useful!
I've also strengthened the handling of connections being lost while waiting for SUBACKs.
> Connection hardening III - Unique kill switch to solve a regression

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GooglePubSubSource.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub/src/test/java/docs/javadsl/ExampleUsageJava.java
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-cloud-pub-sub/src/test/scala/docs/scaladsl/ExampleUsage.scala
Fixes issue https://github.com/akka/alpakka/issues/832
The usage of the api key was removed in https://github.com/akka/alpakka/pull/683
Hopefully we can get this in before 1.0 as it will be a breaking change for the scala/java api.
> google-cloud-pub-sub: remove redundant api key

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Prior to this commit, if a server-side session was publishing to a client and the client disconnected, and then subsequently reconnected, its publications would be lost. This is because I was closing over some actor state within a future. Whoops.
I’ve now written a comprehensive test for this scenario, along with some additional, unrelated, subscription tests along the way.
I also cancel timers explicitly to be tidy (and to avoid potential misfiring issues, although I've not seen any), and the logging has been improved so that debug log levels outputs MQTT events sans sensitive info (passwords, payloads); the latter being useful toward logging.
> MQTT streaming: Fixup the continuation of a session

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Prior to this PR, a lack of a CONNACK would result in the client stream completing, but with no explanation. We now fail the client stream with an appropriate exception.
Also, the lack of a SUBACK would be silently ignored. This PR makes the lack of a SUBACK consistent with a lack of a CONNACK in that the client stream will be failed with an appropriate exception.
Also, a small improvement to the command logging so that we can capture any generated packet ids.
> Fail the client when no CONNACK or SUBACK

- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/avroparquet.md
- docs/src/main/paradox/awslambda.md
- docs/src/main/paradox/azure-storage-queue.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/dynamodb.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/geode.md
- docs/src/main/paradox/hbase.md
- docs/src/main/paradox/ironmq.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/slick.md
- docs/src/main/paradox/udp.md
- docs/src/main/paradox/unix-domain-socket.md
Removes the `Usage` documentation topic sub-header from most of the connectors where it was present (except S3 and couchbase as those have PRs pending).
With this change the connector TOC boxes in the main page contain more relevant information and are `Ctrl+f` friendly.
> Drop the unneccessary level in documentation

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Producers of PUBLISH should tend to need to re-send messages faster than the consumer may be able to process them, otherwise the consumer may fail the connection entirely and cascade the problem. Sending multiple publications is benign with MQTT and has the positive effect of resetting the consumer’s timers. This works particularly well on machines where the JVM startup is very slow e.g. a single core Atom processor.
As a side note, Paho’s client has the same separation of concerns in terms of retry interval and receive timeout. We also have the same values of 15 seconds and 30 seconds respectively.
> Separate producer/consumer timeouts

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectorSettings.scala
Fixes `withSSLContext` being effectively a NOOP.
> Pass the argument from the method

- .travis.yml
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/model.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/resources/logback-test.xml
- couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseFlowSpec.scala
- docker-compose.yml
- docs/src/main/paradox/couchbase.md
Add a `upsertDocWithResult` operator emitting `CouchbaseWriteResult` subclasses for users that need to handle write failures in-stream.
cc @dannylesnik
> Couchbase: introduce upsertDocWithResult to handle write errors in-stream

- .travis.yml
- RELEASING.md
- build.sbt
- project/PublishRsync.scala
This reverts back to using ssh-agent in Travis. This allows us to not hardcode paths to the identity files, so the deployment setup works in Travis and locally.
> Fixes for doc publishing

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
It is quite possible that a client can receive a `PUBLISH` message immediately on connection and before a subscription occurs given the prior establishment of a server-side session. In this case, the `PUBLISH` message will often have the `DUP` flag set. Prior to this PR, the `DUP` flag would cause a packet router failure given that the routing decision was being performed out of step with where the routing state is managed. This PR moves that routing logic to the correct place.
A new test has also been added for the use-case described above along with existing coverage validating the `DUP` processing.
> MQTT streaming: Tolerate DUP PUBLISH messages on first connecting

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GooglePubSubSource.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/TestCredentials.scala
Addresses https://github.com/akka/alpakka/issues/1435
Previously  returnImmediately and maxMessages where hard coded in the api. Now they are exposed as options in the config.
> gce pubsub. When pulling make the options configurable.

- s3/src/main/scala/akka/stream/alpakka/s3/impl/SetupStage.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
- s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
> S3: Propagate attributes when nesting Akka Stream operators with Setup

- .github/ISSUE_TEMPLATE/--bug-report.md
So it does not end up in a newly created ticket of not removed
> Informational section as a comment

- docs/src/main/paradox/kudu.md
- kudu/src/main/resources/reference.conf
- kudu/src/main/scala/akka/stream/alpakka/kudu/KuduAttributes.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/KuduClientExt.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/impl/SetupStage.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/javadsl/KuduTable.scala
- kudu/src/main/scala/akka/stream/alpakka/kudu/scaladsl/KuduTable.scala
- kudu/src/test/java/docs/javadsl/KuduTableTest.java
- kudu/src/test/resources/application.conf
- kudu/src/test/scala/docs/scaladsl/KuduTableSpec.scala
Fixes #1217
Clean up Kudu Akka Stream operator factories from resources. 
Akka Stream operators are blueprints which are meant to be reused. Therefore external resources needed for the operators should either be resolved during materialization or injected via stream attributes.
> Manage kudu client in an extension

- docs/src/main/paradox/kinesis.md
- Leverages the new KCL 2.x to support "enhanced-fanout" and other new features
N/A
- Include more alternatives which leverage the AWS KCL library
- Updates AWS Kinesis document section
- No library at the moment supports the new KCL 2.x
N/A
> AWS Kinesis - Docs - Another alternative KCL based source

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
Add null checks for `indexName` on `ElasticsearchSource`.  Add null checks for `indexName` and `typeName` on `ElasticsearchFlow`
The `indexName` and `typeName` `String` params are used in `ElasticsearchFlowStage` when creating the indexing JSON request for Elasticsearch.  If the parameters are `null` and added as `JsStrings` to the request JSON (https://github.com/akka/alpakka/blob/v1.0-M2/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala#L157..L158) then an NPE will be thrown from deep inside spray-json when the request JSON is serialized.  This is a known issue in spray-json (https://github.com/spray/spray-json/issues/70).  The reason I passed `null` to these parameters was due to a different issue related to a known Scala bug …
> ElasticSearch null check for index and type name on source and flow

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisSourceStage.scala
When using `akka-stream-alpakka-elasticsearch` and `akka-stream-alpakka-kinesis` in the same project, the following error will get swallowed:
```
Exception in thread "main" java.util.concurrent.ExecutionException: com.amazonaws.SdkClientException: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
You have two possible resolutions:
1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
```
> AWS Kinesis: Better error for GetShardIteratorFailure

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Prior to this PR, more than 10 control packets (configurable) could come in very quickly and prevent the client or server handling more. This created a problem if, say, 10 `PUBLISH` packets were received then followed by a `SUBACK`. The `SUBACK` would never be processed.
The changes here no longer restrict subscriptions and unsubscriptions for both the client and server from occurring only one at a time. This then frees the session to process packets without effectively being blocked.
An added bonus is that the code is somewhat simplified. :-)
Also new, is the introduction of the ability to be notified of server-side SubAck completion. It is important for the server to know when it is the right time to start publishing for a newly subscribed topic; too early and the publications will be …
> Parallel subscriptions/unsubscriptions and SubAck notifications

- .travis.yml
- docker-compose.yml
- docs/src/main/paradox/jms/ibm-mq.md
- jms/src/test/java/docs/javadsl/JmsIbmmqConnectorsTest.java
- jms/src/test/scala/docs/scaladsl/JmsIbmmqConnectorsSpec.scala
- project/Dependencies.scala
Compilable docs for IBMMQ and documentation update
1. Add ibmmq docker image
2. Add ibmmq clients dependency
3. Add test classes: scaladsl and javadsl
I currently building integration at work and I use `alpakka/jms` connector. I saw differences between versions `1.0-M1` and `1.0-M2`. Also there is opened issue for doc update.
I decided to help. I am looking forward for release `1.0`
ref: #1328
> JMS: IBMMQ update docs

- docker-compose.yml
- jms/src/test/java/docs/javadsl/JmsIbmmqConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/CachedConnectionFactory.scala
Fixes #1493 by adding the required methods.
* sort docker compose file
* reformat Java code
> JMS: Adapt to JMS 2.0 API change in tests

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestStateSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Packet ids now monotonically increase until they reach the maximum value, upon which they wrap around to the minimum. Care is taken to ensure that packet ids that are in use are not issued, as it is
technically possible, albeit rare.
This fixes a number of potential race conditions. For example, consider a PUBLISH -> PUBACK exchange with QoS1 with the old behavior:
1) Server retransmits an unacknowledged publish
2) Before client receives retransmission, it finally ACKs original publish.
3) Server receives ACK, and performs new publish, reusing the last id.
4) Client receives retransmission from # 1, and ACKs it.
5) Server receives ACK, and misinterprets it as an ack from # 3
6) Oh no!
By wrapping around, we've effectively eliminated the changes of this happening. This is similar to how …
> mqtt-streaming: Prefer wrapping instead of reissuing packet ids

- build.sbt
Flags for scalac compiler plugin introduced in #1486 should not be set when generating API docs.
> Do not apply scalac compiler plugin flags when generating API doc

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/WriteMessage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
op_type that can be used to force a create operation, allowing for "put-if-absent" behavior. When create is used, the index operation will fail if a document by that id already exists in the index.
Fixes #xxxx
Add op_type 'create' which index only if not exists.
Adding missing Elasticsearch supported option to create a document only if not exists.
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html
> Elasticsearch: Add CreteCreateMessage which supports Elasticsearch op_type 'create'

- hdfs/src/test/resources/logback-test.xml
- project/Dependencies.scala
Upgrade Cats to 1.6.0 as it is available for Scala 2.13.0-M5.
Sorted out log4j vs slf4j while at it.
Part of #828
> HDFS: Cats 1.6.0 and logging sorted out

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectorSettings.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/AmqpRpcFlow.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/AmqpSink.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/AmqpSource.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/javadsl/CommittableIncomingMessage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/model.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpRpcFlow.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpSink.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpSource.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/CommittableIncomingMessage.scala
- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java
- amqp/src/test/java/docs/javadsl/AmqpDocsTest.java
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
- amqp/src/test/scala/docs/scaladsl/AmqpDocsSpec.scala
- docs/src/main/paradox/amqp.md
Fixes #1500 
Part of #1223 
Make use of `assertAllStagesStopped` to ensure proper stream shutdown in test cases.
Add `ApiMayChange` on stream element classes as they have unfortunate names.
> Amqp: assert all stages stopped and fix source shutdown

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/WriteMessage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSink.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSink.scala
- elasticsearch/src/test/java/docs/javadsl/ElasticsearchTest.java
- elasticsearch/src/test/resources/application.conf
- elasticsearch/src/test/resources/log4j2-test.xml
- elasticsearch/src/test/resources/logback-test.xml
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
Change Elasticsearch flow signatures to single element flows.
Akka has introduced a new type of flow `withContext` which supports `passThrough`s to be passed hidden from the user.
Elasticsearch flows used to do have internal logic for batching which made them consume `WriteMessage`s but emit `Seq[WriteResult]`s which does not work together with context promotion.
The retry logic in `ElasticsearchFlowStage` does not work with context promotion, either.
This ended up in a major rewrite of `ElasticsearchFlowStage`.
https://github.com/akka/akka/pull/25951
> Elasticsearch: Make flows type signature simpler to prepare for `withContext`

- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpReplyToSinkStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpRpcFlowStage.scala
- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSinkStage.scala
- geode/src/main/scala/akka/stream/alpakka/geode/impl/stage/GeodeContinuousSourceStage.scala
- geode/src/main/scala/akka/stream/alpakka/geode/impl/stage/GeodeFiniteSourceStage.scala
- geode/src/main/scala/akka/stream/alpakka/geode/impl/stage/GeodeFlowStage.scala
- hbase/src/main/scala/akka/stream/alpakka/hbase/impl/HBaseFlowStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsBrowseStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsProducerStage.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/DiskBuffer.scala
Fixes #1173
Uses the IODispatcher attribute value provided by akka-stream jar, instead of the config path.
> Use IODispatcher attribute

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSink.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSink.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
Introduce a new factory method for Elasticsearch writing that takes and emits tuples so that it can be used with Akka's new `withContext`.
> Elasticsearch: introduce `withContext` flow

- project/Dependencies.scala
A step towards #828
Updates to the latest jwt-core and scalatest which have Scala 2.13.0-M5 artifacts published.
> Update to the latest jwt-core

- dynamodb/src/main/resources/reference.conf
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/DynamoSettings.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
- dynamodb/src/test/java/docs/javadsl/ExampleTest.java
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/DynamoSettingsSpec.scala
Fixes #1542
Allows the `maxOpenRequests` of the underlying host connection pool to
be configured separately from the `maxConnections` value (as specified
by the `parallelism` value in the config).
To preserve old behavior, I made it an optional field, where if it's
absent, then it will use the `parallelism` value as before. However the
one thing I'm not sure of is whether I should have the `Option` exposed
in the public interface (since this is meant to be used in Java as
well). Glad to accept any suggestions on how to handle optional values
like this.
#1542 - Can't specify maxOpenRequests in DynamoClient
> Add maxOpenRequests param in DynamoConfig

- docs/src/main/paradox/overview.md
- project/project-info.conf
* List Scala 2.13 availability
* Fix dead links
> Scala 2.13; links to snapshots page from data-transformations

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
- unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
The binding and connection flows were not living up to their contract whereupon they should be re-usable. This PR fixes that.
The PR has been inspired by the findings of Lunfu Zhong (@zhongl) and his PR: https://github.com/akka/alpakka/pull/1552.
> Lazy source and flow

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/java/docs/javadsl/S3Test.java
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Fixes #1543
Changes the wrapper for the materialized value of the multiPartUpload/multiPartCopy from `Source` to `Future`. This fixed the API inconsistency where the stream needs to be run twice in order for the upload to start.
In #1395 the materialized value was changed from `Future` to `Source` because all of the S3 internals where changed to support blue-print-like-usage of S3 factories. `multiPartUpload/multiPartCopy` use the same machinery for materialized value transformations so the changes propagated here as well. Since the stream is already running when the materialized value is transformed, it is okay to have the `Future` as the wrapper in `multiPartUpload/multiPartCopy` materialized value. In other words, that will not brake the blueprint nature of the stream operators …
> Change mat value to Future in multiPartUpload/Copy

- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Remove `.runWith` in tests which survived after #1556
> AWS S3: Remove left-overs from #1556

- docs/src/main/paradox/mqtt-streaming.md
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/resources/application.conf
- mqtt-streaming/src/test/resources/logback-test.xml
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
Make use of `assertAllStagesStopped` in all tests running streams so that everything is shut down properly.
> Mqtt streaming: assertAllStageStopped

- build.sbt
- project/plugins.sbt
Updates to the updates sbt-site, which correctly uses overriden `Paradox / sourceDirectory` for both `paradox` and `paradoxTheme` settings.
> Fix sourceDirectory for paradoxTheme

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSink.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSource.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSink.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSource.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/settings.scala
- docs/src/main/paradox/cassandra.md
Marks all Alpakka Cassandra APIs as "may change".
We might not be able to rework the API before we publish release candidates and want to be clear about anticipated API changes.
See #1213 and https://github.com/akka/akka-persistence-cassandra/issues/390
> Cassandra: API may change

- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
Updates to the just released akka-grpc 0.6.
Had to drop 2.11 for Google Pub/Sub gRPC because akka-grpc does not support it anymore https://github.com/akka/akka-grpc/issues/520
> Update akka-grpc to 0.6

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
There were a couple of behaviours that were not handling the termination signal where it was possible to receive it. This PR fixes that.
I recommend reviewing without white space changes as the formatter wants to format.
> Termination signal handling

- mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/MqttPerf.scala
- mqtt-streaming-bench/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttPerf.scala
- mqtt-streaming/src/main/mima-filters/1.0-RC1.backwards.excludes
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/MqttSessionSettings.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/Mqtt.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/Mqtt.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
A number of commits here that improve the resilience of the mqtt-streaming connector. #1577 remains important as well, but will require an Akka release.
This allows the MQTT session to better track which events are relevant, given that there can be races when old connections are torn down and new ones are established.
This could cause duplicate publications to never be sent to new connections
Previously, messages for QoS1/2 were only republished on an interval after not receiving an ack.
It is more conventional to instead republish everything only on connect, and indeed to be compliant for MQTT 5, that is the only time this is allowed.
To accommodate this, the timeouts default to 0, but the previous behavior can still be restored by changing the default producer timeout settings.
> mqtt-streaming: Various fixes

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
Server shouldn't stash PUBLISH for uninterested clients
This fixes a memory leak on the server, where when a client disconnects, all PUBLISH messages -- even those that the client hasn't subscribed to -- are stashed.
Instead, if it's a PUBLISH message, we now drop it.
/cc @huntc
> mqtt-streaming: Server shouldn't stash PUBLISH for uninterested clients

- docs/src/main/paradox/examples/mqtt-samples.md
- docs/src/main/paradox/ftp.md
- docs/src/main/paradox/google-fcm.md
- docs/src/main/paradox/release-notes/1.0-M2.md
Fix links into API that has moved and some anchors that changed.
> Fix more links to API docs

- s3/src/main/mima-filters/1.0.x.backwards.excludes
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSize.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/SplitAfterSizeSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Fixes #980 
Split data streams to be uploaded to S3 if the chunk size would exceed the limit of 10 MB.
AWS S3 has a lower and an upper size limit for chunks when uploading data. The lower limit of 5 MB is described in http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html
The upper limit is 10 MB.
> AWS S3: put an upper limit on upload chunks

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
Fixes #1599 
Add missing `TRUNC` mode if `append` is false.
It should overwrite file if exists.
> FTP: fix default sftp overwrite behaviour

- sqs/src/test/java/docs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Trying to improve SQS tests on Travis with different timing.
SQS tests have been failing quite a lot recently, possibly because the timings have changed with the update to AWS client 2.0.
> SQS: try different timing for better test stability

- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
Make FTP tests fail less often.
#1571
> FTP: remove some assertAllStagesStopped

- build.sbt
- docs/src/main/paradox/release-notes/1.0.x/mqtt-streaming.md
Remove Scala 2.11 from cross Scala versions for MQTT streaming.
As MQTT streaming is built on top of Akka Typed which is not published for Scala 2.11 anymore, Alpakka won't publish Scala 2.11 artifacts for this anymore.
> Mqtt streaming: Discontinue Scala 2.11

- project/Dependencies.scala
Upgrade to the latest google-auth-library-oauth2-http version 0.15.0 as the former version pulled in very old other libraries.
> Google Cloud Pub/Sub gRPC: upgrade to google-auth-library-oauth2-http

- build.sbt
Fixed failure from https://travis-ci.com/akka/alpakka/jobs/190295310
Different connectors depend on different guava libraries. When all of the connector dependencies are pulled together, as it is done by unidoc, some of them get into binary incompatibilities. This change filters out the guava library that is causing incompatibility.
> Ignore the latest guava android from the dependencies

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
The MQTT streaming API allows the server to supply a `Promise` when it offers a `SUBACK`. The contract here is that when the `Promise` is completed, it is safe for the server to begin sending `PUBLISH`es as all of the internal machinery is ready.
However, due to a race condition, `PUBLISH` commands sent in response to this `Promise` being completed could arrive before the server's `ClientConnection` has messaged itself the `Subscribed` instance. If this happens, the `PUBLISH` is ignored.
This introduces another promise that the `ClientConnection` is responsible for completing when it receives the `Subscribe` message in response. It then completes this `Promise`, which in turn completes the user's supplied `Promise`, thus eliminating the race and ensuring that
`PUBLISH`es are not ignored. …
> mqtt-streaming: Fix a race condition in server publishing

- build.sbt
- project/Dependencies.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
Build sqs and sns connectors with Scala 2.13.0-M5.
Aws Spi Akka Http was released for Scala 2.13.0-M5 recently: https://github.com/matsluni/aws-spi-akka-http/issues/3#issuecomment-481664687
Fixes #1537 and #1538
> Enable 2.13 for sqs and sns connectors.

- scripts/buildChanged.sh
Comparing against `origin/master` when building master is incorrect. This PR adds a check to `buildChanged.sh` where when building master, it looks for differences against `HEAD^`.
> Compare against previous state of master when building master

- scripts/buildChanged.sh
After the `buildChanged.sh` improvements (#1650), the master branch build still went of to compare against `origin/master` instead of `HEAD^`. This tries to use more explicit bash syntax in the conditional.
> Try to fix bash script if condition

- xml/src/main/scala/akka/stream/alpakka/xml/impl/StreamingXmlWriter.scala
- xml/src/test/scala/docs/scaladsl/XmlWritingSpec.scala
This does not appear to be strictly necessary when producing full documents,
but does make a difference when outputting 'snippets'.
> xml: flush output after the input is finished

- project/Dependencies.scala
Reverts akka/alpakka#1640 as we should not update dependency minor versions in a patch release.
> Revert "Upgrade cassandra driver to 3.7.1"

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/CommonFtpStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpBaseSupport.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
This PR is about making `Ftp.ls` emit directories it encounters no matter if they were traversed or not.
The previous behavior being that you only get directories that were not entered, which is unexpected.
References #1657
`FtpGraphStageLogic` keeps a record of traversed directories and emit them first on pull.
For instance the path `/foo/bar/sample` will result in the emission of three `FtpFile`, one for `foo`, one for `bar`, and one for `sample`, in that order.
Additionally, the test-related class `FtpBaseSupport` had to be fixed to remove empty directories when cleaning files, and tests have been reviewed to match the new behavior of `listFiles`.
> FTP: emit traversed directories from Ftp.ls

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
Align LocalDate.now() function in S3Stream.scala's signing key with UTC. This is because the credential scope in AWS should be in UTC.
* Align LocalDate.now() to be LocalDate.now(UTC)
AWS is expecting UTC time zone for credential scope.
> Align local date in s3 stream signing key to UTC

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/StrictHostCheckingSftpSourceTest.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
This PR makes it possible to download a file partially (from an offset) with `FTP.fromPath`
References #1660 
I found it hard to maintain binary compatibility while implementing this. I couldn't add a parameter or a method to the `FtpLike` trait even though it's an internal API and it's protected (is that even related to binary compatibility?), so I added a new trait called `RetrieveOffset` mixed in all the FtpLike instances.
Also `FtpApi` defines a default chunksize parameter to `fromPath` and I couldn't add another parameter to that mehod nor add another method with default parameters, so anyone wanting to define an offset will have to manually specify the chunksize (defaults to 8192).
Eg.: `Ftp.fromPath(path, settings, 8192, offset)`
Two tests were added.
> FTP: support partial file download

- couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseClusterRegistry.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSession.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSession.scala
- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSessionExamplesSpec.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSourceSpec.scala
- docs/src/main/paradox/couchbase.md
Cache Couchbase `AsyncCluster` independently of `Buckets` in `CouchbaseSessionRegistry` so that they are shared when more than one bucket is used.
See #1676 
* Introduce internal `CouchbaseClusterRegistry` to cache `AsyncCluster` instances per `CouchbaseSessionSettings`
* Add example using the `CouchbaseSessionRegistry` to documentation
> Couchbase: reuse `AsyncCluster` via registry

- project/Dependencies.scala
This PR updates the dependency `aws-spi-akka-http` to version `0.0.6`. This includes a fix for #1665.
References #1665
> SQS/SNS: Update aws-spi-akka-http to version 0.0.6

- docs/src/main/paradox/s3.md
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/java/docs/javadsl/S3Test.java
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
- s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
Fixes #1546 
Regarding the issue that i posted i've created some bucket management functionality. It allows end user to create, delete and check if bucket of a given name exists.
As for now the docs created by AWS doesn't specify a request to list all buckets so that functionality was not implemented.
I'd be glad if someone would check whether the naming in the enum is understandable for others and is there any better solution to have the same request but with different mapping functions (i am talking about explicitly passing this implicit in S3Stream to processing functions)?
> S3: Bucket management

- s3/src/main/mima-filters/1.0.0.backwards.excludes
- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ExtSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Akka HTTP has support for forward proxies via its [Pluggable Client Transports](https://doc.akka.io/docs/akka-http/current/client-side/client-transport.html). The functionality is used in this update in order to support forward proxies when integrating with S3.
References #1017
> AWS  S3 - forward proxy support

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/Signer.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/SigningKey.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SignerSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SigningKeySpec.scala
During AWS request signing the request timestamp and the date in the signed authorization credential should denote the same date, so they should be constructed from a single timestamp.
This is a follow-up to #1678 
* Add `ZonedDateTime` to `SigningKey`
* Dirive date in `CredentialScope` from the request date in `SigningKey`
* unrelated: add missing (but impossible) match case in `processCheckIfExistsResponse`
> AWS S3: use a single date/time for signing

- build.sbt
- csv-bench/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvBench.scala
- csv/src/main/mima-filters/1.0.x.backwards.excludes
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
Improves parsing speed of alpakka-csv from 1.5 MiB/s to 78 MiB/s for the most extreme case.
I searched, but didn't find any other issues or discussions.
* New jmh benchmark: `CsvBench`
* `CsvParser` is faster.
While evaluating alpakka-csv as a non-blocking replacement for our currently blocking usage of OpenCSV, I benched it and found that it parses slower than I'd expect, even over benchmarks that play to alpakka-csv's strengths. After poking around, I found some slow spots and optimized them.
```
[info] Benchmark       (bsSize)   Mode  Cnt    Score   Error  Units
[info] CsvBench.parse        32  thrpt   10    1.551 ± 0.028  ops/s
[info] CsvBench.parse      1024  thrpt   10   60.279 ± 0.720  ops/s
[info] CsvBench.parse      8192  thrpt   10  117.125 ± 1.138  ops/s
[info] CsvBench.parse …
```
> Add alpakka-csv benchmark and optimize.

- project/Dependencies.scala
Otherwise coursier fails to resolve dependencies.
> Sync grpc version to the one that comes from akka-grpc

- docs/src/main/paradox/sqs.md
- sqs/src/main/mima-filters/1.0.x.backwards.excludes
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/java/docs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Make the number of parallel requests issued by `SqsSource` configurable. Use 1 as default. 
References #1605 
* Set the parallelism for AWS client fetching via `SqsSourceSettings` (which fetches up to `maxBatchSize` messages)
* cleanup: limit all `CompletionStage.get` calls with a finite duration
As discussed in https://github.com/akka/alpakka/issues/1665#issuecomment-491521609 the higher parallelism could help to fill the buffer when starting up. (See even https://github.com/akka/alpakka/issues/1588#issuecomment-476105607 for the original discussion).
The `buffer` operator in `SqsSource` makes sure more data is fetched eagerly, even if the stream back-pressures, but does not buffer data as long there is down-stream demand ([buffer …
> SQS source: make parallelism configurable

- build.sbt
- docs/src/main/paradox/sns.md
- docs/src/main/paradox/sqs.md
- sns/src/test/java/docs/javadsl/SnsPublisherTest.java
- sns/src/test/scala/akka/stream/alpakka/sns/IntegrationTestContext.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceSettings.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
- sqs/src/test/java/docs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Akka HTTP is injected to the AWS client via reflection. This use creates another actor system internally.
I learned this via #1693
See https://github.com/matsluni/aws-spi-akka-http/issues/7
* show explicit `AkkaHttpClient` use so that the actor system is reused
* document the use of Netty as another option
> AWS SQS/SNS: more concise docs about the HTTP client

- doc-examples/src/main/java/elastic/KafkaToElasticInJava.java
- doc-examples/src/main/java/ftpsamples/FtpToFileExample.java
- doc-examples/src/main/resources/logback.xml
- doc-examples/src/main/scala/elastic/KafkaToElastic.scala
- docs/src/main/paradox/examples/elasticsearch-samples.md
- project/Dependencies.scala
Add a new self-contained example which reads messages from a Kafka topic and writes these to Elasticsearch.
Make use of the new `withContext` API in Akka Streams.
Use [Testcontainers](https://www.testcontainers.org/) to start Kafka and Elasticsearch.
> Read from Kafka write to Elasticsearch example

- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
Fix bug: LogRotatorSink does not terminate when consuming an empty Source
[Related bug report](https://github.com/akka/alpakka/issues/1701)
- Complete the stage's promise when`onUpstreamFinish` is called
I signed the CLA
> Fix: LogRotatorSink does not complete when consuming an empty source

- docs/src/main/paradox/sqs.md
- sqs/src/main/mima-filters/1.0.0.backwards.excludes
- sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala
- sqs/src/test/java/docs/javadsl/SqsAckTest.java
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/SqsModelSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
Fixes #625
Improve SQS batch operations
After the AWS SDK update, changes in the AWS models can make the API simpler and cleaner:
- No need to propagate FifoIdentifiers anymore
- Separation between request metadata (HTTP request info) and content metadata
> SQS: Revise stream element data model

- docs/src/main/paradox/sqs.md
The links to Scaladoc didn't get updated in a late rename in #1604.
> AWS Sqs: fix Scaladoc links after rename

- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
The CSV optimisations in #1685 changed the parsing behaviour for streams ending with an empty column, this brings back the expected behaviour.
Optimisation work in #1685 
Reported as bug in #1710
> CSV: stream may end with delimiter

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala
Fixes the issue wherein setting tls=true in DynamoSettings overwrites the configured port to 443
References #1662 
Passed port to Http().cachedHostConnectionPoolHttps
> DynamoDb: set port from settings even when tls=true

- dynamodb/src/main/resources/reference.conf
By defaulting to port 443 in `reference.conf` this makes #1722 work backwards-compatible.
As `tls` was enabled by default, with just #1722 the code would try to connect to port `-1`. By making port `443` the default everything should work as previously.
> DynamoDb: set 443 as default port

- .travis.yml
- build.sbt
- project/plugins.sbt
Updates to the latest sbt-site
~This uses not yet released sbt-site feature from https://github.com/sbt/sbt-site/pull/148~
`Paradox` configuration scope is not needed anymore when using sbt-site with Paradox.
> Update to the latest sbt-site

- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- csv/src/test/java/docs/javadsl/CsvFormattingTest.java
- csv/src/test/java/docs/javadsl/CsvParsingTest.java
- csv/src/test/java/docs/javadsl/CsvToMapTest.java
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvFormattingSpec.scala
- docs/src/main/paradox/data-transformations/csv.md
Accept an escape byte (eg `\`) in the input which is not followed by an escapeable byte (escape (`\`) or delimiter (`,`)) and add the escape byte itself to the parsed column.
It still fails if escape is followed by quote (eg. `\"`).
#1643
> CSV: accept escape without escapeable byte after

- build.sbt
- docs/src/main/paradox/amqp.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/data-transformations/compression.md
- docs/src/main/paradox/data-transformations/json.md
- docs/src/main/paradox/data-transformations/parsing-lines.md
- docs/src/main/paradox/examples/csv-samples.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/overview.md
- docs/src/main/paradox/patterns.md
- docs/src/main/paradox/sns.md
- docs/src/main/paradox/sqs.md
* Change extref names `akka-docs` to `akka` and `akka-http-docs` to `akka-http`.
* Fix port in links for `previewSite`
* Sort extref/scaladoc/javadoc links differently
* Point scala Scaladoc to `scalaBinaryVersion`.x
> Standardise extref names

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
- s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Moves FailedUpload exception to the user facing API
Fixes #1706
* makes the `FailedUpload` exception public
* adds a test that mocks a failure after the initial request succeeds
> S3: Move FailedUpload exception to the user facing API

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequest.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/Signer.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequestSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SignerSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Fixes issue with using `+` char in a S3 object key
https://github.com/akka/alpakka/issues/838 S3 Connector - Using `+` (plus) symbol causes mismatched request signature
- HttpRequests adds a synthetic akka http header `Raw-Request-URI` to the built request. The header contains stringified uri of a request with all `+` characters replaced with the url-encoded representation `%2B`.
- Signer now ignores a synthetic akka http header `Raw-Request-URI`.
> AWS S3: Fix plus char usage in s3 key

- s3/src/main/scala/akka/stream/alpakka/s3/S3Exception.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Right now, when alpakka receives an empty message it throws S3Exception but doesn't include any clue for the user on how to fix it. As all communication with S3 is just standard Http alpakka has the response code but ignores it before calling S3Exception's constructor.
Purpose of this PR is to include more information in exception message
References #1589
Added a response code to exception's constructor to later be displayed for the user.
> S3: Empty exception issue #1589

- .travis.yml
- CONTRIBUTING.md
Explain the use of MiMa in contributing.md
#1750
> Explain MiMa use for contributors

- project/Dependencies.scala
As Alpakka SNS and SQS use Akka HTTP via aws-spi-akka-http, the Apache HTTP client can be excluded from the dependencies brought in by the AWS SDK 2.
https://github.com/akka/alpakka/pull/1695
https://github.com/matsluni/aws-spi-akka-http/issues/11
* Add another exclusion to the AWS SDK dependency for SNS and SQS
* Format the exclusions for easier reading
* Depend on Jackson Databind 2.9.9 to avoid a security issue
> AWS SNS and SQS: Apache HTTP client is not used

- elasticsearch/src/main/mima-filters/1.0.2.backwards.excludes
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
Replace the raw tuple-based "with context" implementation with the new types from Akka 2.5.23.
See #1713
> Elasticsearch: use proper FlowWithContext

- docs/src/main/paradox/awslambda.md
- docs/src/main/paradox/other-docs/webinars-presentations-articles.md
- docs/src/main/paradox/release-notes/1.0-M2.md
It has been pointed out that we used to have an inconsistent spelling of "connector". This changes the last remainders.
> Nitpick: lower-case connector

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
Create AmqpDetailsConnectionProvider with multiple hosts and ports
> AMQ: multiple hosts in AmqpDetailsConnectionProvider

- .scalafmt.conf
- project/plugins.sbt
Switches to the latest scalafmt
Latest scalafmt has a fix (https://github.com/scalameta/scalafmt/pull/1384) for concurrent scalafmt artifact downloads. Without the fix, scalafmt might fail, if the artifacts have not been downloaded yet.
> Use latest scalafmt

- docs/src/main/paradox/release-notes/1.0.x/csv.md
Remove extra char breaking the link address.
> Fix link in CSV release notes

- .travis.yml
So the scalafmt artifacts are cached.
> Cache coursier data directory

- google-cloud-storage/src/test/resources/application.conf
When trying to setup an example using the documentation I was getting an error of not having proper configuration. The problem was that for defaults if you look at https://github.com/akka/alpakka/blob/master/google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageSettings.scala#L95 it has the proposed change in this PR.
> Google Cloud Storage: application.conf path for config

- couchbase/src/main/java/akka/stream/alpakka/couchbase/javadsl/DiscoverySupport.java
- couchbase/src/main/mima-filters/1.0.2.backwards.excludes
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/DiscoverySupport.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/model.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSession.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/DiscoverySupport.scala
- couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
- couchbase/src/test/resources/application.conf
- couchbase/src/test/resources/discovery.conf
- couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
- couchbase/src/test/scala/docs/scaladsl/DiscoverySpec.scala
- docs/src/main/paradox/couchbase.md
- project/Dependencies.scala
Add support for use of Akka Discovery to configure Couchbase nodes.
* Add `enrichAsync` to `CouchbaseSessionSettings`
* Apply `enrichAsync` before using settings
* Test case with `DiscoverySupport` usage
* Documentation
> Couchbase: Akka Discovery support

- docker-compose.yml
Use the new pre-packaged native image of ElastiMQ for faster startup.
https://github.com/softwaremill/elasticmq/#experimental-native-elasticqmq-via-docker
> SQS: test against ElasticMQ native image

- sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
- sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
Support gzip responses out of the box
References #1356 
SSE Source
Based on previous test
> SSE: Support gzip encoding

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala
- google-cloud-pub-sub/src/test/java/docs/javadsl/ExampleUsageJava.java
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-cloud-pub-sub/src/test/scala/docs/scaladsl/ExampleUsage.scala
Nor should be 'messageId' be required when creating PubSubMessage for publishing.
Improve Scala and Java API - don't require redundant parameter
Improve compliance with Google Cloud PubSub HTTP API - don't send fields that shouldn't be sent.
References #1786
* Added Scala and Java api that doesn't require 'messageId'
* Do not encode 'messageId' and 'publishTime' when sending JSON body
I wanted to create separate case class for publishing PubSub message but I went in a direction to not break code.
If for 1.1 we can break source and binary compatibility, I'd like to contribute other change.
> Issue 1786 - 'messageId' and 'publishTime' should not be published

- mqtt/src/test/java/docs/javadsl/MqttFlowTest.java
- project/Dependencies.scala
When in nightly, build with Akka 2.6.
When in nightly:
* switches Akka to the latest mileston
* drops 2.11 cross Scala version
> Nightly with Akka 2.6

- docs/src/main/paradox/jms/consumer.md
- jms/src/main/mima-filters/1.0.2.backwards.excludes
- jms/src/main/scala/akka/stream/alpakka/jms/Destinations.scala
- jms/src/main/scala/akka/stream/alpakka/jms/Headers.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsMessageProducer.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsMessageReader.scala
- jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsBufferedAckConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsConnectorsTest.java
- jms/src/test/java/docs/javadsl/JmsTxConnectorsTest.java
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
This makes it easy to get the Alpakka `JmsMessage`s with the body, all headers, and all JMS properties intact.
This is a first pass, I only have so much time to work on this so wanted to get some discussion before going any further with anything else that will be required.
`JmsProducer` requires Alpakka `JmsMessage` model objects to produce messages in a flow (or plain body objects with no headers in a sink). While implementing a standard request/reply model, I found there was no automatic way to convert a `jms.Message` to a `JmsMessage` while keeping headers & properties intact (need fields such as `correlationId` and `replyTo` from the original message).
I added the missing standard JMS headers in `JmsHeader`, and added conversions from `jms.[Map|Text|Bytes|Object]Message` to their …
> WIP Add conversion functions to get JmsMessages from jms.Messages

- udp/src/main/scala/akka/stream/alpakka/udp/model.scala
Adds conventional Java API getters to `Datagram`.
Fixes #1768
> Add java getter to Datagram

- build.sbt
Switch off Scala 2.11 compilation for Google Cloud Storage.
New connectors should not support outdated Scala versions.
> Google Cloud Storage: don't publish for Scala 2.11

- project/Common.scala
Remove doubled slash in canonical URLs in Paradox generated docs.
The `homepage` URL gets promoted to Paradox to be used as the base for canonical URLs. The Akka Paradox template introduces an extra slash which makes the URLs included two slashes and Google doesn't seem to like that.
> Canonical URL fix

- build.sbt
Enables MiMa on new connectors since 1.1.0.
Fixes #1773 and #1790
> Enable MiMa on Google Cloud Storage and InfluxDb

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/QueueOfferState.scala
- project/Dependencies.scala
Keeps nightlies in sync with the latest Akka release.
> Update to the latest Akka 2.6-M4

- project/Dependencies.scala
Updates to the latest Akka milestone 2.6.0-RC5 for the nightly runs.
> Update to Akka 2.6.0-M5

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/QueueOfferState.scala
Hi! With the changes made in #1818, we're seeing an issue with the MQTT connector. Reverting the 1 line change fixes it. I don't know what the semantics of `Behavior.interpretSignal` are but the change is causing the following:
```
2019-07-17T22:13:18.792Z [22:13:18.792UTC] 127.0.0.1 com.cisco.streambed.durablequeue.remote ERROR ActorAdapter - deferred [Deferred(TimerSchedulerImpl.scala:28)] should not be passed to interpreter
java.lang.IllegalArgumentException: deferred [Deferred(TimerSchedulerImpl.scala:28)] should not be passed to interpreter
at akka.actor.typed.Behavior$.interpret(Behavior.scala:422)
at akka.actor.typed.Behavior$.interpretSignal(Behavior.scala:399)
at akka.stream.alpakka.mqtt.streaming.impl.QueueOfferState$$anonfun$waitForQueueOfferCompleted$3.applyOrElse(QueueOfferSta …
```
> mqtt-streaming: Partially revert #1818

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
Spawns MQTT connector actors as system actors, so the connector can be used with typed system that enforces a single guardian.
Fixes #1836
This PR duplicates code from
https://github.com/akka/akka/blob/89e269d5d89b78ba950af9cbcef49e6b38a335b4/akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/ActorSystemAdapter.scala#L114-L1187
without wrapping the `ActorRef` to a `Future`.
> Spawn MQTT connector actors as system actors

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
- mqtt/src/test/travis/acl
Removes common clinetId/topic from typed/untyped MqttFlowSpec so both of the specs can run independently.
Follow up after #1848
> Make typed/untyped MqttFlowSpec independent

- scripts/buildChanged.sh
`buildChanged.sh` should build modules even with no changes when the Travis job is a nightly.
Fixes #1850
> Build all connectors when building in nightly

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttCodecSpec.scala
Prior to this PR, a failure to attain a QoS level when subscribing to a topic was considered bad. The spec treats this condition as one being something for the application to handle e.g. a client can decide to proceed or not given that one of the topics being subscribed fails or not.
The fix is to deprecate the `BadSubAckMessage` and always return `SubAck`. This then permits the `Subscriber` to process `SubAck`s whether they are good or bad from the application's perspective.
Fixes #https://github.com/akka/alpakka/issues/1833#issuecomment-515437102
> Failure to attain QoS is not bad

- doc-examples/src/main/java/ftpsamples/RotateLogsToFtpExample.java
- docs/src/main/paradox/examples/ftp-samples.md
This commit migrates the file `RotateLogsToFtp.scala` a new file `RotateLogsToFtpExample.java` as requested in https://github.com/akka/alpakka/issues/1479
https://doc.akka.io/docs/alpakka/current/examples/ftp-samples.html
https://github.com/akka/alpakka/issues/1479
Adds the file `RotateLogsToFtpExample.java`
> Ftp: migrates RotateLogsToFtp to Java #1479

- hdfs/src/main/mima-filters/1.1.x.backwards.excludes
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/CompressedDataWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/DataWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/HdfsWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/writer/SequenceWriter.scala
- hdfs/src/main/scala/akka/stream/alpakka/hdfs/scaladsl/HdfsFlow.scala
- hdfs/src/test/scala/docs/scaladsl/HdfsWriterSpec.scala
Fixes https://github.com/akka/alpakka/issues/1761
Overwrite HDFS target file when the `overwrite` setting is set to true.
* propagated overwrite information to HdfsWriter base trait
* deleted existing file if overwrite is enabled in HdfsWriter#moveToTarget function
This is the most simple fix I could come up with but there are still some issues with the code imho:
* First the result of the `moveToTarget` operation is ignored at https://github.com/akka/alpakka/blob/master/hdfs/src/main/scala/akka/stream/alpakka/hdfs/impl/HdfsFlowStage.scala#L144 . This results in silent errors which lead to the original issue. What would be the best approach to handle errors here?
* Secondly, `org.apache.hadoop.fs.FileSystem` does not provide a `rename` function that can take an overwrite flag or option. …
> HDFS: fix target file overwrite

- docs/src/main/paradox/ftp.md
- ftp/src/main/mima-filters/1.1.x.backwards.excludes
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpBrowserGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpDirectoryOperationsGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/java/docs/javadsl/FtpMkdirExample.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
- ftp/src/test/scala/docs/scaladsl/scalaExamples.scala
PR introduces an ability to create a directory
- Some refactoring to the way that specific GraphStage-s are created. Common methods (not related specifically to the Graph were moved higher)
- Introduced another Graph Stage, that is responsible for directory operation. For now, it is only creating action but this can be expanded to deleting using a sealed trait and matching type in Graph Stage's method `onPull`.
For now alpakka lacks asych API to create a bucket and it is necessary for our application to have one. I've done something similar that is in S3 module, where create bucket has 2 versions: one materialized (future / completion stage) and other not materialized (source). Since both api-s doesn't return anything after successfully creating bucket or directory, I've used the same …
> FTP: Mkdir

- build.sbt
Use the `interalProject` setup for the reference connector to not check Mima for it.
#1860
#1860 enabled Mima for the reference connector which isn't published, so it doesn't work.
> Mima: don't check reference connector, as it is not published

- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- csv/src/test/resources/correctness.csv
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- csv/src/test/scala/docs/scaladsl/CsvParsingSpec.scala
Allow quotes to end mid-column (those quotes disappear in output).
Reported in #1835 
The Alpakka CSV parser was strict on the second quote of a quoted column to end it. Instead, it now reads on as if the field wasn't quoted in the first place.
> CSV: accept quotes ending mid-column

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/QueueOfferState.scala
`Behavior.orElse`, that was removed used to be implemented with `Behavior.interpretSignal` and `Behavior.start`.
https://github.com/akka/akka/pull/27252/files#diff-a0594f18c52ddedf689c54c7907f25ddL170
Previous attempt (#1818) was missing a `Behavior.start`.
Fixes nightly builds after #1832
> Start deferred behaviors

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/WriteMessage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/test/java/docs/javadsl/ElasticsearchTest.java
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
Document (Scala) and enable (Java) how to use properly formatted JSON documents without Spray or Jackson.
Implements #1825 
* Provide predefined `StringMessageWriter`
* Allow passing `MessageWriter` in the Java API
* Add sample use for Scala and Java
#1825 asked for this support, which was available with the Scala DSL, but not the Java DSL.
> Elasticsearch: store JSON strings

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoProtocol.scala
TransactionCanceledException was not previously parsable, resulting in
generic AmazonDynamoDBExceptions being returned with no ability
for users to extract specifics as to why the transaction has been
canceled.
References #1847 
* Introduced a new shape capable of parsing `TransactionCanceledException`s.
Given this update was so trivial, I feel there was no other approach that can be justified.
`TransactionCanceledException` was simply not added when transaction support was originally introduced.
> DynamoDB: Add TransactionCanceledException

- jms/src/main/mima-filters/1.1.1.backwards.excludes
- jms/src/main/resources/reference.conf
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsTxSourceStage.scala
- jms/src/test/scala/docs/scaladsl/JmsTxConnectorsSpec.scala
Let the user notice when a transaction gets rolled back because `ack-timeout` was hit.
Implements #1855 
See #1831 
* Log warning or fail the stream when the commit future isn't completed within `ack-timeout`
* Introduce setting `fail-stream-on-ack-timeout` to let the user opt-in to let the stream fail
It might seem natural to fail the promise in `TxEnvelope` so that `commit` and `rollback` would fail with "Promise already completed" when an ACK timeout occurred. This behaviour could be desirable but is not backwards compatible for scenarios that handle duplicated messages today. cc @andreas-schroeder
>  JMS transactions: fail stream or log on ack timeouts 

- build.sbt
Exclude a conflicting version during the unidoc task to avoid compilation errors due to classpath order.
> Scaladoc: exclude jwt-core 3.0.1 during unidoc

- project/plugins.sbt
Make use of the latest Scalafmt sbt plugin.
> Scalafmt: update plugin to 2.0.3

- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
- project/Dependencies.scala
Updates the versions of the following dependencies so to avoid conflicts with more recent versions of pubsub api. 
```
"com.google.api.grpc;grpc-google-cloud-pubsub-v1;1.61.0;protobuf", 
"io.grpc;grpc-auth;1.21.0",
"com.google.auth;google-auth-library-oauth2-http;0.16.1"
```
While developing a component that integrates with pubsub we tried using the latest version of it's apis but this caused a conflict with alpakka's version of the pubsub apis which where very obsolete. 
For good measure we also updated the other related components which only had minor version changes.
> Updated google pubsub grpc deps to latest version

- build.sbt
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApiSpec.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleTokenApiSpec.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApi.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApiSpec.scala
- project/Dependencies.scala
fixes #1811 and enable scala 2.13 cross build for all google modules
fixes #1762
fixes #1763
As jwt-core 2 and 3 are not compatible this is a breaking change
to continue the cleanup see #773
> sync google modules jwt-core version

- file/src/main/java/akka/stream/alpakka/file/impl/FileTailSource.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/FileTailSource.java
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
Akka 2.6 changes what exception is being thrown in case of FileIO failure. This PR adapts the testcase to expect a correct exception.
> Expect correct exception in Akka 2.6

- build.sbt
Enables Scala 2.13 build for Google Cloud Pub/Sub gRPC connector
Fixes #1533
> Enable Scala 2.13 build for Google Cloud Pub/Sub gRPC connector

- build.sbt
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/javadsl/MongoFlow.scala
- project/Dependencies.scala
Enables Scala 2.13 build for the MongoDb connector.
Fixes #1535
> Update to Scala 2.13 supported MongoDb dependencies

- couchbase/src/main/mima-filters/1.1.1.backwards.excludes
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionImpl.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionJavaAdapter.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSession.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSink.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSession.scala
- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseFlowSpec.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSourceSpec.scala
- docs/src/main/paradox/couchbase.md
The Couchebase API provides replace (Replace a Document if it does already exist.). This was not implemented in Alpakka Couchbase before.
References #1884
* Added `replace` implementation
* Added tests
* I've tried to follow the `upsert` implementation for `replace`
* I've added `bucketName` to `upsertSampleData` because you need documents in Couchbase for `replace` to work
* I've added assertions in `CouchbaseExamplesTest.java` to the `upsert` tests as well
* I've rearranged `CouchbaseFlowSpec` because there were `delete` tests under `upsert` which was confusing
> COUCHBASE: Add bucket replace functionality

- project/Common.scala
Disables fatal warnings when CI is running a nightly build. Fatal warnings are still enabled in PR builds and regular master builds.
Alpakka nightly builds switch to the latest milestone of Akka 2.6. Some of the APIs in the 2.6 milestones are deprecated which prevents running nightly builds with fatal warnings.
> Do not enable fatal warnings on nightly

- docker-compose.yml
- project/Dependencies.scala
This change is to upgrade Apache HBase to 1.4.9, which is the current stable version.
This PR changed an HBase docker image to run tests using HBase 1.4.
> HBase: version 1.4.9

- .travis.yml
- build.sbt
- ftp/src/main/mima-filters/1.1.x.backwards.excludes
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
- mqtt/src/main/scala/akka/stream/alpakka/mqtt/settings.scala
- project/Dependencies.scala
Allow publishing Alpakka FTP for Scala 2.13, and using Scala 2.12.9 for compilation.
Issue #1532 
Using Scala 2.12.8 hits https://github.com/scala/bug/issues/11305
Scala 2.13.0 does not compile the Java tests successfully which looks like the same problem of missing type signatures.
Due to the changed handling of static forwarders in Scala 2.12.8+ the pattern used to implement the different FTP styles doesn't compile anymore. 
* Make `FtpApi` just an interface
* Move type member to type parameter in `FtpApi`
* Repeat implementations of the operations in every FTP style
> FTP: enable Scala 2.13 and 2.12.9 compilation

- build.sbt
- project/Common.scala
* Use new Scaladoc flags from Scala 2.12.9.
* Remove hack to get correct links to Java sources.
> Scaladoc: link to source and canonical

- .scalafmt.conf
- project/plugins.sbt
Upgrades to the latest scalafmt formatter and sbt plugin.
https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.0.4
https://github.com/scalameta/scalafmt/releases/tag/v2.0.1
> Upgrade to scalafmt 2.0.1 / sbt-scalafmt 2.0.4

- .travis.yml
- build.sbt
- docker-compose.yml
- docs/src/main/paradox/ftp.md
- ftp/src/main/mima-filters/1.1.1.backwards.excludes
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpWithProxyStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsWithProxyStageTest.java
- ftp/src/test/java/akka/stream/alpakka/ftp/SftpWithProxyStageTest.java
- ftp/src/test/resources/squid.conf
- project/Dependencies.scala
Adds proxy support to FTP, SFTP, and FTPS connectors
References #600
* Add `withProxy` method on all three FTPSettings builders that takes a `java.net.Proxy` object
* Pass the proxy object to the underlying client before the connection is made
* Added tests for the three supported protocols via a proxy
* Added squid proxy and configuration to docker-compose so this can be tested. 
The approach is relatively straight forward. The extra option fits neatly into to existing builder pattern and passing the proxy to the client at the start of the connect operation is the natural place for it to go. 
I've chosen to use a squid proxy in the testing as this is a widely used proxy.
> FTP - Add proxy support to FTP, SFTP, and FTPS connectors

- docs/src/main/paradox/s3.md
- project/Dependencies.scala
- project/build.properties
- s3/src/main/mima-filters/1.1.x.backwards.excludes
- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/headers/ServerSideEncryption.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/SigningKey.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/S3StreamSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SignerSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SigningKeySpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
- s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
Upgrades S3 connector to use AWS SDK 2.
Fixes #1342
Credentials, Region and some utility AWS classes have been migrated to AWS SDK 2. All of the other machinery is implemented directly using akka-http and akka-stream.
Test verifying credential refresh functionality has been removed, as refreshing credentials is no longer supported.
https://docs.amazonaws.cn/en_us/sdk-for-java/v2/migration-guide/client-credential.html#credentials-changes-mapping
> Migrate S3 connector to AWS SDK 2

- docs/src/main/paradox/dynamodb.md
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/javadsl/RetryFlow.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/scaladsl/RetryFlow.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoDb.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoDb.scala
- dynamodb/src/test/java/docs/javadsl/ExampleTest.java
- dynamodb/src/test/java/docs/javadsl/RetryTest.java
- dynamodb/src/test/resources/application.conf
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TestOps.scala
- dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
- dynamodb/src/test/scala/docs/scaladsl/RetrySpec.scala
*This is a continuation of #1876. ~Built on top of #1725 and therefore Draft until it gets merged~*
Adds a `DynamoDb.tryFlow` of the shape `Req => Try[Resp]`. This allows composition with a RetryFlow (https://github.com/akka/akka/pull/27461).
To let the tests pass, RetryFlow is now included verbatim in this PR.
Supersedes https://github.com/akka/alpakka/pull/1712
Fixes #1682
> DynamoDb: AWS SDK2; Add tryFlow to be used with RetryFlow

- docs/src/main/paradox/s3.md
Fixes a typo in the S3 documentation.
https://doc.akka.io/docs/alpakka/current/s3.html
> S3 docs: Fix typo

- build.sbt
- project/Dependencies.scala
Make Alpakka HDFS build with Scala 2.13 by upgrading cats-core to the binary compatible 2.0.0 release.
#1764
> HDFS: upgrade Cats to 2.0.0 and enable Scala 2.13

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
Changes behavior for pull subscribe stream.
Before: error responses were successfully Unmarshalled to empty PullResponse, giving no signal that errors occurred.
That was because Google PubSub error response bodies are valid JSON messages and PullResponse contains only one optional field.
After: when status code for pull request is not 200 OK, then source will fail with exception that contain no OK response status.
References #1902
I've used technique similar to current handling of failed publish requests.
> Google Pub/Sub: Fail source when pull status code is not 200 OK

- docs/src/main/paradox/influxdb.md
The documentation at https://doc.akka.io/docs/alpakka/current/influxdb.html renders the artifact name as `akka-stream-alpakka-influxdb2.12`. This should of course be `akka-stream-alpakka-influxdb_2.12` for Maven and Gradle, and just `akka-stream-alpakka-influxdb` for sbt.
I checked other Alpakka projects that do get it right, and the only difference appears to be the missing underscore.
> InfluxDB docs: fix artifact name for sbt, Maven and Gradle

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchJsonBase.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
This PR introduces a simple flow stage implementation without retrying.
See RetryFlow in https://github.com/akka/akka/pull/27742
DynamoDB retrying https://github.com/akka/alpakka/pull/1712
* Introduce `ElasticsearchJsonBase`
* Add `ElasticsearchSimpleFlowStage`
* Rework the `javadsl` factory methods to use `scaladsl` implementations
* Rework the factory methods to choose stage depending on the retry settings
The Elasticsearch flow stage implementation is more involved than needed, as it contains retrying logic. I work on implementing generic retrying flows so that these concerns can be abstracted over in https://github.com/akka/akka/pull/27742
> Elasticsearch: refactor to make retrying more explicit

- xml/src/main/scala/akka/stream/alpakka/xml/impl/StreamingXmlWriter.scala
- xml/src/main/scala/akka/stream/alpakka/xml/javadsl/XmlWriting.scala
- xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlWriting.scala
- xml/src/test/java/docs/javadsl/XmlWritingTest.java
- xml/src/test/scala/docs/scaladsl/XmlWritingSpec.scala
add ability to provide a specific XMLOutputFactory when instantiating an Xml Writer
References #1936
> XML: add ability to provide a specific XMLOutputFactory

- file/src/test/java/docs/javadsl/ArchiveHelper.java
- file/src/test/java/docs/javadsl/ArchiveTest.java
Make stable "ArchiveTest.java" test.
References #1909
Instead of reading files multiple times in test. Now files are kept in memory. 
After checking the test I decided to give a try different solution than proposed in the issue.
I suspect, something was accessing files, while the tests were running and file metadata has changed before creating reference zip. After this change, files are read from disk only once and reused for both methods of creation ZIP.
> Files: used in ArchiveTest.java are now read only once

- .travis.yml
The former JDK 8 version became invalid for use with Jabba.
> CI: update Adopt Open JDK versions

- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceFlowStage.scala
- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceSourceStage.scala
- reference/src/main/scala/akka/stream/alpakka/reference/impl/ReferenceWithResourceFlowStage.scala
- reference/src/main/scala/akka/stream/alpakka/reference/scaladsl/Reference.scala
Align the reference connector with the naming most connectors use.
As @kstrek pointed out in https://github.com/akka/alpakka/pull/1921#discussion_r328295990, the reference connector did not append `Stage` to the graph stage implementations in contrast to almost all other stages in Alpakka.
> Reference: add Stage to the names

- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
Backport of https://github.com/akka/alpakka/pull/1889 to make Alpakka 1.1 work with Akka 2.6
> [Backport #1889] File: Expect correct exception in 2.6

- couchbase/src/main/mima-filters/1.1.1.backwards.excludes
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionImpl.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/impl/CouchbaseSessionJavaAdapter.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSession.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/javadsl/CouchbaseSink.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseSession.scala
- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/scala/akka/stream/alpakka/couchbase/testing/CouchbaseSupport.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseFlowSpec.scala
- couchbase/src/test/scala/docs/scaladsl/CouchbaseSourceSpec.scala
- docs/src/main/paradox/couchbase.md
Backport of https://github.com/akka/alpakka/pull/1888
> [Backport] Added couchbase bucket replace implementation + tests

- docs/src/main/paradox/file.md
- file/src/main/java/akka/stream/alpakka/file/impl/FileTailSource.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/FileTailSource.java
- file/src/test/java/docs/javadsl/FileTailSourceTest.java
- file/src/test/resources/application.conf
- file/src/test/scala/docs/scaladsl/FileTailSourceExtrasSpec.scala
When a file is deleted that is being tailed with `FileTailSource` the source will do nothing.  The underlying API used to stream files from the filesystem uses [`AsynchronousFileChannel`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/AsynchronousFileChannel.html).  The `FileTailSource` will issue an asynchronous read request to the channel which wil callback to the `CompletionHandler` successfully even if the file is deleted.  The handler will signal that no bytes were read with the `-1` special case that we use to trigger a new poll.  ~~Instead of repolling indefinitely, this PR checks if the file exists first.  If it does not exist, then we successfully complete the stage.~~
This PR adds examples to the docs to demonstrate how to shutdown the stream if the file is deleted …
> FileTailSource examples when file deleted or idle

- xml/src/main/mima-filters/1.1.2.backwards.excludes
- xml/src/main/scala/akka/stream/alpakka/xml/impl/StreamingXmlParser.scala
- xml/src/main/scala/akka/stream/alpakka/xml/javadsl/XmlParsing.scala
- xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlParsing.scala
- xml/src/test/java/docs/javadsl/XmlParsingTest.java
- xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
Adds support to pass in a configure function for configuring the XMLInputFactory used by XmlParsing
References #1943
> XML: add support for supplying XMLInputFactory configuration

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/impl/CassandraSourceStage.scala
Under some conditions, the source completed before all results were loaded from the result set.
Now it only completes when rs is fully fetched and all elements were emitted. Before it was completing in case where the current fetched buffer was empty.
References https://github.com/akka/alpakka/issues/1934
* only completes the stream when `rs.isFullyFetched`
* if just the currently loaded set is empty, it fetches more (an edge case)
I observed this issue where fetchSize was set relatively low and the
downstream consumer was fast.
> Cassandra: check `isFullyFetched` before completion

- docs/src/main/paradox/dynamodb.md
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/DynamoDbOp.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoDb.scala
- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/scaladsl/DynamoDb.scala
- dynamodb/src/test/java/docs/javadsl/ExampleTest.java
- dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
Offer the paginating DynamoDB operations as a flow.
When @julianhowarth pointed out in https://github.com/akka/alpakka/issues/767#issuecomment-539102613 I discovered that the `GetBatchItem` operation wasn't prepared for use with pagination in Alpakka.
While at it I added a `flowPaginated` for use of paginated results in flows to complement the source and added some documentation for `flowWithContext`.
(The use of a `RetryFlow` is still pending, we might want to remove the `Try` from the Java API.)
> DynamoDB: flow with pagination

- build.sbt
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/impl/Codec.scala
- ironmq/src/main/scala/akka/stream/alpakka/ironmq/impl/IronMqClient.scala
- project/Dependencies.scala
Upgrade the akka-http-circe dependency from 1.21 to 1.29.1 to reach scala 2.13
(This will not build with 2.11 bcs the lib was released only to 2.12 and 2.13)
Enable Scala 2.13 for IronMq, but disable 2.11.
References #1926 #1534
Maven link: [akka-http-circe](https://mvnrepository.com/artifact/de.heikoseeberger/akka-http-circe)
version up, fix broken code, add visibility modifications from #1926
> IronMq: akka-http-circe 1.21 to 1.29.1

- docs/src/main/paradox/slick.md
- slick/src/main/mima-filters/1.1.x.backwards.excludes
- slick/src/main/scala/akka/stream/alpakka/slick/javadsl/package.scala
- slick/src/main/scala/akka/stream/alpakka/slick/scaladsl/package.scala
- slick/src/test/scala/docs/scaladsl/SlickSpec.scala
Introduces an extra factory method for creating a SlickSession out of Slick Database and Profile instances.
References #1509
* Created method forDbAndProfile(db: JdbcBackend#Database, profile: JdbcProfile): SlickSession in the scaladsl version.
* Before this changes, the scala version of SlickSession object was the same as the javadsl version. Now these two are different, as the above method, only makes sense from scala, due to Slicks missing Java API.
* To avoid duplicat code, all the shared logic of the two SlickSession objects, has been moved to a SlickSessionFactory abstract class, that they both extend.
It makes it possible to create a SlickSession, if you starting point is a Slick Database instance. This can be the case, when working with other libraries, that are based on Slick, …
> Slick: factory method SlickSession.forDbAndProfile

- docs/src/main/paradox/release-notes/1.1.x/google-cloud-pub-sub.md
Improve the wording in the release notes.
See #1994
> Google Cloud Pub-Sub: Scala 2.13 is not supported in 1.1.x

- solr/src/main/scala/akka/stream/alpakka/solr/SolrMessages.scala
Deprecate old `WriteMessage` factory methods in Solr.
See #1491
> Solr: deprecate old write message factories

- project/Dependencies.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/test/java/docs/javadsl/S3Test.java
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
Ensure the HTTP response entity data is discarded when a signing response fails.
* discard entity data in `signAndRequest`
* change Javadsl `listBucket` to use `Optional` instead of `scala.Option` (old methods deprecated)
* add shutdown of Actor System and WireMock in `S3Test`
* upgrade WireMock to 2.25.1 and adapt empty request mocking
> AWS S3: discard entity on failed sign request

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
Queries sent from `ElasticsearchSource.typed` ignore non-ascii characters.
For example, the query created by the following code
```scala
ElasticsearchSource
.typed[Document](
"documents",
"_doc",
query = """{ "match": { "content": "先生" } }"""
)
```
is recorded in `logs/elasticsearch_index_search_slowlog.log` as
```
source[{"size":10,"query":{"match":{"content":{"query":"??","operator":"OR","prefix_length":0,"max_expansions":50,"fuzzy_transpositions":true,"lenient":false,"zero_terms_query":"NONE","auto_generate_synonyms_phrase_query":true,"boost":1.0}}},"sort":[{"_doc":{"order":"asc"}}]}]
```
where "先生" is "??".
- Add `StandardCharset.UTF_8` to `StringEntity` in `ElasticsearchSourceStage.scala` as in `ElasticsearchFlowStage.scala`
> Elasticsearch: Add charset

- .scalafmt.conf
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsBufferedAckConnectorsSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsTxConnectorsSpec.scala
- project/plugins.sbt
Don't let Scalafmt remove braces that are not strictly necessary (eg. around one-expression methods).
* Use the latest sbt-plugin (that works with sbt 1.2.8)
* Up the version in the config to 2.1.0 (triggered a little reindentation)
* Remove `RedundantBraces` rewriting
The removing of braces has annoyed me for some time...
> Scalafmt: don't remove redundant braces

- doc-examples/src/main/resources/logback.xml
- docs/src/main/paradox/file.md
- file/src/main/java/akka/stream/alpakka/file/javadsl/Directory.java
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/Directory.scala
- file/src/test/java/docs/javadsl/DirectoryTest.java
- file/src/test/scala/docs/scaladsl/DirectorySpec.scala
Add new flow factories which will create a directory for every element sent through.
When refreshing the [Alpakka Samples](https://akka.io/alpakka-samples/) I noticed the "Download all file from FTP" example is lacking the creation of local directories.
> File: mkdir flow

- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
fix typo in pub-sub-grpc documentation
> fix GOOGLE_APPLICATION_CREDENTIALS typo

- sqs/src/main/mima-filters/2.0.0-M1.backwards.excludes/PR2032.excludes
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/javadsl/SqsPublishSink.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
- sqs/src/test/java/docs/javadsl/SqsAckTest.java
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/java/docs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
Change the type in the Java API of the batch operations to allow for sub-types of `Iterable` so it composes more nicely with eg. `grouped`.
* Improved closing the SQS client in the tests
* Use Alpakka to publish to the topic in `SqsSourceTest` to avoid too many parallel HTTP connections when tests run on Travis
> SQS: allow sub-types in the Java API; improve tests

- project/Dependencies.scala
> AWS SDK 2.10.34

- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
Make sure SQS tests shut down their streams properly.
Some SQS tests did not shut down the created sources, this makes sure everything is cleaned up.
> AWS SQS: assert stage stopping

- google-cloud-pub-sub/src/main/mima-filters/2.0.0-M1.backwards.excludes/issue-2017-remove-implicits.excludes
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/javadsl/GooglePubSub.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub/src/test/java/docs/javadsl/ExampleUsageJava.java
Use `Flow.setup` to get access to the `ActorSystem` and `Materializer` on materialization so that those don't need to be passed as (implicit) parameters.
#2017 
The APIs were changed by #1983 which introduced the need to access the materializer.
> Google Cloud Pub/Sub: remove ActorSystem and Materializer

- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsProducerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/SourceStageLogic.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSharedServerSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsBufferedAckConnectorsSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsTxConnectorsSpec.scala
Close JMS sessions on stage stop.
(See commits)
* Isolate the access to `sessions` within `JmsConnector`.
* Switch some tests to use a shared JMS broker with by using random queue names
* Close sessions in `finishStop` which is called from `postStop`
While exploring possible solutions to #2039 I noticed the JMS sessions are not properly closed in more scenarios.
> JMS: close sessions in postStop

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
- s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
Validate the bucket name even when using path-style access so that using `..` doesn't give access to other S3 buckets levels.
#1679
* validate bucket names for path-style access
* shut down WireMock in tests
* avoid nesting `Source.setup` in `request`
When using path-style access, the S3 bucket name becomes a part of the URLs and opens up to select sub-directories on S3.
Path-style access is being discontinued by AWS from September 2020 see #1679
> AWS S3: disallow sub-dir selection with bucket names

- build.sbt
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/impl/GuavaFutures.scala
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- google-cloud-pub-sub-grpc/src/main/mima-filters/2.0.0-M2.backwards.excludes/PR2050-version-upgrades.excludes
- project/Dependencies.scala
- project/plugins.sbt
Use the current versions of Akka gRPC and other dependencies.
https://github.com/akka/akka-grpc/releases/tag/v0.7.3
> Google Cloud Pub/Sub gRPC: latest versions

- build.sbt
Make the IntelliJ import work.
Fixes #2028
The IntelliJ sbt import seems to get lost when the `docs` project has a "similar" name as the root project.
> IDE: Rename docs project so that IntelliJ imports it

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
Allowing file download from GCS without having to override `akka.http.client.parsing.max-content-length`
Relevant issue #303 
Relative PR #1036
Possible workout explained [here](https://github.com/akka/alpakka/issues/1176#issuecomment-422230025)
While investigating an issue with file downloads in GCS I came across #303, I thought the fix would be very similar for GCS as well.
> GCS: Remove Unexpected Download Limit

- project/Dependencies.scala
Update akka version from 2.5.26 to 2.5.27 
Update akka-http version from 10.1.10 to 10.1.11
Relevant issue https://github.com/akka/alpakka/issues/2070
> updated akka and akka-http versions

- build.sbt
The travis build fails when publishing artifacts for google-cloud-pub-sub because the `doc` task doesn't have the silencer plugin in scope.  For some reason this is only an issue in the 2.12 and 2.13 cross builds.
Ex)
```
[error] (google-cloud-pub-sub-grpc / Compile / doc) Scaladoc generation failed
```
https://travis-ci.com/akka/alpakka/jobs/273152362#L1611
https://travis-ci.com/akka/alpakka/jobs/273152363#L2199
* Issue created in #2050
* Ref: https://github.com/ghik/silencer/issues/40
* Only apply silencer `scalac` parameters in `Compile, compile` targets.
> Do not use silencer scalac params when running doc task

- build.sbt
The fix in #2077 was able to progress the Alpakka master publishing a step further, but then fails again when the silencer exemption is not available for during the `publish` task itself.  After consulting with @eed3si9n I found a cleaner universal fix that should resolve this issue once and for all.
* Ref #2077 
* https://github.com/ghik/silencer/issues/40#issuecomment-572208376
* Previous master build failure on snapshot publishing https://travis-ci.com/akka/alpakka/jobs/273614859#L1325
Use silencer parameters in all `Compile` configurations only.  Omit `intask` in scoping so it applies to all tasks and remove previous workaround to filter out parameters for the `doc` task specifically.
> Use silencer plugin params only in Compile configuration

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchFlowStage.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
- failed messages are treated independently to avoid loosing track of previously failed ones
- retry counts are kept per message so to guarantee correct number of retries and intervals
- added test case proving fix correctness
Apart for the added test, this pull request has also been tested on a live system which kept failing with the 1.1.2 release.
This pull request corrects ElasticsearchFlowStage retry logic implementation making sure that old failed messages are not lost due to new failures.
References #1566
Only the internal implementation of ElasticsearchFlowStage has been changed to keep track of retry counts on a per message basis.
> Elasticsearch - #1566 - ElasticsearchFlowStage retry logic improvement

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/test/resources/application.conf
- google-cloud-storage/src/test/scala/docs/scaladsl/GCStorageSourceSpec.scala
Remove 8MB download limit on GCS files.
References #2084 
* Removes 8MB download limit for GCS
> Google Cloud Storage: remove download limit (2084)

- file/src/main/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlow.scala
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlowTest.scala
- file/src/test/scala/docs/scaladsl/ArchiveSpec.scala
Fix for possible error "Cannot push port ZipArchiveFlow.out twice"
References #2010
`emit` is used instead of `push` in `onUpstreamFinish()`
> File: Used emit instead of push in onUpstreamFinish

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
prevent vanishing trailing slash in s3 objects keys 
References #2089 
* change key split in a way it does not remove trailing empty slashes
-
> S3 request uri: include empty trailing slashes for the key

- build.sbt
- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/CommittableRecord.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisSchedulerErrors.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisSchedulerSettings.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSchedulerSourceStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSourceStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/ShardProcessor.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/javadsl/KinesisSchedulerSource.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSchedulerSource.scala
- kinesis/src/test/java/docs/javadsl/KclSnippets.java
- kinesis/src/test/java/docs/javadsl/KinesisSnippets.java
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/DefaultTestContext.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSchedulerSourceSpec.scala
- kinesis/src/test/scala/docs/scaladsl/KclSnippets.scala
- project/Dependencies.scala
Adds the KCL Source and record checkpointer Flow/Sink.
Updated version of the old PR: https://github.com/akka/alpakka/pull/434
> AWS Kinesis KCL streams support

- project/Dependencies.scala
- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
Set virtual-host-style access as the default for AWS S3 (from being path-style before).
**This change may break existing usages as it applies much harder restrictions on the bucket names.**
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
#1679
#2053 
#2086
#1993 
#1308
* Mark the `path-style-access` setting as deprecated with references to the blog post
* Issue warnings if `path-style-access` is enabled
Even though virtual-host-style access is much more restrictive on bucket names, it is the designated way forward for S3.
> AWS S3: change default to virtual-host-style access

- docs/src/main/paradox/jms/browse.md
- docs/src/main/paradox/jms/consumer.md
- docs/src/main/paradox/jms/producer.md
- jms/src/main/mima-filters/2.0.0-M2.backwards.excludes/PR2067.excludes
- jms/src/main/resources/reference.conf
- jms/src/main/scala/akka/stream/alpakka/jms/JmsBrowseSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsProducerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/SourceStageLogic.scala
Fixes #2066
This change aims to make sure that references to Jms connection are cleared in both main logic and connection status publishing. Also, it clears the reference to the graph stage logic via the exception listener when the connection gets closed.
This is achieved by:
- Evicting non-consumed connection status events after a specific timeout. This uses a broadcast hub and subscribes a single discarding consumer after a configurable timeout I preliminary called `connection-status-subscription-timeout` and gave it a default of 5 seconds. There would be other ways to fix the leak, but I think this is the simplest and safest way (i.e. safe against accidental misuse).
- Making sure that the reference of the graph stage logic to its Jms connection  is cleared on stop. The code in …
> JMS: Fix memory leak in connection status

- file/src/test/java/docs/javadsl/ArchiveHelper.java
- file/src/test/java/docs/javadsl/ArchiveTest.java
- file/src/test/scala/docs/scaladsl/ArchiveSpec.scala
Improve stability of File archive tests
References #1989 and #1909
- improved stability in java and scala archive zip test
Before, archive created by zip stream was compared with archive created with plan java.
Unfortunately, while creating zip file current time is taken https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/zip/ZipOutputStream.java#L197
So, when the tests were slow, time didn't match in result archive. 
In this fix, archives are not compared. Only input files with files after zip -> unzip.
Fix as discussed with @ennru  https://github.com/akka/alpakka/issues/1909#issuecomment-576184708
> Files: Compare input data in zip archive tests

- docs/src/main/paradox/jms/browse.md
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsAckSourceStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConsumerStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsTxSourceStage.scala
- jms/src/test/scala/docs/scaladsl/JmsTxConnectorsSpec.scala
Try to isolate the commit failure problem reported in #2103 into a test case.
References #2103
* Unfinished test case in `JmsTxConnectorsSpec`
* Change consumer stage logic classes to named classes
* Change logging severity for connection closing
* Remove the browse stage `connectionStatusSubscriptionTimeout` docs (as it didn't get added in #2067)
> JMS: test case for TX sources with broker restart

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/CommonFtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
`Ftp.remove` and `Ftp.move` emit the result in its materialized value of `Future[IOResult]`. Currently there's no way to know if the delete/move failed, e.g. if the file does not exist. A successful and failed delete will both materialize as a `Future.successful(IOResult(1, Success(Done)))`. After this PR, a failed delete will materialize as a `Future.successful(IOResult(1, Failure(IOException)))`.
> FTP: error on failed delete/move

- docs/src/main/paradox/mqtt-streaming.md
- docs/src/main/paradox/other-docs/versioning.md
- docs/src/main/paradox/overview.md
Add a link to the new upgrade strategy docs in main Akka.
> Docs: link to Akka update strategy

- unix-domain-socket/src/test/java/docs/javadsl/UnixDomainSocketTest.java
The lone Java test in unix-domain-socket used for docs has always failed, but we never noticed it because we didn't block on stream completion before the test completed.  The blocking was added #2040 (https://github.com/akka/alpakka/pull/2040/files#r368017011), but the test failure got confused with a transient test failure and the PR was merged.
Changes
* Use a temp directory instead of a file.  `jnr-unixsocket` will create the socket files on our behalf, if the file already exists then we'll observe an `Address in use` exception (https://travis-ci.com/akka/alpakka/jobs/277967218#L358)
* Actually send data through socket!
* Remove framing boilerplate and just parse as a `ByteString` like the Scala docs example does.
> Fix Java Unit Test docs example in Unix Domain Sockets

- unix-domain-socket/src/test/java/docs/javadsl/UnixDomainSocketTest.java
This would have made #2129 more obvious, checking the stream
result is good practice so we should lead by example.
> error handling for UnixDomainSocketTest

- project/Dependencies.scala
- project/build.properties
Removes the need for the workaround for javax.jms
> Update to sbt 1.3.8

- .travis.yml
That is the 'old' location, and if that exists we might risk
coursier accidentally using that dir instead
https://get-coursier.io/docs/cache.html#compatibility-with-former-versions
> Don't create ~/.coursier on travis

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- testkit/src/main/scala/akka.stream.alpakka.testkit/CapturingAppender.scala
- testkit/src/main/scala/akka.stream.alpakka.testkit/LogbackUtil.scala
- testkit/src/main/scala/akka.stream.alpakka.testkit/javadsl/LogCapturingJunit4.scala
- testkit/src/main/scala/akka.stream.alpakka.testkit/scaladsl/LogCapturing.scala
To make the logs for failures more useful.
If this works out we should perhaps apply it upstream, https://github.com/akka/akka/issues/28571
> Allow filtering LogCapturing by source actor system

- project/Dependencies.scala
Upgrade to later versions of "jiffi" and "jnr-unixsocket" and remove the classifier on "jiffi".
The classifier puts sbt-whitesource off https://travis-ci.com/akka/alpakka/jobs/280329800#L356
I'm not sure if the classifier is needed anymore. It works locally on OSX for me.
> Unix domain socket: upgrade dependencies; remove classifier

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/CommonFtpStageTest.java
Make the `java.net.ConnectException` show the host, port, and the proxy settings the `connect` tried.
Ensure the failing move/remove tests actually see the file before they try. #2126
> FTP: enrich ConnectException; track failures

- docs/src/main/paradox/avroparquet.md
- docs/src/main/paradox/awslambda.md
- docs/src/main/paradox/couchbase.md
- docs/src/main/paradox/data-transformations/compression.md
- docs/src/main/paradox/data-transformations/json.md
- docs/src/main/paradox/data-transformations/parsing-lines.md
- docs/src/main/paradox/data-transformations/simple-codecs.md
- docs/src/main/paradox/data-transformations/xml.md
- docs/src/main/paradox/elasticsearch.md
- docs/src/main/paradox/file.md
- docs/src/main/paradox/google-cloud-storage.md
- docs/src/main/paradox/jms/consumer.md
- docs/src/main/paradox/jms/producer.md
- docs/src/main/paradox/mongodb.md
- docs/src/main/paradox/s3.md
- docs/src/main/paradox/slick.md
- docs/src/main/paradox/sns.md
- docs/src/main/paradox/sqs.md
- docs/src/main/paradox/udp.md
Simplify some docs by relying on `@apidoc`.
It actually catched some misspellings, as well.
> Docs: use `@apidoc` much more

- dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/javadsl/DynamoDb.scala
Add an annotation and link to #1987 to defer the decision about `Try` in the Java API.
> DynamoDB: Java API with Try may change

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApiSpec.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleTokenApi.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleTokenApiSpec.scala
improved this while working on #2163
before:
```
DeserializationException, with message: Object is missing required member 'access_token'. (GCStorageStreamIntegrationSpec.scala:130)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
```
after:
```
RuntimeException: Request failed for POST https://www.googleapis.com/oauth2/v4/token, got 400 Bad Request with body: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}
[info]   at akka.stream.alpakka.googlecloud.storage.impl.GoogleTokenApi.$anonfun$readResponse$1(GoogleTokenApi.scala:74)
```
> Better handling of invalid credentials for Google Pub Sub and Cloud Storage connectors

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
Use Unix Domain Socket implementation class as log source.
This logging shows that it logged everything as `akka.actor.ActorSystem` which is very undesired and misleading.
https://travis-ci.com/akka/alpakka/jobs/291725645#L479
> Unix Domain Socket: use class as log source

- google-cloud-storage/src/main/mima-filters/2.0.0-M3.backwards.excludes
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/CustomerEncryption.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/ObjectAccessControls.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/Owner.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/ProjectTeam.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/Formats.scala
Something went wrong when these classes were created and their package names got the `main.scala` prefix.
> Google Cloud Storage: fix package names

- .travis.yml
Alpakka stage jobs are hard to read now that additional env vars push out the `DIR` env var in the env var field of jobs.  We can use job name instead of `DIR`.
> Build: Use stage job name instead of DIR var on travis

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSessionRegistry.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSession.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSessionRegistry.scala
- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSpecBase.scala
- project/Dependencies.scala
Complement the `CassandraSessionRegistry` extension with access methods for `ClassicActorSystemProvider` which makes it usable without changed for the new actors API's `akka.actor.typed.ActorSystem` without depending on that module.
This can't be compiled against Akka 2.6 as `ExtensionId` in that version contains the `apply(ClassicActorSystemProvider)` method so it requires an `override` modifier in `CasssandraSessionRegistry`.
Use the `SystemMaterializer` to get hold of a `Materializer`.
**Upgrades to Akka 2.6.4 and Akka 2.5.30.**
See #2194
> Cassandra: add methods for new actors API (Akka 2.6.4)

- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/resources/logback-test.xml
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
Add logging adapters so that log messages get the FQCN that issues it as log category instead of `Materializer`.
Add an extra logging that may help to identify the cause of #1549
> MQTT Streaming: improve logging

- cassandra/src/main/scala/akka/stream/alpakka/cassandra/CassandraMetricsRegistry.scala
Follow-up on #2195 to make support creating the Metrics Registry from the new actors API.
References #2195
> Cassandra: new actors API in Metrics Registry

- s3/src/main/mima-filters/2.0.0-M3.backwards.excludes
- s3/src/main/scala/akka/stream/alpakka/s3/S3Ext.scala
Complement the `S3Ext` extension with access methods for `ClassicActorSystemProvider` which makes it usable without changed for the new actors API's `akka.actor.typed.ActorSystem` without depending on that module.
This can't be compiled against Akka 2.6 as `ExtensionId` in that version contains the `apply(ClassicActorSystemProvider)` method so it requires an `override` modifier in `S3Ext`.
See #2194, #2195, #2197
> AWS S3: add methods for the new actors API

- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocket.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
Complement the `UnixDomainSocket` extensions with access methods for `ClassicActorSystemProvider` which makes it usable without changed for the new actors API's `akka.actor.typed.ActorSystem` without depending on that module.
This can't be compiled against Akka 2.6 as `ExtensionId` in that version contains the `apply(ClassicActorSystemProvider)` method so it requires an `override` modifier in `UnixDomainSocket`.
See #2194, #2195, #2197, #2211
> Unix Domain Socket: add access with new actors API

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
Guard the HTTP response to be JSON before trying to deserialize it so that missing subscriptions aren't reported as marshalling problems.
References #1840
> Google Cloud Pub/Sub: require JSON responses

- couchbase/src/main/mima-filters/2.0.0-M3.backwards.excludes/ClassicActorSystemProvider
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
Complement the `CouchbaseSessionRegistry` extension with access methods for `ClassicActorSystemProvider` which makes it usable without changed for the new actors API's `akka.actor.typed.ActorSystem` without depending on that module.
This can't be compiled against Akka 2.6 as `ExtensionId` in that version contains the `apply(ClassicActorSystemProvider)` method so it requires an `override` modifier in `CasssandraSessionRegistry`.
See #2194, #2195
> Couchbase: add methods for new actors API

- google-cloud-storage/src/main/mima-filters/2.0.0-M3.backwards.excludes
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageExt.scala
Complement the `GCStorageExt` extension with access methods for `ClassicActorSystemProvider` which makes it usable without changed for the new actors API's `akka.actor.typed.ActorSystem` without depending on that module.
This can't be compiled against Akka 2.6 as `ExtensionId` in that version contains the `apply(ClassicActorSystemProvider)` method so it requires an `override` modifier in `GCStorageExt`.
See #2194, #2195, #2197, #2211, #2212
> Google Cloud Storage: add access with new actors API

- build.sbt
- docker-compose.yml
- s3/src/main/mima-filters/2.0.0-M3.backwards.excludes/PR2183
- s3/src/main/mima-filters/2.0.0-M3.backwards.excludes/PR2193
- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Enable use of DNS-style access while setting an endpoint URL so to use other S3 compatible solutions such as [MinIO](https://min.io/).
Introduce a new flag `path-style-access-warning` which can be used to switch off the logged warning when path-style access is enabled.
References #2171
Support a placeholder `{bucket}` in the `endpoint-url` setting which is replaced with the bucket name.
The second commit makes use of Akka HTTP `ClientTransport` to force requests to `localhost` even if the request authority is something different, to allow the dynamic hostnames to contain the bucket names. This affects the `S3IntegrationSpec` quite significantly, as now all requests need to get the `S3Settings` passed explicitly. (This shows the motivation for #2139.)
As #2099 (issue #1679) switched the …
> AWS S3: virtual-host-style access with endpoint URL

- build.sbt
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- google-cloud-pub-sub-grpc/src/main/mima-filters/2.0.0-M3.backwards.excludes/Akka-gRPC-upgrade
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/PubSubSettings.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GrpcPublisher.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GrpcSubscriber.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GrpcPublisher.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GrpcSubscriber.scala
- google-cloud-pub-sub-grpc/src/test/java/docs/javadsl/IntegrationTest.java
- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
- project/Dependencies.scala
- project/plugins.sbt
Complement the factory methods with methods for `ClassicActorSystemProvider` which makes it usable without changed for the new actors API's `akka.actor.typed.ActorSystem` without depending on that module.
This can't be compiled against Akka 2.6 as `ExtensionId` in that version contains the `get(ClassicActorSystemProvider)` method so it requires an `override`.
**Upgrades to Akka 2.5.30 and Akka gRPC 0.8.0**
See #2194, #2195, #2197
> Google Cloud Pub/Sub gRPC: hide materializer, support new actors API

- mongodb/src/main/scala/akka/stream/alpakka/mongodb/DocumentReplace.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/javadsl/MongoFlow.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/javadsl/MongoSink.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoFlow.scala
- mongodb/src/main/scala/akka/stream/alpakka/mongodb/scaladsl/MongoSink.scala
- mongodb/src/test/java/docs/javadsl/DomainObject.java
- mongodb/src/test/java/docs/javadsl/MongoSinkTest.java
- mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala
> MongoDB: replaceOne operation

- mqtt-streaming/src/main/mima-filters/2.0.0-M3.backwards.excludes/ClassicActorSystemProvider
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/javadsl/MqttSession.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/scaladsl/MqttSession.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttActorSystemsSpec.scala
Changes the factory methods and constructors of the `MqttSession`s to just require a `ClassicActorSystemProvider` instead of `akka.actor.ActorSystem` and `akka.stream.Materializer`.
This is possible as Alpakka MQTT Streaming is only compatible with Akka 2.6.
This makes it easier to use with the new actor APIs and hides the existence of the materializer form the users.
References #2118
> MQTT streaming: ClassicActorSystemProvider in the API

- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub-grpc/src/test/java/docs/javadsl/IntegrationTest.java
- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
References #2141 
Here is a simple approach to have synchronous pull. I tried this in our environment (scala) and it worked well, the only quirk being that we have to tune the `maxMessages` parameter and interval finely. Wondering if there is a better way to manage the amount of messages being pulled.
This is what the usage looks like:
```
private val request: PullRequest =
PullRequest().withSubscription(Settings.PubSub.pubSubSubscription).withMaxMessages(100)
lazy val source: Source[ReceivedMessage, Future[Cancellable]] = GooglePubSub.subscribe(request, 100.millis)
```
> Google pub/sub gRPC: allow sync poll using PullRequest

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/KinesisErrors.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSourceStage.scala
In one of my project, I'd like to further understand easily what are the cause of the errors when using `KinesisSourceStage`, further in my downstream handler. 
When failing to fetch the Kinesis shard for example, it will now tell you more detailed error message (such as when the Kinesis HTTP server fails to respond)
> Kinesis: more descriptive Source error log

- cassandra/src/test/java/docs/javadsl/CassandraFlowTest.java
- cassandra/src/test/java/docs/javadsl/CassandraSourceTest.java
- cassandra/src/test/resources/application.conf
- cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSpecBase.scala
- project/Dependencies.scala
* Apply log capturing to Cassandra tests
* Exclude the Netty dependency
* Exclude all Tinkerpop dependencies (see #2200)
* Upgrade Jackson Databind to 2.10.3 to align with Akka 2.6 (add add explicitly to Cassandra dependencies)
The fix to the performance issued that were traced down to Netty, did not exclude the Netty dependency. https://github.com/akka/akka-persistence-cassandra/pull/730
This should be removed, once it is fixed in the Netty version the Cassandra Java driver pulls in. Filed #2226
> Cassandra: apply Netty exclusion; exclude all Tinkerpop and Esri Geometry depenencies

- pravega/src/main/resources/reference.conf
- pravega/src/main/scala/akka/stream/alpakka/pravega/impl/PravegaSource.scala
- pravega/src/test/java/akka/stream/alpakka/pravega/PravegaGraphTestCase.java
- pravega/src/test/resources/application.conf
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaGraphSpec.scala
Checkpoint event were not handle correctly neither timeout.
> Pravega fix checkpointing (and timeout)

- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/javadsl/GooglePubSub.scala
- google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/scaladsl/GooglePubSub.scala
- google-cloud-pub-sub/src/test/java/docs/javadsl/ExampleUsageJava.java
- google-cloud-pub-sub/src/test/scala/docs/scaladsl/ExampleUsage.scala
I have a small improvement for current PubSub API. Pulling from PubSub should be exposed as a flow, not the source. This gives the user more elasticity over stream composition. 
The benefits are: 
* User can set pulling frequency configuring source or attaching any source depends he needs
* Network failures happen from time to time when implementing backoff strategy for source we losing access materializer for original source. This means we cannot cancel the source anymore. When we use backoff strategy for flow we still have access to source materializer. As mention before more elasticity in composition. 
I left the old interface for backward compatibility.
> Google PubSub: subscribe as a flow

- cassandra/src/main/resources/reference.conf
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/AkkaDiscoverySessionProvider.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/CassandraMetricsRegistry.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/CqlSessionProvider.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/javadsl/CassandraSessionRegistry.scala
- cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSessionRegistry.scala
- couchbase/src/main/java/akka/stream/alpakka/couchbase/javadsl/DiscoverySupport.java
- couchbase/src/main/mima-filters/2.0.0-RC1.backwards.excludes/ClassicActorSystemProvider.excludes
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/CouchbaseSessionRegistry.scala
- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/DiscoverySupport.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GrpcPublisher.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GrpcSubscriber.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GrpcPublisher.scala
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GrpcSubscriber.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageExt.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCStorageSettings.scala
- kudu/src/main/mima-filters/2.0.0-RC1.backwards.excludes/ClassicActorSystemProvider.excludes
- kudu/src/main/scala/akka/stream/alpakka/kudu/KuduClientExt.scala
- project/Dependencies.scala
- reference/src/main/scala/akka/stream/alpakka/reference/Resource.scala
- s3/src/main/scala/akka/stream/alpakka/s3/S3Ext.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- udp/src/main/scala/akka/stream/alpakka/udp/scaladsl/Udp.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocket.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
In Akka 2.5.31 the `ClassicActorSystemProvider` is actually implemented by the `akka.actor.ActorSystem` and `akka.actor.typed.ActorSystem[_]` so that it can be used to accept both types of actor systems.
With this PR the Alpakka APIs prefer the provider so that integration with the new actor APIs doesn't need any adapter in user code.
> Akka 2.5.31 and prefer `ClassicActorSystemProvider`

- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AbstractAmqpAsyncFlowStageLogic.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpFlowSpec.scala
Fixes StackOverflowException which occurs if AMQP publishing stage with delivery confirmation fails on connection, channel, ...  creation.
> AMQP: fix StackOverflowException in AbstractAmqpAsyncFlowStageLogic

- jms/src/main/scala/akka/stream/alpakka/jms/JmsBrowseSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/SendRetrySettings.scala
Allows passing an actor system of the new actors API without conversion on the user side.
> JMS: create settings from new actors API

- couchbase/src/main/scala/akka/stream/alpakka/couchbase/model.scala
Allows passing an actor system of the new actors API without conversion on the user side.
> Couchbase: settings from ClassicActorSystemProvider

- docs/src/main/paradox/file.md
- file/src/main/mima-filters/2.0.0-RC2.backwards.excludes/PR2268-tar-reader.excludes
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntry.scala
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarReaderStage.scala
- file/src/main/scala/akka/stream/alpakka/file/javadsl/Archive.scala
- file/src/main/scala/akka/stream/alpakka/file/model.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/Archive.scala
- file/src/test/java/docs/javadsl/ArchiveTest.java
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntrySpec.scala
- file/src/test/scala/docs/scaladsl/ArchiveSpec.scala
- file/src/test/scala/docs/scaladsl/TarArchiveSpec.scala
Add reading of tar-formatted streams of `ByteString`s.
Inspired by the recent addition of writing tar in #2241 by @choffmeister.
* Add `TarReaderStage`
* Tar header parsing in `TarArchiveEntry`
* Improve `ByteString` handling in `TarArchiveEntry` header creation
* Move tar tests into own spec
TODO
> File: TAR archive reader

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Adds missing URL encoding for source keys when copying.
> AWS S3: Allow source keys with non-ASCII characters

- build.sbt
- project/Common.scala
- project/Dependencies.scala
- sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
Make the scheduled build use Akka 2.6 and Akka HTTP 10.2.
This required to provide an implicit actor system in the SSE tests, so that the `Route` to `Flow[...]` conversion would become applicable.
https://doc.akka.io//docs/akka-http/10.2/release-notes/10.2.x.html
> Build: Akka HTTP 10.2 in cron build

- mqtt/src/main/scala/akka/stream/alpakka/mqtt/impl/MqttFlowStage.scala
The materialized subscription promise should not be completed again when a reconnect happens.
(I'm not sure yet why this problem didn't show earlier.)
References #2288
> MQTT: avoid completing promise on reconnect

- avroparquet/src/main/mima-filters/2.0.0-RC2.backwards.excludes/PR2273-generics.excludes
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/impl/AvroParquetFlow.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/impl/AvroParquetSource.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/javadsl/AvroParquetFlow.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/javadsl/AvroParquetSink.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/javadsl/AvroParquetSource.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/scaladsl/AvroParquetFlow.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/scaladsl/AvroParquetSink.scala
- avroparquet/src/main/scala/akka/stream/alpakka/avroparquet/scaladsl/AvroParquetSource.scala
- avroparquet/src/test/java/docs/javadsl/AvroParquetSinkTest.java
- avroparquet/src/test/java/docs/javadsl/Examples.java
- avroparquet/src/test/scala/docs/scaladsl/AbstractAvroParquet.scala
- avroparquet/src/test/scala/docs/scaladsl/AvroParquetFlowSpec.scala
- avroparquet/src/test/scala/docs/scaladsl/AvroParquetSinkSpec.scala
- avroparquet/src/test/scala/docs/scaladsl/AvroParquetSourceSpec.scala
- build.sbt
- docs/src/main/paradox/avroparquet.md
- project/Dependencies.scala
Hello!
There is no issue related with this PR.
While looking at how to implement protobuf parquet connector, I realised that the current implementation of avroparquet was statically typead as `GenericRecord`, which for the Akka user is not nice.
On continuation with that the tests were simplified and improved by not just checking the number of records written but also the actual content of the file.
> Avroparquet: Lower bound higher kinded 

- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3WireMockBase.scala
…to try and address intermittent failures (#2209).
No guarantees this will address the failures, but I can't replicate them locally, so will have to rely on Travis.
> S3: Add some backoff delay to multipart upload retries for tests

- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvParser.scala
- csv/src/test/scala/akka/stream/alpakka/csv/CsvParserSpec.scala
When the input to CSVParser.offer starts with a UTF-8 byte order marker, the cursor is advanced 4 places (but the size of the BOM is 3 bytes). This causes an edge case if the first value is quoted, where it gets wrapped in additional quotes:
```
val in = ByteString("\"one\",\"two\",\"three\"\n", StandardCharsets.UTF_8.name())
val inWithBom = ByteOrderMark.UTF_8 ++ in
val parser = new CsvParser(',', '"', '\\', maximumLineLength)
println("Without BOM")
parser.offer(in)
parser.poll(false).value.map(_.utf8String).foreach(s => println("- " + s))
println("With BOM")
parser.offer(inWithBom)
parser.poll(false).value.map(_.utf8String).foreach(s => println("- " + s))
```
Output prior to this change (see the extra quotes around "one" in the second case):
```
Without BOM
- one
- two
- three
With BOM …
```
> CSV: handle UTF-8 BOM correctly

- project/Dependencies.scala
> Fix intermittent issues with Wiremock connection reset simulation

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchWriteSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/RestBulkApi.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/RestBulkApiV5.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/RestBulkApiV7.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchConnectorBehaviour.scala
Purpose
---
Enables the use of the Elasticsearch Sink in non-default environments where url-based access control is performed.
This PR is an update of #1844 which seems to be abandoned.
References
---
References #1843 
Changes
---
`ElasticsearchWriteSettings`: Added an aditional setting `allowExplicitIndex`
`ElasticsearchSimpleFlowStage[T, C]`: The actual endpoint to which the _bulk request is determined based on the newly introduced `ElasticSearchWriteSetting.allowExplicitIndex` 
`RestBulkApi` and `RestBulkApiV5` and `RestBulkApiV7`: Support writing the shared fields to the API based on the `allowExplicitIndex` setting
Background Context
---
Current implementation of the Elastic search Sink will fail (requests rejected) if the cluster configuration does not hold the default setting for …
> [elasticsearch] Support `allow_explicit_index: false`

- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntry.scala
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntrySpec.scala
> file/tar: Allow space as terminal character in tar header

- file/src/main/mima-filters/2.0.0-RC2.backwards.excludes/PR2323-log-rotator-sink.excludes
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
The current implementation of `LogRotatorSink` works well for time-based rotation, if the time is the real time. It does not fit well, if the time to trigger on is contained in the stream itself, since the stream is already of type `ByteString`. You had to parse that `ByteString` to gain access to the time contained in the data (or anything else you would like to trigger on).
This PR slightly modifies `LogRotatorSink` to accept an additional type parameter `T`. The triggerGeneratorCreator function becomes `T => Option[C]`, the sinkFactory becomes `C => Sink[T, Future[R]]`. This allows to trigger on data contained in `T`, the sink also works on `T` and probably uses a transformer `T => ByteString`. For details, have a look at the new test in `LogRotatorSinkSpec`.
> Allow LogRotatorSink be a Sink[T] instead of Sink[ByteString]

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
References #2314
In the referenced issue, I had asked about the proper way to keep the stage alive for clean up when downstream has already finished. I noticed that some other stages were doing this by calling `setKeepGoing(true)`, so I used that here. The documentation seems to support the use case, but please let me know if it looks incorrect.
I plan to add tests and documentation in the coming days. I wanted to get this PR up first to see if there was any feedback on the initial implementation.
> ElasticsearchSource: Clear Scroll On Exhaustion or Completion

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardIterator.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardSettings.scala
- kinesis/src/test/java/docs/javadsl/KinesisSnippets.java
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisSourceSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/ShardSettingsSpec.scala
- kinesis/src/test/scala/docs/scaladsl/KinesisSnippets.scala
References #2315 
I'd also suggest to mark the following methods as deprecated:
```scala
def withShardIteratorType
def withStartingSequenceNumber
def withStartingAfterSequenceNumber
def withAtTimestamp
```
Although technically the latter 3 are safe, it is not visible in their type that they are also changing the shard iterator type and I've observed people making the mistake of setting the shard iterator type first anyway  (including myself :P)
Please let me know what you think.
Thanks
> Kinesis: Construction safe API

- project/Dependencies.scala
Underlying perf issue has been fixed
> Cassandra: Driver 4.6.1 (Remove netty override)

- s3/src/main/scala/akka/stream/alpakka/s3/S3Exception.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3ExceptionSpec.scala
* Simplify construction of the exception when the XML can't be parsed.
* Always keep the HTTP status code.
* According to the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) it should be `RequestId` not `RequestID` as the earlier code did.
* `HostID` doesn't exist anymore(?), but `Resource` is there
References #2310
> AWS S3: parse error replies

- project/Dependencies.scala
Removes the explicit dependency on `jsurfer`, which is of type `pom`, but is implicitly specified as being of type `jar` in the generated POM for `alpakka-json-streaming`, making the latter unusable from Maven (#2338).
> json-streaming: fix generated POM

- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
I would expect the stream to be terminated with an exception, if the sink created by `sinkFactory` of `LogRotatorSink.withSinkFactory` throws an exception. This is not the case. I added a test case in `LogRotatorSinkSpec` that demonstrates this.
The issue initially occured while trying to use `LogRotatorSink` together with `S3.multipartUpload`. My aws-config was not correct, leading to Exceptions being thrown in `S3.multipartUpload`-Sink, which never showed up and left the stream in a non-functional, but not terminated condition. I had to remove `LogRotatorSink` and use `S3.multipartUpload` directly to see those exceptions and have the stream terminated.
> File: Fail LogRotatorSink on failures in the sinks

- slick/src/main/scala/akka/stream/alpakka/slick/javadsl/Slick.scala
- slick/src/test/java/docs/javadsl/DocSnippetFlow.java
- slick/src/test/java/docs/javadsl/DocSnippetFlowWithPassThrough.java
- slick/src/test/java/docs/javadsl/DocSnippetSink.java
- slick/src/test/java/docs/javadsl/SlickTest.java
Extend Java DSL for using `java.sql.PreparedStatement`
References #2247
> Slick/JDBC: Support `PreparedStatement` use in Java DSL

- amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpReplyToSinkStage.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectorsSpec.scala
Fixes situation when `properties` of the message are present, but `replyTo` header in this properties is `null`. In that case `elem.properties.map(_.getReplyTo)` evaluated to `Some(null)` and sending message resulted with the error:
```
java.lang.IllegalStateException: Invalid configuration: 'routingKey' must be non-null.
at com.rabbitmq.client.impl.AMQImpl$Basic$Publish.<init>(AMQImpl.java:2280)
at com.rabbitmq.client.AMQP$Basic$Publish$Builder.build(AMQP.java:1219)
at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:696)
at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicPublish(AutorecoveringChannel.java:202)
at akka.stream.alpakka.amqp.impl.AmqpReplyToSinkStage$$anon$1$$anon$2.onPush(AmqpReplyToSinkStage.scala:74)
```
> AMQP: Fixes handling null replyTo header in AmqpReplyToSinkStage

- project/Dependencies.scala
Override to the latest patch version of Jackson Databind.
refs #2372
> Jackson 2.10.5 (to get latest security fixes)

- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/impl/util/Delay.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/impl/util/Splitter.scala
- google-cloud-bigquery/src/test/scala/akka/stream/alpakka/googlecloud/bigquery/impl/util/SplitterSpec.scala
Fixes #2379 
Fixes #2361 
Fixes #2378 
More info below the linked issues but tldr;
The BQ connector has a cycle in it, so the pull and close propagation are critical. The filter changes in 2.6.2 (akka/akka#28467) broke it, so the Splitter logic moved to a custom stage. This made the tests in earlier and later akka versions green too.
> BigQuery: re-implement splitter as stage

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSource.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttActorSystemsSpec.scala
- sns/src/main/scala/akka/stream/alpakka/sns/scaladsl/SnsPublisher.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala
- sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsSource.scala
I got reports from users that ended up with an NPE without understanding where it came from.
This PR covers some random connectors which get a client instance passed (implicitly).
> Check client instance for nulls

- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
They don't really have a function here since requestNext returns as soon
as the expected object arrives
fixes #2389
> SQS tests: Remove tight requestNext timeout

- project/Dependencies.scala
Needs to be at least 2.6.5 because the grpc-based pub-sub
implementation needs https://github.com/akka/akka/issues/28818
> Build against Akka 2.6.8 on Travis nightlies

- s3/src/main/resources/reference.conf
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3ExtSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
References #2171 . In the pull request https://github.com/akka/alpakka/pull/2193#issuecomment-686304485 it was noted that it would be better to have a separate `access-style` property instead of the current tripartite `path-style-access` one. This PR attempts to improve that situation.
With this change, `access-style` is the preferred way of setting the property, using either `path` or `virtual`.
If the old, deprecated `path-style-access` is used, that takes precedence, but a warning is logged to instruct the developer to change to the new property.
If the effective access style is `path`, and `endpoint-url` is not set (i.e. the S3 provider is AWS), one warning is issued. This is not configurable, but it shouldn't have to be, because using path-style access on AWS S3 is likely going to …
> S3: Add access-style property

- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MarshallingSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SlowMinioIntegrationSpec.scala
- scripts/create-slow-minio.sh
* Add support for `text/event-stream` in CompleteMultipartUploadResultUnmarshaller
* Add a unit test for unmarshlling
* Add an integration test to reproduce the behviour using a throttled Minio instance. Since setting up the throttled minio instance requires some effort, the test must be run manually and is annotated with an `@Ignore`
fixes #2394
> S3: `text/event-stream` ContentType in multipart upload response

- docs/src/main/paradox/overview.md
follow-up to #2393
Or should it say Akka 2.6.8 as that's what we validate in the scheduled build?
> docs: least Akka 2.6 version from the scheduled build

- docs/src/main/paradox/file.md
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntry.scala
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarReaderStage.scala
- file/src/main/scala/akka/stream/alpakka/file/model.scala
- file/src/test/java/docs/javadsl/ArchiveTest.java
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/TarArchiveEntrySpec.scala
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlowTest.scala
- file/src/test/scala/docs/scaladsl/TarArchiveSpec.scala
* Support directory entries in tar files (writing and reading)
* Accept closing EOF marker blocks of 512 0-bytes
The somewhat loose tar standard allows for more variants than Alpakka File can handle. This adds support for the "link indicator" flag, which also indicates directory entries.
Tar recommends files end with two 512 byte blocks of 0-bytes. This makes Alpakka File handle those and read to the end of the incoming streams.
> File: tar with directory support and EOF block detection

- build.sbt
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
To make the log capturing more useful and possibly understand what's off in eg #1723
Most modules did switch it off even before this.
> tests: disable parallel execution

- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
Using `S3.deleteObjectsByPrefix("bucket", None)` looks a bit odd.
> S3: Add method to delete bucket contents

- amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectionProvidersTest.java
- aws-event-bridge/src/test/java/docs/javadsl/EventBridgePublisherTest.java
- build.sbt
- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- couchbase/src/test/java/docs/javadsl/DiscoveryTest.java
- csv/src/test/java/docs/javadsl/CsvFormattingTest.java
- csv/src/test/java/docs/javadsl/CsvParsingTest.java
- csv/src/test/java/docs/javadsl/CsvToMapTest.java
- file/src/test/scala/docs/scaladsl/TarArchiveSpec.scala
- ftp/src/test/java/docs/javadsl/FtpWritingTest.java
- google-cloud-storage/src/test/java/docs/javadsl/GCStorageTest.java
- jms/src/test/java/docs/javadsl/JmsSettingsTest.java
- jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
- json-streaming/src/test/java/docs/javadsl/JsonReaderUsageTest.java
- kudu/src/test/java/docs/javadsl/KuduTableTest.java
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt/src/test/java/docs/javadsl/MqttSourceTest.java
- project/Common.scala
- simple-codecs/src/test/java/docs/javadsl/RecordIOFramingTest.java
- slick/src/test/java/docs/javadsl/SlickTest.java
- sns/src/test/java/docs/javadsl/SnsPublisherTest.java
- text/src/test/java/docs/javadsl/CharsetCodingFlowsDoc.java
- xml/src/test/java/docs/javadsl/XmlParsingTest.java
tests: use Hamcrest's assertThat 
JMS tests: expect connection to be closed eventually 
File tests: Check that the file exists, eventually on Travis 
Slick test: recover -> recoverWithRetries
A part of #2410
> Less use of deprecated APIs in Java code

- project/Common.scala
Since enabling more Java warnings in #2413 the scheduled build, which runs on JKD11, failed.
This allows warnings in the scheduled build, just as Scala warnings are allowed.
> CI: allow Java warnings in the schdeduled build

- project/Dependencies.scala
Align io.grpc grpc-auth version with the versions brought in by Akka gRPC.
https://doc.akka.io/docs/akka-grpc/1.0.0/server/walkthrough.html#dependencies
﻿
> Google Cloud Pub/Sub gRPC: align the gRPC auth version

- docker-compose.yml
Switches to the official gcloud emulator for the gRPC tests.
This is the same image as #2425 uses for the non-gRPC variant.
> Google Pub/Sub gRPC: use the gcloud emulator in tests

- pravega/src/main/scala/akka/stream/alpakka/pravega/PravegaSettings.scala
Builder didn't forward the keyExtractor
References #2441
> Pravega: keyExtractor not set

- docker-compose.yml
Select the former version of the gcloud docker image as all Pub/Sub tests started failing.
Refs #2448﻿
> Google Pub/Sub: lock emulator version to 313.0.1

- docker-compose.yml
The last successful CRON build was 26/9, this is the most
recent tag that was uploaded before that date.
> Google Pub-Sub: Switch to older emulator image

- google-fcm/src/main/mima-filters/2.0.x.backwards.excludes
- google-fcm/src/main/resources/reference.conf
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/FcmSettings.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/ForwardProxyHttpsContext.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/ForwardProxyPoolSettings.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmFlows.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmSender.scala
- google-fcm/src/main/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApi.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/FcmSenderSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/impl/GoogleTokenApiSpec.scala
Akka HTTP has support for forward proxies via its [Pluggable Client Transports](https://doc.akka.io/docs/akka-http/current/client-side/client-transport.html). The functionality is used in this update in order to support forward proxies when integrating with Google FCM.
> Google FCM: Forward proxy

- aws-event-bridge/src/test/java/docs/javadsl/EventBridgePublisherTest.java
- elasticsearch/src/test/java/docs/javadsl/ElasticsearchTest.java
- file/src/main/java/akka/stream/alpakka/file/impl/DirectoryChangesSource.java
- file/src/main/java/akka/stream/alpakka/file/javadsl/DirectoryChangesSource.java
- jms/src/test/java/docs/javadsl/JmsConnectorsTest.java
- orientdb/src/test/java/docs/javadsl/OrientDbTest.java
- project/Common.scala
Enable more Java linting flags and﻿fix a few warnings detected by it.
> Catch and fix more warnings in Java sources

- build.sbt
- docs/src/main/paradox/mqtt-streaming.md
- docs/src/main/paradox/overview.md
- google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/javadsl/GooglePubSub.scala
- project/Common.scala
- project/Dependencies.scala
- text/src/main/scala/akka/stream/alpakka/text/javadsl/TextFlow.scala
Set Akka 2.6.10 as the only Akka version used in Alpakka.
To allow the deprecation warnings in CI, `fatalWarnings` is now `false` by default. https://github.com/akka/alpakka/issues/2456
References #2054
> Require Akka 2.6 (drop Akka 2.5)

- build.sbt
- csv/src/test/java/docs/javadsl/CsvFormattingTest.java
- csv/src/test/java/docs/javadsl/CsvParsingTest.java
- csv/src/test/java/docs/javadsl/CsvToMapTest.java
- csv/src/test/scala/docs/scaladsl/CsvSpec.scala
Update the CSV tests to pass the actor system instead of an explicit materializer.
References #2054, #2468
> CSV: remove materializer

- pravega/src/main/scala/akka/stream/alpakka/pravega/PravegaSettings.scala
- pravega/src/test/java/akka/stream/alpakka/pravega/PravegaAkkaTestCaseSupport.java
- pravega/src/test/java/akka/stream/alpakka/pravega/PravegaGraphTestCase.java
- pravega/src/test/java/docs/javadsl/PravegaBaseTestCase.java
- pravega/src/test/java/docs/javadsl/PravegaReadWriteDocs.java
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaBaseSpec.scala
- pravega/src/test/scala/akka/stream/alpakka/pravega/PravegaGraphSpec.scala
Initially I was only attempting to recreate #2453. I noticed when I ran the same test twice I received a timeout on the same Future as #2453.  I added some explicit timeouts to the data population code and got a little carried away.
* Always use unique group, scope, and stream name per test
* Java API: overload to load `ReaderBasicSettings` from supplied config
* Remove usages of Materializer
> Pravega: Re-factor tests

- text/src/test/java/docs/javadsl/CharsetCodingFlowsDoc.java
- text/src/test/scala/akka/stream/alpakka/text/scaladsl/CharsetCodingFlowsSpec.scala
- text/src/test/scala/docs/scaladsl/CharsetCodingFlowsDoc.scala
Fixes #2503 
(doesn't enable fatal warnings as that triggers a total rebuild of Alpakka, I'll spare that until we have merged a few)﻿
> Text: Adapt to Akka 2.6

- build.sbt
- xml/src/test/java/docs/javadsl/XmlParsingTest.java
- xml/src/test/java/docs/javadsl/XmlWritingTest.java
- xml/src/test/scala/docs/scaladsl/XmlCoalesceSpec.scala
- xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
- xml/src/test/scala/docs/scaladsl/XmlSubsliceSpec.scala
- xml/src/test/scala/docs/scaladsl/XmlSubtreeSpec.scala
- xml/src/test/scala/docs/scaladsl/XmlWritingSpec.scala
> xml: Akka 2.6 features

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchSourceSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchWriteSettings.scala
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStageTest.scala
PR to change the default Elasticsearch version from V5 to V7. Change impacts the default used by both the `ElasticsearchSourceSettings` and `ElasticsearchWriteSettings`
> Elasticsearch: Make V7 the default version

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/backport/RetryFlowCoordinator.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/javadsl/ElasticsearchSource.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/test/java/docs/javadsl/ElasticsearchTestBase.java
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStageTest.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpec.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpecBase.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpecUtils.scala
With the switch to Akka 2.6, a lot of deprecation warnings popped up. I've removed all deprecation warnings and a few unused import warnings for the Elasticsearch module.
> Elasticsearch: Adapt to Akka 2.6

- docs/src/main/paradox/sns.md
- sns/src/test/java/docs/javadsl/SnsPublisherTest.java
- sns/src/test/scala/akka/stream/alpakka/sns/DefaultTestContext.scala
- sns/src/test/scala/akka/stream/alpakka/sns/IntegrationTestContext.scala
> SNS: Akka 2.6; proper Http client pool shutdown in tests

- docs/src/main/paradox/sqs.md
- sqs/src/main/scala/akka/stream/alpakka/sqs/impl/BalancingMapAsync.scala
- sqs/src/test/java/akka/stream/alpakka/sqs/javadsl/BaseSqsTest.java
- sqs/src/test/java/docs/javadsl/SqsAckTest.java
- sqs/src/test/java/docs/javadsl/SqsPublishTest.java
- sqs/src/test/java/docs/javadsl/SqsSourceTest.java
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/DefaultTestContext.scala
> SQS: Akka 2.6; proper Http client pool shutdown in tests

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/BaseFtpSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/BaseSftpSupport.java
- ftp/src/test/java/akka/stream/alpakka/ftp/BaseSupportImpl.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseFtpsSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSftpSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
This PR addresses issue https://github.com/akka/alpakka/issues/2541: when wrong credentials are being used to connect to a FTP server, the materialized Future will be completed with a failure containing a `UserAuthException`.
While `UserAuthException` belongs to `sshj` project, thus not really 100% appropriate for `FtpsOperations` and `FtpOperations` (it's only thrown by `SftpOperations`), I believe it looks more consistent from an user perspective rather than throwing for example a `javax.security.auth.login.FailedLoginException` for the Ftp/Ftps cases and a `UserAuthException` in case of `Sftp`.
> Ftp 2541 incorrect credentials should complete with a failed future

- project/Dependencies.scala
This version of jms-testkit has been cross-compiled
for Scala 2.11, Scala 2,12, Scala 2.13, and Scala 3.0.0-M3
https://github.com/sullis/jms-testkit/commits/master
> jms-testkit 0.4.1

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/javadsl/GCStorage.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorage.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStreamIntegrationSpec.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/scaladsl/GCStorageWiremockBase.scala
- google-cloud-storage/src/test/scala/docs/scaladsl/GCStorageSinkSpec.scala
Pretty self explanatory, metadata is currently part of StorageObjects but wasn't able to be added on upload.
I wasn't sure which combination of overloaded functions/default args to add, so for now I've just added an additional overloaded function for where chunkSize is already set.
I didn't add it for the `simpleUpload` case as it [seems to be quite messy to upload a single file with metadata](https://cloud.google.com/storage/docs/uploading-objects), so I felt it best to leave until someone had a use case for that
> GCS: Allow adding custom metadata for resumable uploads

- docs/src/main/paradox/slick.md
Some additional parameters need to be set to stream some databases such as PostgreSQL
I got the surprise of my application loading my whole database in-memory while I was thinking I was streaming it, so I think it's worth highlighting this.
References https://github.com/akka/alpakka/issues/1128
> Slick: Add note about enabling streaming with PostgreSQL (#1128)

- contributor-advice.md
Fixes link for for Java API factory methods source file in `contributor-advice.md`.
> Fix broken link in contributor-advice.md

- couchbase/src/test/java/docs/javadsl/CouchbaseExamplesTest.java
- docs/src/main/paradox/jms/consumer.md
- docs/src/main/paradox/jms/producer.md
- ftp/src/test/scala/docs/scaladsl/SftpSpec.scala
- jms/src/test/java/docs/javadsl/JmsConnectorsTest.java
- jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
- project/plugins.sbt
CCPA banner from akka/akka-paradox#135
> Update to paradox theme with new cookie banner

- jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala
A Java API `withProperties(properties: java.util.Map[String, Object])` method was missing from several passthrough JMS message types. This PR adds a new trait to enforce its implementation.
> Enforce withProperties Java API on passthrough messages

- file/src/main/mima-filters/2.0.0-RC2.backwards.excludes/PR2559-log-rotator-sink.excludes
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/LogRotatorSink.scala
- file/src/test/scala/docs/scaladsl/LogRotatorSinkSpec.scala
issue come up with; https://discuss.lightbend.com/t/writing-element-each-to-its-own-file-problem-on-last-element/7696 also #2553
I need some help, bcs I see something really odd! I will write down the context to get faster to the point;
The logRotator is a custom sink stage. When it gets an element, it runs a function, and if the input function returns with a Some, creates a new subSink, and send the element to that sink.
The current problem appears when the subsink is still initializing (not consuming the dangling data) while the input gets an `onUpstreamFinish`. At this point the stage completes without giving down the last element to the last sink.
My idea was to simply override the input handler when the rotation happens and we still waiting to the data to be consumed by the new …
> File: LogRotatorSink fix completition

- docs/src/main/paradox/ftp.md
- ftp/src/main/mima-filters/2.0.2.backwards.excludes
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/test/java/docs/javadsl/SftpRetrievingExample.java
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
- ftp/src/test/scala/docs/scaladsl/scalaExamples.scala
Fixes: #2557
This change allows the SFTP connector to send multiple parallel read requests to an SFTP server, significantly improving throughput.
A new API has been added to `SftpSettings` - `withMaxUnconfirmedReads(value: Int)`.  When this value is >=2 it will result in the SFTP client sending the corresponding number of read requests to the server without waiting synchronously on an ACK for each one.  This significantly improves performance and is particularly important for connections with higher latency.
The timings below show the time taken in milliseconds to download a 1GB file at various latencies between an Alpakka SFTP client and an openssh SFTP server.
```
0ms
64 reads: 32683ms
32 reads: 35815ms
16 reads: 35298ms
8 reads: 38902ms
20ms
64 reads: 42407ms
32 reads: 48456ms
16 …
```
> FTP: Enable SFTP connector to issue more than one unconfirmed read request

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpIOGraphStage.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/CommonFtpStageSpec.scala
Stop using the failure side of `IOResult` which was [deprecated in akka 2.6.x](https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html#iosources-fileio).
Previously, failures materialized as a _successful_ `Future` with the exception buried in the `IOResult`.
I'm using `IOOperationIncompleteException` as the exception for `Ftp.fromPath`/`Ftp.toPath` to keep the APIs consistent with `FileIO`.
References #2474
> FTP: fix deprecations for `IOResult.createFailed`

- build.sbt
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSchedulerSourceStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSchedulerSource.scala
- kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/KinesisTest.java
- kinesis/src/test/java/docs/javadsl/KinesisFirehoseSnippets.java
- kinesis/src/test/java/docs/javadsl/KinesisSnippets.java
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/DefaultTestContext.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisMock.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseMock.scala
- kinesis/src/test/scala/docs/scaladsl/KclSnippets.scala
- kinesis/src/test/scala/docs/scaladsl/KinesisFirehoseSnippets.scala
- kinesis/src/test/scala/docs/scaladsl/KinesisSnippets.scala
- project/Dependencies.scala
- solr/src/test/java/docs/javadsl/SolrTest.java
- solr/src/test/scala/docs/scaladsl/SolrSpec.scala
Upgrading all `kinesis` dependencies and removing the `akka.stream.{ActorMaterializer, Materializer}` kinesis tests as akka streams now uses the system wide materializer
Also applies updates from Akka 2.6 for solr.
References #2487 
References #2498
> Kinesis and solr Akka 2.6 updates and other things

- build.sbt
- project/Dependencies.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/impl/UnixDomainSocketImpl.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/javadsl/UnixDomainSocket.scala
- unix-domain-socket/src/main/scala/akka/stream/alpakka/unixdomainsocket/scaladsl/UnixDomainSocket.scala
- unix-domain-socket/src/test/java/docs/javadsl/UnixDomainSocketTest.java
- unix-domain-socket/src/test/scala/docs/scaladsl/UnixDomainSocketSpec.scala
- Update unix-domain-socket according to the checklist in #2505 
- Update unix-domain-socket dependencies to their latest version
References #2505
> Update unix-domain-socket to Akka 2.6

- build.sbt
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/impl/OrientDbFlowStage.scala
- orientdb/src/test/java/docs/javadsl/OrientDbTest.java
- orientdb/src/test/scala/docs/scaladsl/OrientDbSpec.scala
- project/Dependencies.scala
- Update OrientDB according to the checklist in #2491 
- Update OrientDB dependencies to their latest version
I've kept `fatalWarnings` set to `false` due to the deprecation warnings from the OrientDB SDK. I looked at it a little bit but it seems like quite a large refactor to update Alpakka to not use deprecated APIs
References #2491
> Update OrientDB to Akka 2.6

- docker-compose.yml
- orientdb/src/main/scala/akka/stream/alpakka/orientdb/impl/OrientDbFlowStage.scala
Fixes #2605 
References #2491 
The OrientDB Java API has changed significantly since the last "makeover" in #1445. This should get things working for now.
> OrientDB: Propagate correct types to updated OrientDB Java API

- docs/src/main/paradox/jms/consumer.md
- jms/src/main/mima-filters/2.0.0-M2.backwards.excludes/PR2583.excludes
- jms/src/main/resources/reference.conf
- jms/src/main/scala/akka/stream/alpakka/jms/JmsConsumerSettings.scala
- jms/src/main/scala/akka/stream/alpakka/jms/JmsExceptions.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsAckSourceStage.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsConnector.scala
- jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSharedServerSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsBufferedAckConnectorsSpec.scala
References #2583 .
Adds timeout for flushing acks back to the JMS broker instead on relying only on buffer completion.
> JMS maxAckInterval

- build.sbt
- docs/src/main/paradox/google-cloud-bigquery.md
- docs/src/main/paradox/google-cloud-pub-sub-grpc.md
- docs/src/main/paradox/google-cloud-pub-sub.md
- docs/src/main/paradox/google-cloud-storage.md
- docs/src/main/paradox/google-common.md
- docs/src/main/paradox/google-fcm.md
- docs/src/main/paradox/index.md
- google-common/src/main/scala/akka/stream/alpakka/google/auth/Credentials.scala
- google-common/src/main/scala/akka/stream/alpakka/google/util/Retry.scala
- google-common/src/test/java/docs/javadsl/GoogleCommonDoc.java
- google-common/src/test/scala/docs/scaladsl/GoogleCommonDoc.scala
References #2623, #2630
Upgrades `google-common` to a full-fledged module, so that it has a published release artifact and docs.
> google-common: create release artifact and docs

- docs/src/main/paradox/google-common.md
Corrects the artifact id in the sbt/maven/gradle section.
> google-common: fix docs typo

- google-common/src/main/scala/akka/stream/alpakka/google/auth/AccessToken.scala
When using a new version of the BigQuery connector I faced that it starts to return the HTTP response with the status code 401 and the message - "Invalid Credentials" after a while. While I was exploring the code of getting a google access token, I noticed, that the field `expiresAt`  of the `AccessToken` class is initializing with the concatenation of seconds and milliseconds. Because of this, the access token did not refresh.
> Google Common: Fix authorization error

- project/Dependencies.scala
This drops the `jwt-core` dependency from the Google connectors since this is now handled in `google-common`.
Unfortunately, this is currently a potentially fatal bug: the `google-common` module depends on a recent version of `jwt-scala` that has a new Maven organization name but retains the same package name as `jwt-core`, which IIUC creates a classpath conflict that SBT will not automatically resolve via eviction. Due to API changes, if the old `JWT` classes are used instead of the new then authorization requests to Google will fail.
> Google: Drop old jwt-core dependencies

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/mima-filters/3.0.0-M1.backwards.excludes/PR2652.excludes
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchConnectionSettings.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchApi.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
The current ElasticsearchAPI only supports basic auth. By including
header options as well as the HttpsContext there would be additional
options to keep previous functionality but still moving forward with
AkkaHttp.
> Elasticsearch has Header and HttpsContext Settings

- google-common/src/main/scala/akka/stream/alpakka/google/ResumableUpload.scala
A small bug fix. Took a while to catch, because it didn't seem to be a problem when running behind a proxy.
> Google Common - Use effective port for GoogleHttp().cachedHostConnectionPool

- .jvmopts
The flag `-XX:+CMSClassUnloadingEnabled` deprecated after the Java 9 release. And it is pointless without the flag `-XX:+UseConcMarkSweepGC` that deprecated too. I would like to remove it from the `.jvmopts`
> Remove the CMSClassUnloadingEnabled jvm flag

- influxdb/src/main/scala/akka/stream/alpakka/influxdb/impl/InfluxDbFlowStage.scala
Fix for back-pressure within the Influxdb alpakka connector. 
I had a problem with it, throwing the error:
`Cannot push port (out(877880393)) twice, or before it being pulled`
Did this small change and now works like a charm.
> Influxdb: emit instead of push in flow stage

- build.sbt
- google-cloud-bigquery/src/main/mima-filters/3.0.0-M1.backwards.excludes/2663-job-configuration
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/javadsl/BigQuery.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/DatasetJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/ErrorProtoJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/JobJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/QueryJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/TableDataJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/TableJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/scaladsl/BigQueryJobs.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/scaladsl/schema/Schema.scala
1. Adds a labels field to `JobConfiguration` and `insertAllAsync`. Not 100% binary compatible to 3.0.0-M1 because of case class stuff, but if important can probably be fixed?
2. Creates a `Schema` singleton object to help materialize implicit `TableSchema` for a class `T`
> BigQuery API improvements

- google-common/src/main/scala/akka/stream/alpakka/google/auth/Credentials.scala
One last fix for 3.0.0 that substantially improves the log messages for application default credentials, especially when they are not found. The previous logging code was badly broken.
> google-common: Improve log messages for application default credentials

- project/Dependencies.scala
jms-testkit 1.0.1 supports Scala 2.x and Scala 3.0.0
> JMS: upgrade to jms-testkit 1.0.1

- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
References #2354
This adds, in the documentation examples, `.withSubscription` to the `AcknowledgeRequest` construction. The current example code would have acks failing with an invalid resource error.
> Google Pub/Sub gRPC: docs for subscription in AcknowledgeRequest

- .travis.yml
- scripts/build.sh
Use apt to install jdk8 and always build, test and release with it from travis. Apt setup copied from akka-persistence-cassandra.
References #2680
> Use JDK 8 for ci

- google-cloud-bigquery/src/main/mima-filters/3.0.0.backwards.excludes/2679-query-request
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/model/QueryJsonProtocol.scala
- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/scaladsl/BigQueryQueries.scala
I want to add extra params to the BigQuery query request. 
- `location` the geographic location where the job should run
- `maximumBytesBilled` limits the number of bytes billed for this query
These params described here https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#QueryRequest
> [BigQuery] Add extra params to the QueryRequest

- udp/src/main/scala/akka/stream/alpakka/udp/impl/UdpBind.scala
- udp/src/main/scala/akka/stream/alpakka/udp/impl/UdpSend.scala
- udp/src/main/scala/akka/stream/alpakka/udp/javadsl/Udp.scala
- udp/src/main/scala/akka/stream/alpakka/udp/scaladsl/Udp.scala
- udp/src/test/java/docs/javadsl/UdpTest.java
- udp/src/test/scala/docs/scaladsl/UdpSpec.scala
I have extended the UDP bind / send flows to allow passing SocketOptions to the Akka UDP manager.
I have a requirement to join channels once the socket is bound and this wasn't possible without the ability to pass options.
This is my first stab at writing any Scala code, so apologies if there are any linting / coding idioms I may have missed.
> UDP: flow with socket options

- jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
- jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsAckConnectorsSpec.scala
I found that in some cases when JMS session is closed the acks queue is left non-empty. This is leading to reprocessing uncommitted messages on another session. The test cases that I modified is irregularly failing if you comment out my changes to the session code.
> Drain JMS acks queue when session is closed

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/WriteMessage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/RestBulkApi.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/RestBulkApiV5.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/RestBulkApiV7.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpecUtils.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV5Spec.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV7Spec.scala
`Operation.Nop` to permit a pass-through `WriteMessage` that does not do any index changes.
For example, if `Source` is a kafka message and `Sink` is a kafka commit, some messages may not warrant any elasticsearch index changes. So pass the message through with a nop.
Fixes #2694
> elasticsearch: Nop

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStageTest.scala
Invocation of an ES endpoint may not be complete and thus returning failed future. This can happen if the host is not reachable (covered in the test) or in other cases. The one that happened in my project was caused by misconfigured Akka HTTP Client. The server was not responding in the desired time (1 second) and the Future was completed with a failure (`akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [xxx:yyyy], no bytes passed in the last 1 second`). The failure was not handled, and the whole stream was stoping processing without any notification.
In this fix, I added a `recoverWith` and invoke the `failureHandler` within it.
> Handle failed Future when invoking ES endpoint

- s3/src/main/scala/akka/stream/alpakka/s3/S3Headers.scala
- s3/src/main/scala/akka/stream/alpakka/s3/headers/ServerSideEncryption.scala
The `equals` method in `MetaHeaders` incorrectly checks if the other type is a `S3Headers`. This is likely an accident since in both cases both types have a field called `metaHeaders`
> Fix equals method for MetaHeaders and AES256

- docs/src/main/paradox/elasticsearch.md
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchSource.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchConnectorBehaviour.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchSpecUtils.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV5Spec.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV7Spec.scala
Fix for https://github.com/akka/alpakka/issues/2656 also a partial fix for https://github.com/akka/alpakka/issues/591 (only for sort)
Support for user-defined sort in elasticsearch connector.
Previously, `sort=_doc` query param was forced, and SprayJsonReader reversed the order for each chunk (I'm curious why?).
if sort is in searchParams keep it and do not add query param, else add `sort=_doc` query param (as before)
Changing response order when _doc is used is not breaking since by design _doc does not guarantee any order
with docs with prices indexed in order `[1,2,3,4,5,6]` and passing a sort in `searchParams`
```
GET /_search?scroll=1m&sort=_doc
{
"size": 2,
"sort": ["price"]
}
```
=>
after reader `[2,1,4,3,6,5]`
```
GET /_search?scroll=1m&sort=_doc
{
"size": 2,
"sort": [{"price": …
```
> elasticsearch: support for sort in searchparams

- s3/src/main/scala/akka/stream/alpakka/s3/Utils.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
So we've been trying to use alpakka with IBM Cloud Object Storage (COS). We observed that COS worked with all the standard S3 tooling, but `multipartCopy` did not work with Alpakka and would fail with a "no such part" error. After some digging, it turns out that COS does not quote the ETag in the `CopyPart` response. Alpakka assumes this to be quoted, and simply drops the first and last character. This ends up mangling the ETag, causing it to not be found when completing the copy.
Standard S3 libraries [removes quotes *if present*](https://github.com/aws/aws-sdk-java/blob/f935a3758b771a25f628f1d296cb61044a82b4ac/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L122), so it works correctly in this case. Although one might argue that COS should quote the …
> Only remove ETag quotes conditionally

- google-cloud-bigquery/src/main/scala/akka/stream/alpakka/googlecloud/bigquery/scaladsl/BigQueryTableData.scala
> BigQuery: Use `effectivePort` instead of `port`

- docs/src/main/paradox/sns.md
This documentation is about SNS not SQS so I fixed the name. Let me know if I need to make an issue.
> AWS SNS: Fix incorrect SQS name

- google-common/src/main/resources/reference.conf
> Google Common: Fix path to the well-known credentials file

- file/src/main/scala/akka/stream/alpakka/file/impl/archive/TarReaderStage.scala
* to avoid pull twice bugs
* maybe too defensive in some of the cases but since
the handler switching and pulling from several places
is rather difficult to follow it's better to be safe than sorry
Fixes #2714
> TarReaderStage only pull when needed, #2714

- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
- s3/src/test/scala/akka/stream/alpakka/s3/S3SettingsSpec.scala
The config parser for `S3Settings` uses `c.hasPath("forward-proxy")` to see if any of the values inside of `forward-proxy` in order to determine whether to skip parsing the entire `forward-proxy` section.
Unfortunately `c.hasPath` returns `true` if you provide optional environment overrides even when they are not set, i.e. if you do something like this (which is a supported typesafe config way of overriding specific config)
```
forward-proxy {
host = ${?HOST}
port = ${?PORT}
credentials {
username = ${?CREDENTIALS_USERNAME}
password = ${?CREDENTIALS_PASSWORD}
}
}
```
and you don't actually set any of these environment variables then `S3Settings` will immediately fail on instantiation with 
```
com.typesafe.config.ConfigException$Missing: reference.conf  No configuration setting found for …
```
> AWS S3: Skip forward-proxy settings on optional overrides

- s3/src/main/scala/akka/stream/alpakka/s3/impl/Chunk.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/DiskBuffer.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/MemoryBuffer.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/DiskBufferSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/MemoryBufferSpec.scala
We seem to hit a very peculiar bug where the HTTP pool is stuck in the `WaitingForEndOfRequestEntity` state.
It's sort of a workaround for that as strict entities don't go that state.
Regardless, I believe using a strict entity should be good for performance.
If this is a change that can be merged, I will update the test code.
> AWS S3: use strict http entity for in-memory chunks

- google-common/src/main/scala/akka/stream/alpakka/google/GoogleSettings.scala
- google-common/src/test/scala/akka/stream/alpakka/google/GoogleSettingsSpec.scala
This PR is the equivalent of https://github.com/akka/alpakka/pull/2720 however its done on `GoogleSettings` rather than `S3Settings`.
Note that since there wasn't any existing test for `GoogleSettings` I created a `GoogleSettingsSpec`
> Google common: ignore forward-proxy on optional environment vars

- docs/src/main/paradox/file.md
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/ZipReaderSource.scala
- file/src/main/scala/akka/stream/alpakka/file/javadsl/Archive.scala
- file/src/main/scala/akka/stream/alpakka/file/model.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/Archive.scala
- file/src/test/java/docs/javadsl/ArchiveTest.java
- file/src/test/scala/docs/scaladsl/ArchiveSpec.scala
docs are missing, the basic test works, ideas welcome :)
> file: unzip introduced

- google-cloud-storage/src/main/resources/reference.conf
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCSAttributes.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/GCSExt.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/settings.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/GCSExtSpec.scala
- google-cloud-storage/src/test/scala/akka/stream/alpakka/googlecloud/storage/GCSSettingsSpec.scala
This PR adds a `GCSSettings` for `google-cloud-stroage` in order to give the ability to configure the host and the basePath. This is mainly done due to the fact that its currently not possible to test GCS using an implementation such as https://github.com/fsouza/fake-gcs-server since the endpoints are hardcoded at https://github.com/akka/alpakka/blob/f2971ca8a4a71b541cddbd5bf35af3a2a56efe71/google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala#L33-L34.
Of note is there was a previous `GCStorageSettings` which was deprecated beforehand since there are a lot of settings that are shared between Google services. In order to not create conflicts/confusion, a seperate `GCSSettings` was created and it contains settings that are **only** specific …
> Add GCSSettings to make endpointUrl + basePath configurable

- file/src/main/java/akka/stream/alpakka/file/impl/DirectoryChangesSource.java
Properly include path in exception message.
I guess someone mixed up Scala and Java :wink:
> file: Fix exception message

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourceStage.scala
- elasticsearch/src/test/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSourcStageTest.scala
application of PR#2702 to ElasticsearchSourceStage
References #2702 which fixes the issue in the ElasticsearchSimpleFlowStage
> Handle failed Future when invoking ES endpoint in Source

- s3/src/main/scala/akka/stream/alpakka/s3/Utils.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
This PR adds https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListMultipartUploads.html and https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html to the S3 API with the ultimate aim of being able to automatically resume a previously aborted S3 multipart upload with the same given bucket/key in the same way that `GCStorage.resumableUpload` works
The implementation of `S3.resumableUpload` still needs to be done using the rough logic outlined in https://stackoverflow.com/questions/53764876/resume-s3-multipart-upload-partetag. The basic implementation of `S3.resumableUpload` is as follows
1. Firstly check if there have been any previously aborted/cancelled multipart uploads for the same given key/bucket by using `S3.listMultipartUpload`. If not then just call already existing …
> S3: Add MultiPartUpload and ListParts APIs

- s3/src/main/scala/akka/stream/alpakka/s3/S3Attributes.scala
- s3/src/main/scala/akka/stream/alpakka/s3/S3Ext.scala
- s3/src/main/scala/akka/stream/alpakka/s3/S3Headers.scala
- s3/src/main/scala/akka/stream/alpakka/s3/headers/ServerSideEncryption.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/package.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/main/scala/akka/stream/alpakka/s3/settings.scala
This PR does some minor cleanups which are self explanatory (see the commit messages).
> S3: Minor cleanups

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
The intention of this PR is to make `eTag`/`ETag` consistent. This was done with internal private API but also the public API where `MultipartUploadResult` used `etag`/`getEtag`/`getEtag` where as every other public model used `eTag`/`getETag`/`withETag`. Since this is a public API I added `deprecated` methods so that people are warned when using the old inconsistent etag naming and to maintain binary compatibility.
There is one case where (I think) source compatibility is broken but NOT binary compatibility (see comments). Unfortunately I couldn't get mima running in Alpakka to verify this, I am getting the following error when I run `s3 / mimaReportBinaryIssues`
```
[error] (s3 / mimaReportBinaryIssues) java.lang.NoClassDefFoundError: Could not initialize class …
```
> S3: Make eTag naming consistent

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
There seems to be another inconsistency between real AWS and Minio wrt creating a bucket in the non default region (i.e. `us-east-1`). With AWS S3 you need an addition XML payload (along with the host/access-style which typically contains the region) in order to create a bucket in a non default `us-east-1` region, with Minio this payload is not required. If the XML payload is not in the make bucket request on AWS you will get the following error
```
The unspecified location constraint is incompatible for the region specific endpoint this request was sent to..
```
For more details you can read https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html , there is already an existing issue at https://github.com/aws/aws-cli/issues/2603#issuecomment-422271388 which demonstrates the …
> S3: Allow bucket creation besides `us-east-1` for AWS

- docs/src/main/paradox/sse.md
> SSE docs: Fix typo in "Last-Event-ID"

- csv/src/main/java/akka/stream/alpakka/csv/javadsl/CsvToMap.java
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvToMapJavaStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/impl/CsvToMapStage.scala
- csv/src/main/scala/akka/stream/alpakka/csv/scaladsl/CsvToMap.scala
- csv/src/test/java/docs/javadsl/CsvToMapTest.java
- csv/src/test/scala/docs/scaladsl/CsvToMapSpec.scala
This PR adds a couple of function that basically allows the user to include the empty fields (using some placeholders) in cases where there are more headers than data (or vice-versa) in the csv being transformed to a Map.
Examples:
1. When there are more data than headers
```csv
eins,zwei
11,12,13
```
maps to
```scala
Map("eins" -> "11", "zwei" -> "12", "Missing header" -> "13")
```
The "Missing header" value is the default one, the user has the option to pass a custom value for this placeholder.
2. When there are more headers than data
```csv
eins,zwei,drei,vier,fünt
11,12,13
```
maps to
```scala
Map("eins" -> "11", "zwei" -> "12", "dreir" -> "13", "vier" -> "", "fünt" -> "")
```
This would be helpful, especially in the second case, when I want to keep the headers even when I don't have …
> CSV: Use placeholders when header and data length differs

- build.sbt
- project/AutomaticModuleName.scala
- project/Common.scala
- project/build.properties
- project/plugins.sbt
- sbt 1.5.5 (and use slash syntax)
- sbt plugin updates
> sbt 1.5.5 and plugin updates

- testkit/src/main/scala/akka/stream/alpakka/testkit/CapturingAppender.scala
- testkit/src/main/scala/akka/stream/alpakka/testkit/LogbackUtil.scala
- testkit/src/main/scala/akka/stream/alpakka/testkit/javadsl/LogCapturingJunit4.scala
- testkit/src/main/scala/akka/stream/alpakka/testkit/scaladsl/LogCapturing.scala
- testkit/src/main/scala/akka/stream/alpakka/testkit/scaladsl/Repeated.scala
As it turns out, the testkit used directory names with `.` in them instead of the regular file layout.﻿
This PR moves the files and fixes their headers.
> fix: use directories in testkit

- s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/MemoryWithContext.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSizeWithContext.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/model.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/SplitAfterSizeWithContextSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
References #2760 
This PR is an implementation of the above referenced ticket. It adds custom versions of `multipartUpload`/`resumeMultipartUpload` that allows you to pass a context with the intention of being able to act on that context whenever a chunk is uploaded to S3, either successfully or unsuccessfully. This is done by providing a `chunkUploadSink: Sink[(UploadPartResponse, immutable.Iterable[C]), NotUsed]` which is a `Sink` that gets executed whenever the said Chunk is uploaded. For a very brief summary of the context of this PR, I want to be able to commit kafka commit cursors after S3 successfully uploads a chunk (with the source being kafka messages).
Notes are listed below
- You may have noticed that the `Sink[(UploadPartResponse, immutable.Iterable[C]), NotUsed]` has an …
> S3: Add multipart upload with context

- google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala
References #2753 
Th rewrite creates it's own internal streams without setting the correct attribute
> pass correct GoogleAttributes in rewrite flow

- CONTRIBUTING.md
- google-common/src/main/resources/reference.conf
- google-common/src/main/scala/akka/stream/alpakka/google/auth/Credentials.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/UserAccessCredentials.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/UserAccessMetadata.scala
Our devs normally acquire credentials through `gcloud auth application-default login` on their personal computers. This creates a file in the well-known credentials file location.
We already try to parse the file found in this location into a service account credentials file. However, credentials acquired this way will have a different format and can not be used as service account credentials. In addition, tokens are obtained a bit differently as we have to use a refresh token and a different endpoint.
I have essentially duplicated the functionality for authorizing with service accounts, altered the expected json format, and changed the endpoint for token generation. Let me know if this is something we would be interested to merge into the main repo and I'll gladly make the necessary …
> Google common: user access credentials

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
enable to authenticate without login/password
headers not forward on `onPush()` method in ElasticsearchSimpleFlowStage https://github.com/akka/alpakka/blob/3f1b06faa0d179adca5f072a1b6487acab1fb389/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala#L78-L80
forward header from ElasticsearchConnectionSettings headers to HttpRequest header
> Elasticsearch: forward headers on bulk insert in SimpleFlowStage

- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
The `Source.queue` implementation has been modified a few times since Akka 2.6 was released which broke this test.
> mqtt-streaming: Accommodate source.queue change in Akka 2.6

- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/javadsl/KinesisFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
- kinesis/src/test/scala/docs/scaladsl/KinesisSnippets.scala
Is one possibility for solving contexts that need handling when writing to a Kinesis data stream fails
References #2814
> Kinesis: clean up contexts in kinesisFlowWithContext on failure

- docker-compose.yml
- project/Dependencies.scala
* Cassandra Java driver 4.13.0
* drop explicit Jackson, the driver pulls Jackson 2.12.2 
* run against current Cassandra 4.0
> cassandra: driver 4.13.0

- json-streaming/src/test/scala/docs/scaladsl/JsonReaderTest.scala
This PR adds a test to verify if unwrapping a JSON array from a top level element works if there are multiple top level JSON array's. The context of the test is here https://discuss.lightbend.com/t/working-with-eof-for-a-source-flow/9481
I think adding this test would be a good idea to verify such behaviour
> json streaming: test for multiple top level array's

- project/Dependencies.scala
- scripts/link-validator.conf
On top of #2820 to check if latest snapshot works (in preparation of 10.2.9).
> Use Akka HTTP 10.2.9

- dynamodb/src/test/java/docs/javadsl/RetryTest.java
- dynamodb/src/test/scala/docs/scaladsl/RetrySpec.scala
- project/Dependencies.scala
The current AWS SDK seems compatible enough.
It does not itself use Jackson anymore so I dropped the Jackson version bump dependencies.
> AWS connectors: use AWS SDK 2.17.113

- build.sbt
- docker-compose.yml
- dynamodb/src/test/java/docs/javadsl/ExampleTest.java
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ItemSpec.scala
- dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/TableSpec.scala
- dynamodb/src/test/scala/docs/scaladsl/ExampleSpec.scala
- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchConnectionSettings.scala
- elasticsearch/src/test/java/docs/javadsl/ElasticsearchTestBase.java
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchConnectorBehaviour.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV5Spec.scala
- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV7Spec.scala
- google-cloud-bigquery-storage/src/test/scala/akka/stream/alpakka/googlecloud/bigquery/storage/mock/BigQueryMockServer.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala
- google-cloud-pub-sub/src/test/scala/docs/scaladsl/IntegrationSpec.scala
- google-common/src/main/scala/akka/stream/alpakka/google/http/ForwardProxyHttpsContext.scala
- huawei-push-kit/src/main/scala/akka/stream/alpakka/huawei/pushkit/ForwardProxyHttpsContext.scala
- project/Dependencies.scala
- s3/src/main/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequest.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/HttpRequestsSpec.scala
- s3/src/test/scala/akka/stream/alpakka/s3/impl/auth/CanonicalRequestSpec.scala
- scripts/link-validator.conf
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsPublishSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsSourceSpec.scala
- sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala
- sse/src/test/scala/docs/scaladsl/EventSourceSpec.scala
Rebased @mrooding's PR #2650 to only use the current Akka HTTP version.
Will need a few more changes to avoid deprecated APIs.
Supersedes #2650
> Use akka-http 10.2.9

- docs/src/main/paradox/kinesis.md
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/javadsl/KinesisFlow.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisFlowSpec.scala
- kinesis/src/test/scala/docs/scaladsl/KinesisSnippets.scala
> Kinesis: remove cleanup function, separate batching and writing

- project/Dependencies.scala
The kinesis client is over 1 year old, and the recently released version 2.4 contains several bugfixes and, some even directed towards Scala
https://github.com/awslabs/amazon-kinesis-client/blob/master/CHANGELOG.md
> updated kinesis client to 2.4.0

- project/Dependencies.scala
Updates alpakka to use the newest released version of Akka
> bump: Akka 2.6.19

- .github/workflows/check-build-test.yml
- docker-compose.yml
- docs/src/main/paradox/s3.md
- project/Dependencies.scala
- s3/src/test/scala/akka/stream/alpakka/s3/MinioContainer.scala
- s3/src/test/scala/akka/stream/alpakka/s3/MinioS3Test.scala
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
Replaces manual starting of minio docker containers in github actions/docker-compose with https://github.com/testcontainers/testcontainers-scala. The changes are a bit more involved than originally anticipated mainly as a result of a race condition between Actor initialization of a typesafe `Config` and testcontainers starting (basically the issue is that when you do `ActorSystem(config)` this will evaluate immediately when the test initializes which is an issue since that is before the `beforeAll` of scalatest (and hence before container actually starts via testcontainers-scala-scalatest). Note that the usage of `lazy val` is also due to this, i.e. we only want to evaluate settings when needed (which is when the tests are actually run and not immediately)
The solution was rather than …
> AWS S3: Use testcontainer-scala-scalatest to setup Minio docker

- docs/src/main/paradox/avroparquet.md
- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
This PR addresses the issue referenced below by ensuring that custom S3 headers passed to multipart copy are included when copying parts and in the final completion request. 
References #2839
> AWS S3: Include custom headers in all multipart copy requests

- project/project-info.conf
The coming Alpakka Couchbase release will not be considered supported.
> Couchbase: retract supported level

- google-cloud-pub-sub-grpc/src/test/scala/docs/scaladsl/IntegrationSpec.scala
especially ByteString is useful to include explicitly, not to confuse
it with `akka.util.ByteString`
> google-cloud-pub-sub-grpc: more imports in sample code

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/main/scala/akka/stream/alpakka/s3/javadsl/S3.scala
- s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3.scala
- s3/src/test/java/docs/javadsl/S3Test.java
- s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala
- s3/src/test/scala/docs/scaladsl/S3SourceSpec.scala
PR adds in the `S3.getObject` method which is an alternative to `S3.download` that has a far simpler/idiomatic API (returns a `Source[ByteString, Future[ObjectMetadata]]` instead of a `Source[Option[(Source[ByteString, NotUsed], ObjectMetadata)], NotUsed]` as well as deprecating `S3.download`. Since no `Option` is returned in `S3.getObject` there is no chance of accidentally creating a leak (with `S3.download` if it returned a `Some` but you didn't consume the underlying `ByteString` `Source` a leak would be created, see referenced issue).
Nothing that fancy in the actual implementation of `Se.getObject`, most changes were mechanical. The materialized value `ObjectMetdata` is propagated by using a `Promise` and all of the tests have been updated to use `S3.getObject`. The old …
> Add S3.getObject and deprecate S3.download

- jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsMessageProducer.scala
- jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
- added support to produce messages with byte array properties
- updated test cases for this scenario
"Fixes #2889"
> JMS - Add support for byte array message properties #2889

- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- project/Dependencies.scala
Current versions of commons-net and sshj for use in Alpakka FTP.
> bump: libs for ftp

- project/plugins.sbt
Upgrades to the current Akka gRPC version (but couldn't remove the workaround introduced by #2678).
> Google PubSub gRPC and BigQuery Storage: Akka gRPC 2.1.5

- .github/workflows/check-build-test.yml
- .github/workflows/publish.yml
Bumps to
- https://github.com/coursier/cache-action/releases/tag/v6.3.3
- https://github.com/coursier/setup-action/releases/tag/v1.2.1
> CI: current Coursier actions

- project/Dependencies.scala
* align with Akka 2.7.x
* CVE-2020-36518
> Update Jackson dependency to 2.13.4

- project/Dependencies.scala
- solr/src/main/scala/akka/stream/alpakka/solr/impl/SolrFlowStage.scala
- solr/src/test/java/docs/javadsl/SolrTest.java
- solr/src/test/scala/docs/scaladsl/SolrSpec.scala
* getIdField in SolrFlowStage.scala:109 is reported as deprecated, but I don't know what it should be replaced with. Create issue https://github.com/akka/alpakka/issues/2917 for this.
> Update solrj dependency to 8.11.1

- project/Dependencies.scala
* in hdfs and hbase modules
Same version as Avro Parquet that was changed in https://github.com/akka/alpakka/pull/2916
> Update hadoop to 3.3.3

- project/Dependencies.scala
Ensure Alpakka Cassandra uses the current version of Jackson.
(java-driver-core 4.14.1 brings in 2.13.2)
> Cassandra: pick current Jackson version

- project/Dependencies.scala
Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-42003 (even if we were not really affected out of the box).
> bump: Jackson databind 2.13.4.1

- CONTRIBUTING.md
Mentioning explicit step of making sure the `git` executable is in the system's `PATH` environment variable to resolve issue #2893.
> Adding some basic development setup information.

- .github/workflows/check-build-test.yml
- .github/workflows/fossa.yml
- .github/workflows/link-validator.yml
- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
- scripts/link-validator.conf
Current Fossa CLI install URL.
GitHub workflow housekeeping (to not hit Node 12 EOL):
- checkout v3
- coursier/setup-action instead of olafurpg/setup-scala
References https://github.com/akka/alpakka-kafka/pull/1574
> chore: current GH actions; coursier/setup-action; Fossa install

- docker-compose.yml
- project/Dependencies.scala
FTP tests have been failing on CI as the `datadog/squid` image is not available anymore.
> ftp(test): use ubuntu/squid Docker image

- xml/src/main/scala/akka/stream/alpakka/xml/impl/StreamingXmlParser.scala
- xml/src/main/scala/akka/stream/alpakka/xml/javadsl/XmlParsing.scala
- xml/src/main/scala/akka/stream/alpakka/xml/scaladsl/XmlParsing.scala
- xml/src/test/scala/docs/scaladsl/XmlProcessingSpec.scala
This pull request adds a contextual version of the parser provided by `XmlParsing`. 
API-wise, I was not entirely sure how to set this up, since different modules seem to follow different conventions. For example, the Cassandra module provides a `withContext` method directly in the `CassandraFlow` object (https://github.com/akka/alpakka/blob/4f77c8b6b7e443acb39fa3164613c19a626e530f/cassandra/src/main/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraFlow.scala), but the AMQP module provides its own `AmqpFlowWithContext` object with contextual variants (https://github.com/akka/alpakka/blob/4f77c8b6b7e443acb39fa3164613c19a626e530f/amqp/src/main/scala/akka/stream/alpakka/amqp/scaladsl/AmqpFlowWithContext.scala).
> XML: Add a contextual version of the parser for XML

- mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala
- mongodb/src/test/scala/docs/scaladsl/MongoSourceSpec.scala
- project/Dependencies.scala
More info https://www.mongodb.com/docs/drivers/java/sync/current/whats-new/
> Mongo: driver 4.7.2 (was 4.4.0), adds full support for MongoDB 6.0

- docs/src/main/paradox/pravega.md
Most likely due to Heroku's new pricing, the Slack invite page has been taken down.
> docs(pravega): remove broken Slack link

- build.sbt
- docs/src/main/paradox/ftp.md
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
The link checker is even happier than before.
Makes the Scala XML 2.1 jump.
References
- https://github.com/sbt/sbt/releases/tag/v1.8.2
- https://github.com/akka/akka-http/releases/tag/v10.5.0-M1
- https://github.com/akka/akka-grpc/releases/tag/v2.3.0-M2
- https://github.com/sbt/sbt-site/releases/tag/v1.5.0-RC2
> bump: sbt 1.8.2, sbt-site 1.5, Akka 23.02

- project/Dependencies.scala
Even bumps
- google-auth-library-credentials 1.15.0 (was 0.24.1)
Even bumps test lib
- Mockito 2.8.1 (was 2.8.0)
> bump(google-common): jwt-spray-json 9.0.2 (was 7.1.4)

- docker-compose.yml
- project/Dependencies.scala
- Google cloud SDK/emulator 416 (was 311); 
- Pub/Sub gRPC protobuf 1.123.1 (was 1.112.5)
References 
- #2454
> bump: Google cloud SDK/emulator 416; Pub/Sub gRPC 1.123.1

- s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala
- s3/src/test/scala/docs/scaladsl/S3SinkSpec.scala
Not very explicit in the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html#API_CompleteMultipartUpload_Examples), but other headers beside the sse headers are not allowed for this particular request (`completeMultipartUpload`).
Fixes https://github.com/akka/alpakka/issues/2906 and reverts a small part from https://github.com/akka/alpakka/pull/2844.
> Ensure to only pass sse headers to completeMultipartUpload

- .github/workflows/link-validator.yml
Publishing docs runs on JDK 11 and thus JavaDoc 11, the regular link checker should use the same version as URLs are affected.
https://github.com/akka/alpakka/blob/3d8b41ffe8c5904b8d2d197d642939d26a84d4ee/.github/workflows/publish.yml#L64-L67
> chore: run link checking on JDK 11

- mqtt-streaming/src/main/mima-filters/5.1.0-M1.backwards.excludes/mqtt-streaming
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ClientState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/RequestState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/impl/ServerState.scala
- mqtt-streaming/src/main/scala/akka/stream/alpakka/mqtt/streaming/model.scala
- mqtt-streaming/src/test/java/docs/javadsl/MqttFlowTest.java
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttCodecSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttFlowSpec.scala
- mqtt-streaming/src/test/scala/docs/scaladsl/MqttSessionSpec.scala
As @ohze pointed out a long while ago, when subscribing Alpakka MQTT streaming sent the Quality of Service uncorrectly.
With the details @sbmpost added it became apparent that the code made the wrong assumption the QoS was encoded the same for Subscribe and Publish, but it is not.
The first commit contains the test case suggested by @ohze.
The second commit changes the API slightly to separate QoS encoding for the two message types.
The third commit re-enables a test case that was ignored due to regular failure. Which seems related.
Fixes
- #2731 
- #1549
> fix(mqtt-streaming): Separate MQTT QoS by message type (#2969

- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpMocking.scala
- aws-event-bridge/src/test/scala/akka/stream/alpakka/aws/eventbridge/DefaultTestContext.scala
- awslambda/src/test/scala/docs/scaladsl/AwsLambdaFlowSpec.scala
- cassandra/src/test/java/docs/javadsl/CassandraFlowTest.java
- cassandra/src/test/java/docs/javadsl/CassandraTestHelper.java
- google-cloud-bigquery-storage/src/test/scala/docs/scaladsl/ExampleReader.scala
- google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/GooglePubSubSpec.scala
- google-common/src/test/scala/akka/stream/alpakka/google/http/GoogleHttpSpec.scala
- google-fcm/src/test/scala/akka/stream/alpakka/google/firebase/fcm/v1/impl/FcmSenderSpec.scala
- huawei-push-kit/src/test/scala/akka/stream/alpakka/huawei/pushkit/impl/HmsTokenApiSpec.scala
- huawei-push-kit/src/test/scala/akka/stream/alpakka/huawei/pushkit/impl/PushKitSenderSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsProducerRetrySpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/JmsSpec.scala
- jms/src/test/scala/akka/stream/alpakka/jms/impl/JmsMessageProducerSpec.scala
- jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/DefaultTestContext.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesis/KinesisMock.scala
- kinesis/src/test/scala/akka/stream/alpakka/kinesisfirehose/KinesisFirehoseMock.scala
- mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala
- mongodb/src/test/scala/docs/scaladsl/MongoSourceSpec.scala
- project/Dependencies.scala
- sns/src/test/scala/akka/stream/alpakka/sns/DefaultTestContext.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishSinkSpec.scala
- sqs/src/test/scala/akka/stream/alpakka/sqs/scaladsl/SqsSourceMockSpec.scala
- sqs/src/test/scala/docs/scaladsl/SqsAckSpec.scala
Dropping the not too useful ScalaTest+ Mockito dependency which is not published for Scala 2.12 for this ScalaTest version.
Fixed some implicit resolution issue in Mongo tests.
> bump: ScalaTest 2.3.15 (was 2.3.11) + drop ScalaTest+ Mockito

- project/Dependencies.scala
- project/plugins.sbt
- scripts/link-validator.conf
We somehow missed that Alpakka was using Akka gRPC and Akka HTTP milestone versions when cutting Alpakka 6.0.
- Akka 2.8.1 (was 2.7.0)
- Akka gRPC 2.3.1
- Akka HTTP 10.5.1
Bumping these Akka versions requires bumping to Scala 3.2.
Align the Jackson version with Akka 2.8.1
> bump: Akka 23.05 versions (Akka gRPC, Akka HTTP, Akka)

- file/src/main/scala/akka/stream/alpakka/file/impl/archive/FileByteStringSeparators.scala
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlow.scala
- file/src/main/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveManager.scala
- file/src/main/scala/akka/stream/alpakka/file/javadsl/Archive.scala
- file/src/main/scala/akka/stream/alpakka/file/scaladsl/Archive.scala
- file/src/test/scala/akka/stream/alpakka/file/impl/archive/ZipArchiveFlowTest.scala
- file/src/test/scala/docs/scaladsl/ArchiveSpec.scala
> File: Add zip compression level

- elasticsearch/src/test/scala/docs/scaladsl/ElasticsearchV5Spec.scala
Noticed that [here](https://doc.akka.io/docs/alpakka/current/elasticsearch.html#passing-data-through-elasticsearchflow), in Scala sample, multiple code snippets are being included while the java sample only has one. I think this was due to copy/paste of the tags when creating new tests. Thus, removing the tags so only one example is shown as with the Java counterpart.
> docs: fix multiple examples for commit after write to elasticsearch

- .github/workflows/check-build-test.yml
- .github/workflows/publish.yml
- project/Common.scala
--release 8 was not defined in javacOptions 
However, --release 8 flag prevents access to com.sun.nio.file.SensitivityWatchEventModifier so instead we have to use JDK 8 in the release CI job.
References #2994
> fix: Release with JDK 8, #2994

- ftp/src/main/mima-filters/6.0.3.backwards.excludes
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
- ftp/src/test/java/akka/stream/alpakka/ftp/FtpsWithTrustAndKeyManagersStageTest.java
- project/Dependencies.scala
This fix adds a couple of methods to FtpsSettings to set specific KeyManager and TrustManager.
I understand that the old tag is taken as a basis, but it would be nice to release, for example, version 2.1 with this improvement.
> FTP: Add for FTPS the ability to set KeyManager and TrustManager

- ftp/src/main/mima-filters/6.0.3.backwards.excludes
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/model.scala
References #2998
I've added a method to FtpSettings and FtpsSettings to enable or disable automatic server encoding detection.
> FTP: Add a setting to enable automatic server encoding detection

- .scala-steward.conf
- project/Dependencies.scala
in sync with https://github.com/akka/akka-persistence-cassandra/pull/1048
> bump: Cassandra java-driver-core 4.17.0

- README.md
- project/Dependencies.scala
See https://github.com/akka/akka/pull/32125
> chore: Drop Scala 2.12

- .github/workflows/check-build-test.yml
- .github/workflows/publish.yml
- build.sbt
- project/Common.scala
- project/project-info.conf
https://github.com/akka/akka/pull/32127
> chore: Drop JDK 8

- project/Dependencies.scala
* some aws dependencies have protobuf-java 3.19.2, which has CVE-2022-3171 CVE-2022-3509 CVE-2022-3510
* bumped those to protobuf 3.21.12, which is the same as in akka-grpc
* also bumped to latest patch of awssdk 2.17.295
> bump: protobuf 3.21.12 in aws modules

- amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala
- amqp/src/test/scala/akka/stream/alpakka/amqp/scaladsl/AmqpConnectionProvidersSpec.scala
Offer new cached connection when previous one has been closed and released
References #3023
ℹ️ I'm not sure whether `abort` is the best way to simulate connection closed by the server. Hopefully, for the purpose of unit test, this is good enough
> AMQP Fix #3023

- project/Dependencies.scala
* to align with the bump in Akka gRPC
> bump: protobuf-java 3.24.0

- build.sbt
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpLike.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpsOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/javadsl/FtpApi.scala
- ftp/src/main/scala/akka/stream/alpakka/ftp/scaladsl/FtpApi.scala
- ftp/src/test/scala/akka/stream/alpakka/ftp/BaseSpec.scala
- project/Common.scala
- Enable Scala 3 for Alpakka FTP.
- Syntax changes for the mixin traits.
- Use `-explain` for Scala 3 in CI.
> ftp: Scala 3

- build.sbt
- google-common/src/main/scala/akka/stream/alpakka/google/auth/GoogleOAuth2.scala
- google-common/src/main/scala/akka/stream/alpakka/google/auth/JwtSprayJsonParser.scala
- project/Dependencies.scala
Remove the dependency on `com.github.jwt-scala` `jwt-spray-json` which was discontinued.
Add the relevant sources from that library into google-common which was the only Alpakka part relying in this.
References
- https://github.com/jwt-scala/jwt-scala/pull/318
> Replace Spray JWT dependency

- avroparquet-tests/src/test/java/docs/javadsl/AvroParquetSinkTest.java
- avroparquet-tests/src/test/java/docs/javadsl/Examples.java
- avroparquet-tests/src/test/scala/docs/scaladsl/AbstractAvroParquet.scala
- project/Dependencies.scala
Explicitly bumps Avro to 1.13.1 which brings smaller API changes.
Fixes [CVE-2023-39410](https://github.com/advisories/GHSA-rhrv-645h-fjfh).
> bump: bump avro to 1.13.1 (was 1.8.2)

- .github/workflows/publish.yml
- docs/src/main/paradox/other-docs/webinars-presentations-articles.md
- scripts/link-validator.conf
The DZone article was archived.
Links to Akka HTTP internals fail the link checker.
> chore: avoid broken and outdated links

- elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/impl/ElasticsearchSimpleFlowStage.scala
The current implementation drops any path that is present in the baseUri.
References
- #3019
> Elasticsearch: keep path from base URI

- kinesis/src/main/scala/akka/stream/alpakka/kinesis/impl/KinesisSchedulerSourceStage.scala
- kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisSchedulerSource.scala
The `KinesisSchedulerSourceStage` needs to run the `software.amazon.kinesis.coordinator.Scheduler` in a thread. The scheduler runs a loop and uses `Thread.sleep`, which needs careful use because it is a blocking operation.
Currently, it uses `Future(scheduler.run())`, which will use the implicit `ExecutionContext` from the constructor. By default, this EC will be the akka default dispatcher which is not suitable for blocking. Also, note the use of `ActorAttributes.IODispatcher` in `initialAttributes` which is not having any effect as we are not using the stage materializer.
This PR removes the EC from the constructor, and uses the stage logic materializer EC (which will be the IODispatcher) which is aligned with other custom stages in this project.
> kinesis: use stage materializer with IODispatcher instead of injected EC

- project/build.properties
Strange issues in main on 1.9.9 where javax.jms cannot be found. We did not manage to reproduce that locally, but consistently happens in ghactions.
> bump: Rollback sbt to 1.9.6

- jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
> Handle session thread

- project/Dependencies.scala
- solr/src/test/scala/docs/scaladsl/SolrSpec.scala
Revert
- #3051 
and review all places to stay on Slf4j V1. Some places pulled in V2 in hideous ways.
> revert: logback may not pull slf4j 2.x

- docker-compose.yml
Bumping the ElasticMQ image for testing should make the test succeed.
Refs
- https://github.com/softwaremill/elasticmq/releases/tag/v1.5.8
> bump(sqs test): ElasticMQ image 1.5.8 (was 1.3.4)

- jms/src/main/scala/akka/stream/alpakka/jms/impl/Sessions.scala
> JMS: Swallow IBM MQ exception

- hbase/src/main/scala/akka/stream/alpakka/hbase/impl/HBaseCapabilities.scala
- hbase/src/test/java/docs/javadsl/HBaseStageTest.java
- hbase/src/test/scala/docs/scaladsl/HBaseStageSpec.scala
- project/Dependencies.scala
- project/plugins.sbt
Note: hbase is currently not tested due to mentioned issue.
> bump (Hbase, Hadoop): Hadoop 3.4, Hbase 2.6) fixes CVE-2021-37137

- couchbase/src/main/scala/akka/stream/alpakka/couchbase/scaladsl/CouchbaseFlow.scala
- docker-compose.yml
Avoid failing `couchbase_prep`. Could only test it locally with a newer version of the docker image, but bumping that would have required to bump the java client, which I am trying to avoid for now.
> fix(couchbase): cli args in the same line

- project/Dependencies.scala
This reverts commit 847fafb2cb93ca0b300dd49268686abcbc3077c0.
Showed [here](https://github.com/akka/alpakka/pull/3260) as a red herring, was introduced [here](https://github.com/akka/alpakka/pull/3241).
> Revert "bump: activemq-broker, activemq-client 5.18.5 (was 5.16.7) (#3241)"

- .scala-steward.conf
- docs/src/main/paradox/solr.md
- project/project-info.conf
Also stop further upgrades of EOL connector libraries.
References
- https://github.com/akka/alpakka/pull/3275
- https://github.com/akka/alpakka/pull/3263
> Mark Apache Solr connector EOL

- project/Dependencies.scala
and drop slf4j exclusions as we bumped the version.
References
- https://github.com/slick/slick/releases/tag/v3.5.2
> bump: Slick 3.5.2 (was 3.5.1)

- .github/workflows/check-build-test.yml
- .github/workflows/link-validator.yml
- .github/workflows/publish.yml
- docs/src/main/paradox/azure-storage-queue.md
- project/Dependencies.scala
- scripts/link-validator.conf
- Run the link validator workflow on PRs and merges instead of the "Documentation" part in the main CI workflow
- Cancel the Publish workflow in case another merge happens while it is running
> chore: link validator in separate workflow

- .github/workflows/link-validator.yml
> chore: Reduce link validator schedule

- project/Dependencies.scala
The library has been renamed from sslcontext-kickstart to [ayza](https://github.com/Hakky54/ayza). The latest version is 10.0.0
Sorry for the inconvenience
> FTP (test): Bump and rename sslcontext-kicktart to ayza
